"""The font sheet back into assembler: font.png and font.json -> font.s.

    python font_source.py

font_sheet.py made the pair out of the game's own packed font, and this is the
other half of that round trip: what it writes is what the assembler sees, so
editing the PNG is how the font changes. build.py runs it whenever the sheet
or this script has moved on.

The picture is what counts. font.json is an atlas in the shape the ZX Spectrum
extension's graphics panel reads, and the panel takes a block's bytes from the
atlas rather than from the picture, so each block carries a base64 copy of its
own; this rewrites those from the pixels each time it runs, and the atlas
therefore never falls behind the sheet.

pentagram.s INCLUDEs what comes out, where it used to INCBIN font.bin. The
bytes are the same either way -- a character's eight rows, top row first, one
byte a row -- and the label the printing code reaches for, `font`, is still
the first thing in it.
"""

import argparse
import base64
import json
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent

# A font has no mask, so a pixel is one of two things. The names are the
# contract with font_sheet.py; the colours come out of the atlas.
PIXEL_BITS = {"paper": 0, "ink": 1}
OPAQUE = 128                            # alpha at or above this is a colour


def read_atlas(path):
    """font.json -> the blocks in font order, and our own facts."""
    atlas = json.loads(path.read_text(encoding="utf-8"))
    zx = atlas.get("meta", {}).get("zx", {})
    if "sprites" not in zx or "font" not in zx:
        raise SystemExit(f"{path.name} is not a sheet written by font_sheet.py")
    blocks = sorted(zx["sprites"], key=lambda block: block["firstIndex"])
    return atlas, blocks, zx["font"]


def read_sheet(sheet, atlas, blocks, facts):
    """The sheet's pixels, as eight row bytes a character, in font order."""
    image = Image.open(sheet).convert("RGBA")
    colours = {tuple(rgba[:3]): PIXEL_BITS[name]
               for name, rgba in facts["palette"].items()}
    pixels = image.load()
    cell = facts["cell"]

    characters = []
    for block in blocks:
        if block["firstIndex"] != len(characters):
            raise SystemExit(f"{block['name']} starts at character "
                             f"{block['firstIndex']}, but {len(characters)} "
                             "characters come before it")
        for n, frame in enumerate(block["frames"]):
            box = atlas["frames"][frame]["frame"]
            if box["x"] + cell > image.width or box["y"] + cell > image.height:
                raise SystemExit(f"{frame} runs off {sheet.name}, which is "
                                 f"{image.width}x{image.height}")
            rows = []
            for y in range(cell):
                byte = 0
                for x in range(cell):
                    r, g, b, a = pixels[box["x"] + x, box["y"] + y]
                    if a < OPAQUE:
                        continue        # a gap between the cells; paper
                    if (r, g, b) not in colours:
                        raise SystemExit(
                            f"{frame} has a colour the sheet has no meaning "
                            f"for at ({x}, {y}): #{r:02X}{g:02X}{b:02X}")
                    byte |= colours[(r, g, b)] << (cell - 1 - x)
                rows.append(byte)
            characters.append(rows)
    return characters


def emit(characters, facts):
    glyphs = facts["glyphs"]
    out = [
        "; Generated by font_source.py from font.png -- do not edit.",
        ";",
        "; Pentagram's forty 8x8 characters: the digits, then A to Z, then a",
        "; full stop, a copyright sign, a space and a per-cent sign. Eight bytes",
        "; a character, top row first, one bit a pixel and no mask.",
        ";",
        "; A character code IS its index, which is the whole of why printing a",
        "; hex digit needs no translating and why the game's own words in end.s",
        "; carry the game's own codes.",
        "",
        "font:",
    ]
    for index, rows in enumerate(characters):
        out.append("\t\t\t; %2d  %s" % (index, glyphs[index]))
        for byte in rows:
            picture = "".join("##" if byte & (0x80 >> bit) else ".."
                              for bit in range(8))
            out.append("\t\t\tDB\t0b{0:08b} ;{1}".format(byte, picture))
    return out


def packed_block(characters, block):
    """A block as font.bin holds it, which is what the atlas carries."""
    first = block["firstIndex"]
    return bytes(byte for rows in characters[first:first + block["count"]]
                 for byte in rows)


def refresh_atlas(path, atlas, blocks, characters):
    """Put the picture's own bytes back in the atlas, if they have moved on.

    The graphics panel reads a block's bytes from here, not from the picture,
    so an edited PNG would otherwise still open as the font it replaced.
    """
    changed = False
    for block in blocks:
        packed = packed_block(characters, block)
        text = base64.b64encode(packed).decode("ascii")
        if block.get("bytes") != text or block.get("length") != len(packed):
            block["bytes"] = text
            block["length"] = len(packed)
            changed = True
    if changed:
        path.write_text(json.dumps(atlas, indent=1) + "\n", encoding="utf-8")
    return changed


def main():
    parser = argparse.ArgumentParser(
        description="Turn the font sheet into the game's font source.")
    parser.add_argument("--sheet", type=Path, default=HERE / "font.png",
                        help="the font sheet PNG (default: font.png)")
    parser.add_argument("--json", type=Path, default=HERE / "font.json",
                        help="the atlas that describes it (default: font.json)")
    parser.add_argument("--out-dir", type=Path, default=HERE,
                        help="where font.s goes (default: beside this script)")
    args = parser.parse_args()

    for needed in (args.sheet, args.json):
        if not needed.is_file():
            raise SystemExit(f"{needed} is missing -- run font_sheet.py to make "
                             "the sheet from font.bin")

    atlas, blocks, facts = read_atlas(args.json)
    characters = read_sheet(args.sheet, atlas, blocks, facts)
    if len(characters) != len(facts["glyphs"]):
        raise SystemExit(f"the sheet holds {len(characters)} characters, but the "
                         f"atlas names {len(facts['glyphs'])}")

    (args.out_dir / "font.s").write_text("\n".join(emit(characters, facts)) + "\n",
                                         encoding="utf-8")
    print(f"Wrote font.s ({len(characters)} characters, "
          f"{len(characters) * facts['cell']} bytes)")

    if refresh_atlas(args.json, atlas, blocks, characters):
        print(f"Brought {args.json.name}'s copy of the bytes back in step with "
              f"{args.sheet.name}")


if __name__ == "__main__":
    main()
