					DEVICE ZXSPECTRUM48

; Pentagram on the Filmation engine in ../engine, laid out the way
; ../knightlore/knightlore.s lays out Knight Lore. The engine is shared
; unchanged; what differs is this file, the game code, and the data.
;
; NOT YET COMPLETE. The engine names a list of things a game has to supply
; -- mover_tbl, walker_player, the BEHAVIOUR_ and CHARACTER_ equates, a
; character_steer, a redraw_hook -- and Pentagram has none of them yet. The
; includes for those are listed below and commented out, each with what still
; has to exist. What this file IS good for now is the memory map: the regions,
; the alignments the engine insists on, and the ASSERT/DISPLAY pairs that
; report what is left. Uncomment as the files arrive.
;
; ---------------------------------------------------------------------------
; How Pentagram differs from Knight Lore, measured rather than assumed:
;
;   sprites        87, widest 40 pixels (5 bytes), tallest 55 rows
;                  Knight Lore: 103, widest 5 bytes, tallest 64 rows
;   graphics       172, against 256 -- but sprite_table still fills 512 bytes,
;                  because the engine reaches it by doubling a pre-halved base
;                  and needs the alignment either way
;   rooms          139, against 128
;   fullest room   43 objects (room 87), against 36 -- so the pool is 1,376
;                  bytes where Knight Lore's is 1,152 plus its collectables
;   room data      4,055 bytes, against 2,986 -- Pentagram keeps a destination
;                  room number against every scenery entry, which is what buys
;                  it a map that is not a grid
;   font           43 characters, 344 bytes, against 40 and 320
;   sprite data    13,798 bytes, against 15,572
;
; So Pentagram is about 1,100 bytes heavier in room data and 224 in the pool,
; and about 1,800 lighter in sprites. Close to a wash overall, but distributed
; differently -- the contended region below $8000 is the one under pressure,
; not the code region above it. Knight Lore finished with 3, 2, 4 and 6 bytes
; free in its four regions; this one starts from a blank sheet and should not
; be allowed to end up there.

					ORG	0x8000

; The view buffer is a window, not a screen: everything that intersects the
; area a moved object disturbed is composited here, then copied out in one go.
; Its shape is the hard limit on how big a single object can be, and both
; dimensions have to clear the whole sprite set:
;
;   widest sprite   5 bytes, and a sprite that is not byte-aligned spans one
;                   column more than its own width -- so 6 columns
;   tallest sprite  55 rows
;
; Pentagram's tallest sprite is 55 where Knight Lore's is 64, so 8 x 64 is
; more than it needs -- 8 x 56 would cover it. It is kept at 64 anyway: the
; row address folds into D with a single `rl d`, which wants the stride a
; power of two and the base even, and 8 x 64 = 512 gives both. Dropping to 56
; rows saves 64 bytes and costs the alignment, which is not a good trade.
VIEW_BUF_WIDTH		EQU		8
VIEW_BUF_ROWS		EQU		512 / VIEW_BUF_WIDTH

; The stack, in UNCONTENDED memory, growing down from the top: SP = 0, so the
; first push lands at $FFFE. STACK_RESERVE is kept clear below it.
;
; Knight Lore's reserve is 48, measured by filling the bytes below the stack
; with a pattern, playing through rooms with everything moving, and counting
; what stayed untouched -- 34 used, 14 spare. Pentagram's call chains are not
; Knight Lore's, so this figure is inherited, not measured, and wants
; re-measuring the same way once the game runs. Until then it is a guess with
; Knight Lore's margin on it.
STACK_TOP			EQU		0x0000
STACK_RESERVE		EQU		48		; inherited from Knight Lore; NOT measured here

; ---------------------------------------------------------------------------
; The game's data, in contended memory.
;
; Every room, the templates they are built from, and the font. None of it is
; touched except when a room is built, so it costs nothing to leave it where
; the ULA fights the CPU for it -- which is where Pentagram itself kept it.
;
; room_data.s is generated by rooms.py from rooms.json, which rooms.py writes
; from room_data.bin, which pg_extract.py takes out of your own copy of the
; tape. font.s comes from font.png/font.json by way of font_source.py. None of
; them is hand-written.
                    ORG     $6000
                    INCLUDE "room_data.s"
                    INCLUDE "font.s"

; The one buffer every deferred rotation goes through -- see ../engine/shift.s.
shift_shared:       DS      SHIFT_SHARED_SIZE

                    INCLUDE "sound_data.s"
                    INCLUDE "sound_tune.s"
room_data_end:
                    ASSERT  room_data_end <= $7400      ; clear of the view buffer
                    DISPLAY "generated data  $6000..", /H, room_data_end, "   free: ", /D, $7400 - room_data_end

; ---------------------------------------------------------------------------
; The engine and the game, in uncontended memory. Everything that runs every
; turn belongs here, including ../engine/sound.s, whose timing assumes it.
;
; sprite.s, object.s and shift.s reach into each other's code and
; sprite_jump_table is computed from the size of a block inside object_update,
; so those three go into a build together and in this order.
; Sabreman walks in four frames, not the knight's six, and his sprites face the
; other way unmirrored. Both are the engine's generic character settings; see
; ../engine/walker.s. His body's height by facing is Pentagram's own, and is
; player_body_up in player.s.
                    DEFINE  CHARACTER_SHORT_WALK
                    DEFINE  CHARACTER_MIRRORED_ART

                    ORG     $8000

					INCLUDE "../engine/sprite.s"
sprite_start:
					INCLUDE "sprite_data.s"
sprite_end:
					DISPLAY "sprite_data size ", sprite_end - sprite_start
					INCLUDE "../engine/object.s"
					INCLUDE "../engine/depth.s"
					INCLUDE "../engine/shift.s"
					INCLUDE "../engine/walker.s"
					INCLUDE "sabreman.s"
					INCLUDE "movers.s"
					INCLUDE "../engine/mover.s"		; movers.s falls into it
					INCLUDE "../engine/sound.s"
					INCLUDE "sound_long.s"
					INCLUDE "../engine/screen.s"
					INCLUDE "panel.s"
					INCLUDE "gameover.s"
					INCLUDE "quest.s"
					INCLUDE "quest_data.s"
					INCLUDE "input.s"
					INCLUDE "main.s"
					INCLUDE "../engine/turn.s"
					INCLUDE "player.s"
					INCLUDE "flyers.s"
                                                     ; here, not Knight Lore's grid arithmetic
					INCLUDE "../engine/redraw.s"
					INCLUDE "overlay.s"              ; redraw_view falls into it -- the game
                                                     ; must ASSERT $ == redraw_view_end
					INCLUDE "../engine/vid_buff.s"

; The pixel adjustments. These belong with the rest of the game's data at
; $6000, and Knight Lore keeps them there -- but Pentagram's room data is a
; thousand bytes heavier than Knight Lore's, because it carries a destination
; room against every scenery entry, and that region overflowed by 162 bytes
; with these in it. The code region has thousands spare, so they come up here.
; sprite_adj_index is page-aligned either way, which is all the engine asks.
					INCLUDE "menu_run.s"             ; cold, in the pad before the index
					INCLUDE "sprite_adj_gen.s"
					INCLUDE "menu_text.s"
					INCLUDE "sound_title.s"

image_end:
                    ASSERT  $ <= $10000 - STACK_RESERVE
                    DISPLAY "code and data   $8000..", /H, image_end, "   free below the stack: ", /D, $10000 - STACK_RESERVE - image_end

; ---------------------------------------------------------------------------
; Building a room, down where the ROM keeps its system variables.
;
; $5B00 to $5FFF is the printer buffer and the system variables, and none of it
; is wanted: interrupts are off for good, nothing here calls the ROM, and the
; stack is up at STACK_TOP. It is contended, so what goes here has to be code
; that does not run every turn -- and building a room is the definition of
; that.
;
; Pentagram's builder differs from Knight Lore's in one place that matters:
; leaving a room. Knight Lore computes the next room arithmetically on a 16x16
; grid. Pentagram cannot -- its map has forty distinct deltas and thirteen
; different ones for a single doorway direction -- so the destination is read
; from the room record instead. Its twelve doorway templates are scenery
; indices 0-7 and 24-27, with the side in `index & 3` as 0=N, 1=E, 2=S, 3=W,
; the same convention Knight Lore uses. The destination byte is the authority,
; not the template: one south doorway is an exit in twenty-eight rooms and
; blocked in one.
                    ORG     $5B00
                    INCLUDE "room_build.s"
                    INCLUDE "../engine/room.s"
                    INCLUDE "quest_ram.s"
                    INCLUDE "busy.s"
                    INCLUDE "sound_fx.s"
                    INCLUDE "menu.s"
room_code_end:
                    ASSERT  room_code_end <= $6000
                    DISPLAY "room builder     $5B00..", /H, room_code_end, "   free: ", /D, $6000 - room_code_end

; ---------------------------------------------------------------------------
; Reservations, in the gap between the data and the code.
;
; The view buffer is aligned to its own size, so a row start is a multiple of
; the stride in both pages and `high view_buffer` is even -- the row address
; folds its top bit into D with a single `rl d`, which needs an even base.
                    ORG     $7400
                    ALIGN   512
view_buffer:        DS      VIEW_BUF_ROWS * VIEW_BUF_WIDTH

; The object pool. A room owns all of it: the builder refills it from the
; start, so nothing survives a room change. 43 is the fullest room in the game
; -- room 87 -- and rooms_source.py emits it as ROOM_MAX_OBJECTS, counted by
; expanding every scenery chain and every object entry's repeat count. It is
; read from there rather than kept here, so it cannot drift from the data.
; One more than the fullest room needs, so that even there something can be
; put down or come out of the well -- the original keeps 48 slots for a room
; and what persists in it, and the fullest room has 43.
ROOM_SLOTS          EQU     ROOM_MAX_OBJECTS + 1 ; what room_add may fill
POOL_SLOTS          EQU     ROOM_SLOTS + EXTRA_SLOTS ; and what falls or is fired
                    ALIGN   32
room_objects:
                REPT    POOL_SLOTS
                    ALIGN   32
                    object_record   0,      0,              0, 0, 0
                ENDR
                    ; object_record lays down only the first twenty bytes of a
                    ; record; the ALIGN in front of the next one gives it the
                    ; rest. The last one has no next one, so it needs this or
                    ; its final twelve bytes are whatever follows the pool.
                    ALIGN   32
                    ASSERT  $ == room_objects + POOL_SLOTS * ROOM_STRIDE

                    ALIGN   256
; Every byte with its bits the other way round, for mirroring a sprite.
bit_reverse_table:
                    bit_reverse_bytes

; sprite_table is read as `ld h,(high sprite_table)/2 / ld l,a / add hl,hl`, so
; its page has to be even: a 512 boundary, not merely a 256 one. Pentagram
; names 172 graphics rather than 256, but the table is still 512 bytes -- the
; entries past the game's own simply hold zero.
                    ALIGN   512
                    INCLUDE "sprite_table.s"

pool_end:
                    ASSERT  $ <= $8000      ; still inside the gap
                    DISPLAY "buffer and pool $7400..", /H, pool_end, "   free: ", /D, $8000 - pool_end

; All of RAM, for build.py to wrap as output/pentagram.z80 with PC at start.
                    SAVEBIN "output/pentagram.bin", $4000, $C000
