"""quest.bin -> quest_data.s: the tables the quest runs on.

pg_extract.py lifts three of the original's tables out of the tape into
quest.bin, back to back:

  $D312  18 records of 16 bytes -- everything that persists from room to
         room. The game copies them to $D432 at the start of every game and
         works on the copy: the four quest items (112-115), the five
         collectables (144-148, all in room 97 until $D16F deals them out),
         the eight pieces of the pentagram in room 82 (128-135), and an empty
         record the well's bucket takes when it comes out.
  $D1A5  20 spots of room, U, V, Z. $D16F deals the five collectables into
         five in a row of them, starting at a random one of the first sixteen.
  $D562  where each collectable settles in room 82, by the bottom three bits
         of its graphic -- five of them.

This writes them in the remake's shape. A record is eight bytes -- graphic, U,
V, Z, size U, size V, size Z, room -- because the original's flags are not
needed: the remake knows what a thing does by its graphic, as the original's
dispatch at $AE2F does.

quest.bin and quest_data.s are both the game's own data and are never
committed; build.py runs this when quest_data.s is missing or older.

    python quest_source.py
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
IN = HERE / "quest.bin"
OUT = HERE / "quest_data.s"

RECORDS = 18
RECORD_LEN = 16
SPOTS = 20
TARGETS = 5
TAB = chr(9)


def main():
    if not IN.is_file():
        sys.exit("%s is missing -- run pg_extract.py against your own copy of "
                 "Pentagram to produce it" % IN.name)
    data = IN.read_bytes()
    want = RECORDS * RECORD_LEN + SPOTS * 4 + TARGETS * 2
    if len(data) != want:
        sys.exit("%s is %d bytes, not %d -- run pg_extract.py again"
                 % (IN.name, len(data), want))
    records = [data[i * RECORD_LEN:(i + 1) * RECORD_LEN] for i in range(RECORDS)]
    spots = data[RECORDS * RECORD_LEN:RECORDS * RECORD_LEN + SPOTS * 4]
    targets = data[RECORDS * RECORD_LEN + SPOTS * 4:]

    L = ["; Generated by quest_source.py from quest.bin -- do not edit.",
         ";",
         "; The things that persist between rooms, as a new game starts: graphic,",
         "; U, V, Z, size U, size V, size Z, room. See quest.s.",
         "quest_start:"]
    for n, r in enumerate(records):
        gfx, u, v, z, su, sv, sz, _flags, room = r[:9]
        L.append(TAB * 5 + "DB" + TAB + TAB
                 + "%3d, %3d, %3d, %3d, %2d, %2d, %2d, %3d" % (gfx, u, v, z, su, sv, sz, room)
                 + TAB + "; %d" % n)
    L += ["QUEST_RECORDS" + TAB + TAB + "EQU" + TAB + TAB + "%d" % RECORDS,
          "",
          "; Where the collectables can start: room, U, V, Z. Five in a row are",
          "; dealt, from a random one of the first sixteen.",
          "quest_spots:"]
    for i in range(SPOTS):
        L.append(TAB * 5 + "DB" + TAB + TAB + "%3d, %3d, %3d, %3d" % tuple(spots[i * 4:i * 4 + 4]))
    L += ["QUEST_SPOTS" + TAB + TAB + "EQU" + TAB + TAB + "%d" % SPOTS,
          "",
          "; Where each collectable settles in room 82: U, V, by graphic & 7.",
          "quest_targets:"]
    for i in range(TARGETS):
        L.append(TAB * 5 + "DB" + TAB + TAB + "%3d, %3d" % tuple(targets[i * 2:i * 2 + 2]))
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("Wrote %s" % OUT.name)


if __name__ == "__main__":
    main()
