"""sound.bin -> sound_data.s: the notes and tunes the sounds play.

pg_extract.py lifts three of the original's tables out of the tape into
sound.bin, back to back:

  $D615  ten notes, a half-period each, that $D5F2 plays one a turn, counting
         down: the four after $D615 when he comes into a room ($B07E starts
         it), and the five after $D619 when he reaches for something ($C007).
  $D718  $D6C0's notes, three bytes each: the half-period as a count of DJNZs
         and then of 256 more, and the cycles in the shortest note. Up to
         where the first tune begins, which is 61 of them; note 0 is a rest
         and has no entry to speak of.
  $D7CF  six tunes, each a byte a note -- the note in bits 0-5, its length
         less one in bits 6-7 -- and $FF at the end: the title; one at $D824
         that nothing in the game loads, perhaps the loader's; the start of a
         game; the water over a quest item; the game over; and the win.

This writes the jingles whole, the note table only as far as the highest note
the tunes played here reach, and the five tunes the game plays -- not the one
nothing loads. The title's goes to sound_title.s on its own, because the build
has room for it only somewhere else.

sound.bin and sound_data.s are both the game's own data and are never
committed; build.py runs this when sound_data.s is missing or older.

    python sound_source.py
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
IN = HERE / "sound.bin"
OUT = HERE / "sound_data.s"
OUT_TITLE = HERE / "sound_title.s"

JINGLES = 10
NOTES = 61                      # $D718 up to $D7CF, three bytes each
TUNES = ("title", "unused", "start", "water", "over", "win")
PLAYED = ("start", "water", "over", "win")
END = 0xFF


def main():
    if not IN.is_file():
        sys.exit("%s is missing -- run pg_extract.py against your own copy of "
                 "Pentagram to produce it" % IN.name)
    data = IN.read_bytes()
    jingles = data[:JINGLES]
    notes = data[JINGLES:JINGLES + NOTES * 3]
    rest = data[JINGLES + NOTES * 3:]

    tunes = {}
    for name in TUNES:
        end = rest.index(END)
        tunes[name] = rest[:end]
        rest = rest[end + 1:]
    if rest:
        sys.exit("%s has %d bytes past the last tune -- run pg_extract.py "
                 "again" % (IN.name, len(rest)))

    highest = max(b & 0x3F for name in PLAYED + ("title",) for b in tunes[name])
    if highest >= NOTES:
        sys.exit("a tune plays note %d, past the table's %d" % (highest, NOTES))

    L = ["; Generated by sound_source.py from sound.bin -- do not edit.",
         ";",
         "; The notes $D5F2 plays a turn at a time: a jingle counts down from",
         "; its length, and plays the note that many past its start. See",
         "; sound_fx.s.",
         "sound_jingles:\tDB\t" + ", ".join("$%02X" % b for b in jingles),
         "",
         "; $D6C0's notes from the first: DJNZs, then 256s plus one, then the",
         "; cycles in the shortest. Note 0 is a rest.",
         "sound_notes:"]
    for n in range(1, highest + 1):
        b, c, cycles = notes[n * 3:n * 3 + 3]
        L.append("\t\t\tDB\t$%02X, $%02X, %d\t; %d" % (b, c, cycles, n))
    for name in PLAYED:
        L.append("")
        L.append("sound_tune_%s_data:" % name)
        t = tunes[name]
        for i in range(0, len(t), 12):
            L.append("\t\t\tDB\t" + ", ".join("$%02X" % b for b in t[i:i + 12]))
        L.append("\t\t\tDB\t$%02X" % END)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")

    T = ["; Generated by sound_source.py from sound.bin -- do not edit.",
         ";",
         "; The title's tune, which a key cuts short -- $D69C. See sound_tune.s.",
         "sound_tune_title:\tld\tde,sound_tune_title_data",
         "\t\t\tld\ta,1",
         "\t\t\tjp\tsound_tune_keys",
         "sound_tune_title_data:"]
    t = tunes["title"]
    for i in range(0, len(t), 12):
        T.append("\t\t\tDB\t" + ", ".join("$%02X" % b for b in t[i:i + 12]))
    T.append("\t\t\tDB\t$%02X" % END)
    OUT_TITLE.write_text("\n".join(T) + "\n", encoding="utf-8")
    print("%s: %d notes, tunes %s" % (OUT.name, highest,
          ", ".join("%s %d" % (n, len(tunes[n])) for n in PLAYED)))


if __name__ == "__main__":
    main()
