; Generated by adj.py from a running Pentagram -- do not edit.
;
; The pixel nudge that lines a sprite's artwork up with its logical
; position. Pentagram picks these inside its per-graphic update
; routines rather than reading a table, so these are the values its
; own code produced, read back out of live object records.
;
; 15 distinct pairs cover all 172 graphics both ways round, and 4
; want a different one mirrored.

; The pairs, x then y. Entry 0 is no nudge at all, so a graphic
; nothing knows about indexes to it harmlessly.
sprite_adj_pairs:
					DB		   0,   0		; 0
					DB		  -5,  -5		; 2
					DB		 -17,  -6		; 4
					DB		  -7,  -5		; 6
					DB		  -7,  -4		; 8
					DB		  -8,  -5		; 10
					DB		 -16,  -5		; 12
					DB		 -16,  -8		; 14
					DB		  -8,  -2		; 16
					DB		 -12,  -6		; 18
					DB		 -12,  -8		; 20
					DB		  -8,  -4		; 22
					DB		  -8,   0		; 24
					DB		 -12,  -4		; 26
					DB		 -16, -12		; 28

; Graphics wanting a different nudge mirrored: the graphic, then
; its mirrored index. A zero graphic ends the list.
sprite_adj_mirror:
					DB		   6,   4
					DB		   7,   8
					DB		   8,  12
					DB		   9,   8
					DB		   0,   0

; One index a graphic, doubled so it reaches the pair directly.
; Bit 7 says look in the mirror list when the sprite is flipped.
sprite_adj_index:
					DB		$00, $00, $00, $00, $00, $00, $82, $86	; $00
					DB		$8A, $8C, $0E, $0E, $10, $10, $10, $10	; $08
					DB		$0E, $0E, $00, $00, $00, $00, $00, $0E	; $10
					DB		$00, $00, $00, $00, $0E, $00, $0E, $00	; $18
					DB		$12, $12, $12, $12, $12, $12, $12, $12	; $20
					DB		$14, $14, $14, $14, $14, $14, $14, $14	; $28
					DB		$12, $12, $12, $12, $10, $16, $16, $16	; $30
					DB		$16, $18, $00, $00, $00, $00, $00, $0E	; $38
					DB		$14, $00, $1A, $1A, $00, $1A, $1A, $1A	; $40
					DB		$0E, $1C, $0E, $0E, $0E, $00, $0E, $0E	; $48
					DB		$0E, $0E, $0E, $00, $0E, $00, $0E, $0E	; $50
					DB		$0E, $0E, $00, $1C, $0E, $0E, $00, $00	; $58
					DB		$00, $00, $00, $00, $00, $00, $00, $00	; $60
					DB		$00, $00, $00, $00, $00, $00, $00, $00	; $68
					DB		$00, $00, $00, $00, $00, $00, $00, $00	; $70
					DB		$0E, $00, $00, $00, $00, $00, $00, $00	; $78
					DB		$00, $00, $00, $00, $00, $00, $00, $00	; $80
					DB		$0E, $00, $00, $00, $0E, $00, $0E, $0E	; $88
					DB		$00, $0E, $0E, $0E, $00, $12, $12, $12	; $90
					DB		$00, $00, $00, $00, $00, $00, $00, $00	; $98
					DB		$12, $12, $12, $12, $12, $12, $12, $12	; $A0
					DB		$0E, $0E, $0E, $0E	; $A8
