"""specials.json back into assembler: the collectable tables.

    python specials_source.py

kl_extract.py pulls the two tables out of the game and writes them as named
data; this is the other half of that round trip, and what it writes is what the
assembler sees. build.py runs it whenever specials.json or this script has
moved on.

knightlore.s INCLUDEs what comes out, where it used to INCBIN specials.bin
twice at counted offsets. The bytes are the same either way. The file opens all
four labels rather than only the two that hold data, because the two that do
not -- the working copy and the dealt graphics -- have to sit between and after
them in exactly that order: special_init copies special_where_start over
special_where in one LDIR, so the pair must be the same shape, and nothing may
come between special_where_start and the end of its 128 bytes.
"""

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

ROWS = 32                       # SPECIAL_ROWS in the game
WANTED = 14                     # SPECIAL_WANTED

# The generated files are tab-indented the way the hand-written ones are: five
# tabs to the mnemonic column, two more to the operand.
LEAD = "\t" * 5
GAP = "\t" * 2


def read(path):
    """specials.json -> the thirty-two positions and the wizard's list."""
    said = json.loads(path.read_text(encoding="utf-8"))

    places = said.get("collectables") or []
    if len(places) != ROWS:
        raise SystemExit("%s has %d collectables, not %d -- the game's table is "
                         "a fixed %d rows and special_init copies it in one LDIR"
                         % (path.name, len(places), ROWS, ROWS))

    wanted = said.get("wanted") or []
    if len(wanted) != WANTED:
        raise SystemExit("%s wants %d objects, not %d -- SPECIAL_WANTED in the "
                         "game is %d, and the two have to agree or the wizard "
                         "reads off the end of his own list"
                         % (path.name, len(wanted), WANTED, WANTED))
    for kind in wanted:
        if not 0 <= kind <= 7:
            raise SystemExit("%s asks for kind %d; a kind is 0 to 7, because "
                             "special.s matches it against a graphic AND 7"
                             % (path.name, kind))

    return places, wanted


def emit(places, wanted):
    """...and the assembler text, in the order the game reads it.

    A row is U, V, Z and then the room -- special_fill walks the first three
    off HL in that order, and room_build reads the fourth on its own to decide
    whether a collectable belongs in the room being built.
    """
    out = [
        "; Generated by specials_source.py from specials.json -- do not edit.",
        ";",
        "; The thirty-two collectables: where each one lies when a game starts,",
        "; and the fourteen the wizard asks for. Which KIND each row is dealt is",
        "; not here -- special_init deals those from a random number every game.",
        "",
        "special_where_start:",
    ]
    for row, place in enumerate(places):
        out.append("%sDB%s%4d,%4d,%4d,%4d%s; %2d  room $%02X"
                   % (LEAD, GAP, place["u"], place["v"], place["z"],
                      place["room"], GAP, row, place["room"]))

    out += [
        "",
        "; Where they are now: special_init copies the table above over this one",
        "; at the start of every game, so the two must stay the same shape.",
        "special_where:%sDS%s%d * 4" % ("\t" * 3, GAP, ROWS),
        "",
        "special_wanted:",
        "%sDB%s%s" % (LEAD, GAP, ", ".join("%d" % k for k in wanted)),
        "",
        "; The kind each row was dealt, filled in by special_init.",
        "special_gfx:%sDS%s%d" % ("\t" * 4, GAP, ROWS),
        "",
    ]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", type=Path, default=HERE / "specials.json")
    ap.add_argument("--out", type=Path, default=HERE / "specials_gen.s")
    args = ap.parse_args()

    places, wanted = read(args.json)
    args.out.write_text(emit(places, wanted), encoding="utf-8")
    print("Wrote %s -- %d collectables, %d wanted"
          % (args.out.name, len(places), len(wanted)))


if __name__ == "__main__":
    main()
