					DEVICE ZXSPECTRUM48


					ORG	0x8000

; The view buffer is a window, not a screen: everything that intersects the
; area a moved object disturbed is composited here, then copied out in one
; go. Its shape is therefore the hard limit on how big a single object can
; be, and both dimensions have to clear the whole sprite set:
;
;   widest sprite   5 bytes, and a sprite that is not byte-aligned spans one
;                   column more than its own width -- so 6 columns
;   tallest sprite  64 rows (the castle door arch; the forest one is 52)
;
; 8 x 64 = 512 bytes covers both with the stride a power of two, which is
; what makes the row address a shift rather than a multiply. Six would be
; tight enough to work and no cheaper: 6 x 64 is 384, still over a page, so
; the second page has to be handled either way, and the multiply-by-6 costs
; more than the multiply-by-8 saves. The padding from the sprite's width out
; to the stride is what the extra two columns actually cost -- see the row
; advance in sprite_blit.
VIEW_BUF_WIDTH		EQU		8

; The buffer spans two pages, so the blit cannot address it with `ld d,high
; view_buffer` plus `inc e` throughout. Rows are 8 bytes on an 8-byte
; boundary, so no row straddles the page break and only the increments that
; can land on a row boundary have to carry into D -- which is the last one
; of each row, plus the row advance itself. Everything inside a row stays
; `inc e`. Knight Lore has no limit of this kind at all, because its buffer
; IS the screen; ours is a small window, and this is what that costs.
VIEW_BUF_ROWS		EQU		512 / VIEW_BUF_WIDTH

; The stack, in UNCONTENDED memory. sjasmplus's SAVESNA leaves SP at 0x5D56,
; which is inside the ULA-contended 0x4000-0x7FFF window, so on real hardware
; every call and return there pays a contention delay -- a few hundred
; T-states a frame for nothing. Everything else this engine touches already
; lives above 0x8000: the sprite data, the rotate table, the view buffer, the
; object records and the code. The stack was the one thing left behind.
;
; It grows down from here into the space above the program, which ends around
; 0xE080 -- getting on for 8K of headroom, against the handful of frames deep
; this ever nests.
STACK_TOP			EQU		0xFF00

; ---------------------------------------------------------------------------
; The castle, in contended memory.
;
; Every room in Knight Lore, the templates they are built from, and the pixel
; adjustments its own code would have computed. None of it is touched except
; when a room is built, so it costs nothing to leave it where the ULA fights
; the CPU for it -- which is also where the game itself kept it.
;
; room_data.s is generated by rooms.py from room_data.bin; sprite_adj.s by
; adj.py from a running game. Neither is hand-written.
                    ORG     $6000
                    INCLUDE "room_data.s"
                    INCLUDE "sprite_adj.s"
room_data_end:
                    DISPLAY "room data ends at ", room_data_end

                    ORG     $8000

					INCLUDE "sprite.s"
					INCLUDE "object.s"
					INCLUDE "shift.s"
					INCLUDE "character.s"
                    INCLUDE "room.s"

					STRUCT SPRITE
WIDTH:				DS		1
HEIGHT:				DS		1
					ENDS
					
	

; The view buffer and the object pool used to sit here, at the top of the
; image. They are reserved at the foot of this file instead, in the gap between
; the room data and the code -- see there for why.

; The stride between records, which the pool's ALIGN fixes.
ROOM_STRIDE         EQU     32


; Interrupts stay off for good. Every part of the drawing path repurposes
; SP as a data pointer -- object_update walks sprite data with it,
; objects_draw_all reads object records with it, the blitters read their
; sprites with it, and redraw_view clears the view buffer by pushing
; through it. An interrupt taken during any of those would push a return
; address into whatever SP was aimed at.
start:              di
                    ld      sp,STACK_TOP        ; off the contended stack, first thing

.enter:             ld      a,(room_number)
                    ld      (room_shown),a
                    call    room_build
                    call    mover_add
                    call    player_add

                    ; Poke room_number from the debugger and the castle turns
                    ; over; otherwise the mover just keeps walking.
.loop:              ld      a,(room_number)
                    ld      hl,room_shown
                    cp      (hl)
                    jr      nz,.enter

                    ; Wait for the frame. Interrupts are off everywhere else --
                    ; every part of the drawing path repurposes SP, so one taken
                    ; mid-blit would push a return address into a sprite -- so
                    ; they are let in here and nowhere else, for exactly one.
                    ;
                    ; IM 1 sends it to the ROM at $0038, which scans the keyboard
                    ; through IY, so IY has to point at the system variables
                    ; while that runs. Nothing else in the engine leaves it
                    ; there: objects_draw_all uses IY as its list pointer, and
                    ; sets it itself.
                    ld      iy,$5C3A
                    ei
                    halt
                    di

                    call    mover_step
                    call    player_step
                    jr      .loop


; Which room to build. $88 is the cauldron room; $B3 is where the game begins.
room_number:        DB      $88
room_shown:         DB      $88


; --- the mover --------------------------------------------------------------
;
; One object walking a square around the room, which is the thing a static
; scene cannot show: the depth sort, as it passes in front of some scenery and
; behind the rest, and the redraw, which repaints the union of where it was and
; where it is rather than the screen.
;
; It is not part of the room. room_objects is sized to the fullest room in the
; castle, so there is no spare slot, and room_build refills it from the start
; anyway -- nothing in it survives a room change. This record joins the sorted
; list once the room is built, and rejoins after the next one.
;
; Its rotation buffer comes from the room's arena like everyone else's, taken
; lazily the first time the path puts it off the byte grid. shift_reset hands
; the whole arena back on a room change, so BUF has to be cleared again with
; it, which mover_add does.
                    ALIGN   32
mover:              object_record   OBJ_MOVABLE, 0, 7, 7, 12
                    ; The macro lays down 23 bytes and a record is ROOM_STRIDE
                    ; wide. In the pool the next record's own ALIGN covers the
                    ; difference; a record on its own has to say so, or what
                    ; follows lands inside it -- mover_leg sat on ADJ_X and the
                    ; path table on ADJ_Y and GFX, so room_adjust rewrote the
                    ; route every frame.
                    ALIGN   ROOM_STRIDE

MOVER_GFX           EQU     178         ; Knight Lore's ball: 3 x 19
MOVER_Z             EQU     128         ; the floor
MOVER_LO            EQU     84          ; the square it walks, chosen to weave
MOVER_HI            EQU     172         ; through the ring of blocks

; Which side of the square it is on, and what that adds to U and V.
mover_leg:          DB      0
mover_legs:         DB       1,  0
                    DB       0,  1
                    DB      -1,  0
                    DB       0, -1


; Put the mover into the room that has just been built.
mover_add:          ld      ix,mover
                    ld      (ix+OBJ.GFX),MOVER_GFX
                    ld      (ix+OBJ.U),MOVER_LO
                    ld      (ix+OBJ.V),MOVER_LO
                    ld      (ix+OBJ.Z),MOVER_Z
                    ld      (ix+OBJ.FLAGS),OBJ_MOVABLE
                    ld      (ix+OBJ.BUF_L),0        ; the old arena went with the
                    ld      (ix+OBJ.BUF_H),0        ; old room
                    xor     a
                    ld      (mover_leg),a
                    call    room_adjust             ; the pixel nudge for this graphic
                    ld      a,MOVER_GFX
                    call    object_place
                    jp      depth_insert


; --- the player -------------------------------------------------------------
;
; A character like any other -- see character.s. The knight's legs are the
; block at 16 and his body the one at 32; he starts facing away from the
; viewer and up the screen.
PLAYER_LEGS_GFX     EQU     16
PLAYER_BODY_GFX     EQU     32
PLAYER_U            EQU     128
PLAYER_V            EQU     104         ; clear of the cauldron at 128,128
PLAYER_FACING       EQU     0           ; -U, up and left

player:             character_record PLAYER_LEGS_GFX, PLAYER_BODY_GFX, PLAYER_FACING


; Put the player in the room that has just been built.
player_add:         ld      ix,player
                    ld      b,PLAYER_U
                    ld      c,PLAYER_V
                    jp      character_add


; Read the keys and walk the player.
;
; The four isometric directions are the two floor axes both ways, so the keys
; pair up as a diamond. Which facing each of them is comes from
; character_steps, and the numbers here are indexes into it.
KEY_UPLEFT          EQU     $FBFE       ; Q, bit 0
KEY_DOWNRIGHT       EQU     $FDFE       ; A, bit 0
KEY_RIGHT           EQU     $DFFE       ; P bit 0, O bit 1

player_step:        ld      bc,KEY_UPLEFT
                    in      a,(c)
                    rra                         ; a key reads 0 while it is held
                    jr      nc,.up_left
                    ld      bc,KEY_DOWNRIGHT
                    in      a,(c)
                    rra
                    jr      nc,.down_right
                    ld      bc,KEY_RIGHT
                    in      a,(c)
                    rra
                    jr      nc,.up_right
                    rra
                    jr      nc,.down_left
                    ret                         ; nothing held: nothing moved,
                    ; and so nothing to repaint

.up_left:           ld      a,0
                    jr      .walk
.up_right:          ld      a,1
                    jr      .walk
.down_left:         ld      a,2
                    jr      .walk
.down_right:        ld      a,3
.walk:              ld      ix,player
                    jp      character_walk


; One unit along the square, then repaint only what that disturbed.
mover_step:         ld      ix,mover
                    call    extent_save             ; where it was, for the union

                    ld      a,(mover_leg)
                    add     a,a
                    ld      e,a
                    ld      d,0
                    ld      hl,mover_legs
                    add     hl,de
                    ld      a,(ix+OBJ.U)
                    add     a,(hl)
                    ld      (ix+OBJ.U),a
                    inc     hl
                    ld      a,(ix+OBJ.V)
                    add     a,(hl)
                    ld      (ix+OBJ.V),a

                    ; A leg ends when the coordinate IT moves reaches the far
                    ; side. Testing both would turn at once in the corner it
                    ; starts in, where U and V are equal.
                    ld      a,(mover_leg)
                    and     1
                    ld      a,(ix+OBJ.U)
                    jr      z,.at_edge
                    ld      a,(ix+OBJ.V)
.at_edge:           cp      MOVER_HI
                    jr      z,.turn
                    cp      MOVER_LO
                    jr      nz,.placed
.turn:              ld      a,(mover_leg)
                    inc     a
                    and     3
                    ld      (mover_leg),a

.placed:            ld      a,MOVER_GFX
                    call    object_place
                    call    depth_relink            ; only re-sorts if it crossed
                    jp      redraw_moved



; --- redrawing ------------------------------------------------------
;
; Nothing draws the whole screen. Each moving object repaints only the
; area it disturbed -- the union of where it was and where it now is --
; and objects_draw_all composites every object that intersects that area,
; so whatever the mover passed over is put back in the same pass.
;
; An area is bounded by what the view buffer holds: VIEW_BUF_WIDTH bytes
; across and VIEW_BUF_ROWS rows down, which is 8 x 64. A one-pixel step
; widens an object's extent by at most one byte -- a byte-aligned sprite
; spans w bytes and a shifted one w+1, and the union of two adjacent
; positions is never more than w+1 -- so with the widest sprite at 5 bytes
; the union peaks at 6 columns, and the tallest at 64 rows. Both fit.

region_rows:		DB		0
region_width:		DB		0

prev_min_y:			DB		0
prev_max_y:			DB		0
prev_min_x:			DB		0
prev_max_x:			DB		0

; ...and where it was in the world, which is what depth_relink gates on.
prev_u:				DB		0
prev_v:				DB		0
prev_z:				DB		0

; redraw_orient used to live here: one pass per region, settling every
; shared graphic before objects_draw_all ran. That is one decision too few
; -- two objects in a region wanting opposite orientations leave whichever
; the pass reached last holding the graphic. sprite_orient asks per object
; instead, at the point of drawing, so this is gone.


; Start a region that several objects will be folded into. The bounds begin
; impossible -- a minimum nothing can be above, a maximum nothing can be below
; -- so the first region_add sets both. Adding nothing at all leaves them that
; way, which redraw_view would read as a region and try to draw, so every
; region_reset must be followed by at least one region_add.
region_reset:       ld      hl,$00FF            ; l = min, h = max
                    ld      (view_y_extent),hl
                    ld      (view_x_extent),hl
                    ret


; Widen the pending region to take in one object's extent.
;   IX -> the object
; Corrupts A and HL. DE, BC and IX are untouched, so a caller can hold a step
; in DE across it.
region_add:         ld      hl,view_y_extent
                    ld      a,(ix+OBJ.MIN_Y)
                    cp      (hl)
                    jr      nc,.max_y           ; keep whichever is smaller
                    ld      (hl),a
.max_y:             inc     hl
                    ld      a,(ix+OBJ.MAX_Y)
                    cp      (hl)
                    jr      c,.min_x            ; keep whichever is larger
                    ld      (hl),a
.min_x:             ld      hl,view_x_extent
                    ld      a,(ix+OBJ.MIN_X)
                    cp      (hl)
                    jr      nc,.max_x
                    ld      (hl),a
.max_x:             inc     hl
                    ld      a,(ix+OBJ.MAX_X)
                    cp      (hl)
                    ret     c
                    ld      (hl),a
                    ret


; Remember an object's extent, before it moves.
;   IX -> the object
extent_save:		ld		a,(ix+OBJ.MIN_Y)
					ld		(prev_min_y),a
					ld		a,(ix+OBJ.MAX_Y)
					ld		(prev_max_y),a
					ld		a,(ix+OBJ.MIN_X)
					ld		(prev_min_x),a
					ld		a,(ix+OBJ.MAX_X)
					ld		(prev_max_x),a
					ld		a,(ix+OBJ.U)
					ld		(prev_u),a
					ld		a,(ix+OBJ.V)
					ld		(prev_v),a
					ld		a,(ix+OBJ.Z)
					ld		(prev_z),a
					ret		


; Repaint the area a just-moved object affected: the union of the extent
; extent_save recorded and the one it has now. The old half erases its
; previous image, the new half draws it where it is.
;   IX -> the object, already moved
redraw_moved:		ld		hl,prev_min_y
					ld		a,(ix+OBJ.MIN_Y)
					cp		(hl)
					jr		c,.min_y		; keep whichever is smaller
					ld		a,(hl)
.min_y:				ld		(view_y_extent),a

					ld		hl,prev_max_y
					ld		a,(ix+OBJ.MAX_Y)
					cp		(hl)
					jr		nc,.max_y		; keep whichever is larger
					ld		a,(hl)
.max_y:				ld		(view_y_extent+1),a

					ld		hl,prev_min_x
					ld		a,(ix+OBJ.MIN_X)
					cp		(hl)
					jr		c,.min_x
					ld		a,(hl)
.min_x:				ld		(view_x_extent),a

					ld		hl,prev_max_x
					ld		a,(ix+OBJ.MAX_X)
					cp		(hl)
					jr		nc,.max_x
					ld		a,(hl)
.max_x:				ld		(view_x_extent+1),a
					jr		redraw_view


; Repaint one object's own area, with no previous position to take in --
; what the opening screen is built from.
;   IX -> the object
redraw_object:		ld		a,(ix+OBJ.MIN_Y)
					ld		(view_y_extent),a
					ld		a,(ix+OBJ.MAX_Y)
					ld		(view_y_extent+1),a
					ld		a,(ix+OBJ.MIN_X)
					ld		(view_x_extent),a
					ld		a,(ix+OBJ.MAX_X)
					ld		(view_x_extent+1),a


; Clear the view buffer, composite everything that intersects the view
; extent into it, and copy the result to its place on the screen. Both
; extents are (min, max) with max exclusive, so max - min is a size.
; No object in the sprite set is taller than VIEW_BUF_ROWS, so there is no
; height case to handle here: the tallest is the 64-row castle arch and the
; buffer holds exactly 64. That is the whole reason the buffer went to
; 8 x 64 -- a region that does not fit has nowhere to go but wrap.
redraw_view:		ld		hl,(view_y_extent)	; l = min, h = max
					ld		a,h
					sub		l
					ret		z		; nothing to draw -- and the copy's
					; DJNZ would take a zero as 256 rows
					cp		VIEW_BUF_ROWS + 1		; taller than the buffer holds cannot
					ret		nc		; be drawn, and must not be tried:
					; the row address has one carry bit and
					; would land outside the buffer
					ld		(region_rows),a

					ld		hl,(view_x_extent)
					ld		a,h
					sub		l
					cp		VIEW_BUF_WIDTH + 1		; a region wider than the buffer has
					jr		c,.width_ok		; no routine to copy it, so clamp
					ld		a,VIEW_BUF_WIDTH		; rather than index off the end of
.width_ok:			ld		(region_width),a		; copy_routines

					; Clear the rows this region uses, by pushing zeroes down through
					; them. PUSH writes two bytes for 11T against LDIR's 21T per byte,
					; so even blanking the lot this way beats LDIR over one region.
					;
					; It no longer blanks the lot, though. At 512 bytes that would be
					; 2816T every region, twice what the old 256-byte buffer cost, and
					; the rows past the region are never read. `push de` is one byte, so
					; where the run is entered decides how much it clears: rows * 8
					; bytes is rows * 4 pushes, so enter that many pushes from the end.
					; A 30-row region now costs 1320T, under what the flat clear cost.
					ld		(.restore_sp+1),sp		; save the real stack
					ld		a,(region_rows)
					ld		l,a
					ld		h,0
					add		hl,hl
					add		hl,hl		; hl = rows * 4, the pushes needed
					ld		e,l
					ld		d,h
					add		hl,hl		; hl = rows * 8, the bytes they cover
					ld		bc,view_buffer
					add		hl,bc
					ld		sp,hl		; PUSH pre-decrements, so this fills downwards
					ld		hl,.clear_end
					or		a
					sbc		hl,de		; ...from here, so exactly de pushes are left
					ld		de,0		; and this is what every one of them writes
					jp		(hl)
				REPT	VIEW_BUF_ROWS * VIEW_BUF_WIDTH / 2
					push	de
				ENDR
.clear_end:
.restore_sp:		ld		sp,0		; operand set just above

					; No orientation pass here any more. It settled the shared
					; graphics once for the whole region, which is one decision
					; too few: objects_draw_all now asks per object, in
					; sprite_orient, at the point it is about to draw one.
					call	objects_draw_all

					; Set the copy routine up for this width. There is one
					; of it: how many bytes of a row to move, and the step from
					; the end of one row of the buffer to the start of the
					; next, both go in as immediates.
					ld		a,(region_width)
					ld		b,a		; B is not wanted until pixelAddress
					ld		a,VIEW_BUF_WIDTH
					sub		b
					ld		(vid_buff_copy.hstride+1),a
					add		a		; the LDI chain is two bytes a column
					ld		(vid_buff_copy.entry+1),a

					; ...and where on the screen it goes
					ld		a,(view_x_extent)		; min x, in bytes
					add		a
					add		a
					add		a		; -> pixels
					ld		c,a
					ld		a,(view_y_extent)
					ld		b,a
					call	pixelAddress		; hl = screen address; bc kept
					ex		de,hl		; de = destination
					ld		hl,view_buffer
					ld		a,(region_rows)
					ld		b,a		; row counter, for the DJNZ. C is the copy
					; routine's own -- it resets it per row so
					; that LDI's countdown can never borrow
					; into B and lose a row.
					call	vid_buff_copy
					ret		






;; Takes a B = Y, C = X 8-pixel coordinate. Real Spectrum screen
;; coords - top left is (0,0).
;;
;; Returns a pointer to corresponding bitmap address in DE.
screen_address: 
					ld 		h,high screen_hi_address_table
					ld 		l,b
					ld		a,(hl)
					inc		h
					ld		h,(hl)
					or		c
					ld		l,a
					ret





; This is the final optimized code. It takes the X coordinate in the C register,
; and the Y coordinate in the B register. The screen address is returned in the HL register pair.
; BC and DE are unchanged, so there is no need for expensive push and pop operations.
pixelAddress:   ld      a, b
                and     %00000111
                ld      h, a    ; h contains Y2-Y0
                ld      a, b
                rra
                scf             ; set bit 14
                rra
                rra
                ld      l, a    ; l contains Y5-Y3
                and     %01011000
                or      h
                ld      h, a    ; h is complete now
                ld      a, c    ; divide X by 8
                rr      l       ; and rotate Y5-Y3 in
                rra
                rr      l
                rra
                rr      l
                rra
                ld      l, a    ; l is complete now
                ret



					INCLUDE "vid_buff.s"



					align	256
screen_hi_address_table:
					REPT	192, y
					DW		high ((y & 0x07) * 256) + ((y & 0x38) * 4) + ((y >> 6) * 2048)
					ENDR
					align	256
screen_lo_address_table:
					REPT	192, y
					DW		low ((y & 0x07) * 256) + ((y & 0x38) * 4) + ((y >> 6) * 2048)
					ENDR


; The stack grows down from STACK_TOP, so the image has to stop below it. This
; is the check that was missing when the player pushed the top past $FF00.
                    ASSERT  $ <= STACK_TOP

; ---------------------------------------------------------------------------
; Two reservations, put where there is room for them.
;
; The room data ends well short of $8000 and nothing uses what is left, so the
; view buffer and the object pool go there rather than on the end of the image.
; They were on the end until the player arrived and pushed it past $FF00, where
; the stack would have pushed straight into the code -- and nothing would have
; said so, because an image that overruns the stack still assembles.
;
; The view buffer is aligned to its own size, so a row start is a multiple of
; the stride in both pages and `high view_buffer` is even -- the row address
; folds its top bit into D with a single `rl d`, which needs an even base.
                    ORG     $7400
                    ALIGN   512
view_buffer:        DS      VIEW_BUF_ROWS * VIEW_BUF_WIDTH

; The object pool. A room owns all of it: room_build refills it from the start,
; so nothing survives a room change. ROOM_MAX_OBJECTS is the fullest room in
; the castle, which rooms.py works out while generating room_data.s.
                    ALIGN   32
room_objects:
                REPT    ROOM_MAX_OBJECTS
                    ALIGN   32
                    object_record   0,      0,              0, 0, 0
                ENDR
                    ASSERT  $ <= $8000      ; still inside the gap

                    SAVESNA "output/filmation.sna", start
