"""Turn room_data.bin into assembly source.

Knight Lore does not store rooms as lists of objects. It stores templates and
expands them: a room is an attribute byte plus a handful of indices, and those
indices name pieces of scenery and groups of objects that are shared across the
whole castle. Room $B3 is four indices -- arch north, arch east, arch south and
the walls for a square room -- and they expand to 19 objects.

This reads the tables the game keeps at $6248-$6FF1 and writes them out as
source we can read and edit, rather than a block of bytes. The layout changes on
the way through: the game bounds each room record with a length and terminates
its scenery list with $FF, and we use two explicit counts instead, because we
are generating the source and a count is cheaper to walk than a terminator.

The names come from the code map in tcdev's disassembly of Knight Lore, as
converted to SkoolKit by Michael R. Cook. Only the factual layer is used -- what
each table is and what its entries are called.

Run via build.py, which regenerates when room_data.bin or this script is newer.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BASE = 0x6248                       # where the block sat in the game

ROOM_SIZE_TBL = 0x6248
LOCATION_TBL = 0x6251
LOCATION_END = 0x6BD1
BLOCK_TYPE_TBL = 0x6BD1
BLOCK_TYPE_COUNT = 29
BG_TYPE_TBL = 0x6CE2
BG_TYPE_COUNT = 24

BG_NAMES = [
    "arch_n", "arch_e", "arch_s", "arch_w",
    "tree_arch_n", "tree_arch_e", "tree_arch_s", "tree_arch_w",
    "gate_0", "gate_1", "gate_2", "gate_3",
    "walls_0", "walls_1", "walls_2",
    "trees_0", "trees_1", "trees_2",
    "wizard", "pot",
    "high_arch_e", "high_arch_s", "high_arch_e_base", "high_arch_s_base",
]

FG_NAMES = [
    "block", "fire", "ball_ud_y", "rock", "gargoyle", "spike", "chest",
    "table", "guard_ew", "ghost", "fire_ns", "block_high", "ball_ud_xy",
    "guard_square", "block_ew", "block_ns", "moveable_block", "spike_high",
    "spike_ball", "spike_ball_falling", "fire_ew", "dropping_block",
    "collapsing_block", "ball_bounce", "ball_ud", "repel_spell",
    "gate_ud_1", "gate_ud_2", "ball_ud_x",
]

TAB = chr(9)
data = None


def b(addr):
    return data[addr - BASE]


def w(addr):
    return b(addr) | (b(addr + 1) << 8)


def block(addr, stride):
    """A template: entries of `stride` bytes, ending in a zero sprite."""
    out = []
    while b(addr):
        out.append(tuple(data[addr - BASE:addr - BASE + stride]))
        addr += stride
    return out


def templates(table, count, stride, names, prefix):
    """Distinct templates in table order, and the label each entry points at.

    Several table entries share a template -- four of the object types are the
    same block seen from different sides -- so a label is emitted once, named
    after the first entry that reaches it.
    """
    label_at = {}
    order = []
    for i in range(count):
        addr = w(table + i * 2)
        if addr not in label_at:
            label_at[addr] = "%s_%s" % (prefix, names[i])
            order.append((addr, label_at[addr], block(addr, stride)))
    return order, [label_at[w(table + i * 2)] for i in range(count)]


def rooms():
    """Every room record: number -> (attribute byte, body bytes)."""
    out = {}
    p = LOCATION_TBL
    while p < LOCATION_END:
        rid, length, attr = b(p), b(p + 1), b(p + 2)
        out[rid] = (attr, bytes(data[p + 3 - BASE:p + 1 + length - BASE]))
        p += length + 1
    return out


def split_body(body):
    """Scenery indices, then the object bytes that follow the $FF."""
    if 0xFF in body:
        cut = body.index(0xFF)
        return list(body[:cut]), list(body[cut + 1:])
    return list(body), []


def pieces_by_index(table, count, stride):
    """Template contents keyed by TABLE index, duplicates included.

    templates() collapses shared templates into one label; this does not,
    because a room names table indices and needs each one to have a length.
    """
    return [block(w(table + i * 2), stride) for i in range(count)]


def count_objects(bg, fg, scenery, objects):
    """How many objects a room expands to -- what the object pool has to hold."""
    n = sum(len(bg[i]) for i in scenery if i < len(bg))
    i = 0
    while i < len(objects):
        typ, count = (objects[i] >> 3) & 0x1F, (objects[i] & 7) + 1
        if typ < len(fg):
            n += count * len(fg[typ])
        i += 1 + count
    return n


def emit(out):
    def line(label, mnemonic, operands, comment=""):
        # a label longer than its column still needs a space after it
        text = (label + " ").ljust(20) if label else " " * 20
        text += mnemonic.ljust(8) + operands
        if comment:
            text = text.ljust(68) + "; " + comment
        out.append(text.rstrip())

    out.append("; Generated by rooms.py from room_data.bin -- do not edit.")
    out.append(";")
    for para in __doc__.strip().split("\n\n")[1:4]:
        for l in para.split("\n"):
            out.append("; " + l if l else ";")
        out.append(";")
    out.append("")
    out.append("")

    line("", ";", "", "")
    out.pop()
    out.append("; --- room shapes -----------------------------------------------------------")
    out.append(";")
    out.append("; Three of them, and the index is the top bits of a room's attribute byte.")
    out.append("; Only the floor changes shape; every room is 128 tall.")
    line("room_size_tbl:", "", "")
    for i, tag in enumerate(("square", "narrow along U", "narrow along V")):
        sx, sy, sz = data[ROOM_SIZE_TBL - BASE + i * 3:ROOM_SIZE_TBL - BASE + i * 3 + 3]
        line("", "DB", "%3d, %3d, %3d" % (sx, sy, sz), "%d - %s" % (i, tag))
    out.append("")
    out.append("")

    # --- scenery -----------------------------------------------------------
    out.append("; --- scenery ---------------------------------------------------------------")
    out.append(";")
    out.append("; A piece is: sprite, U, V, Z, size U, size V, size Z, flags -- which is our")
    out.append("; object record almost field for field. Flags bit 6 mirrors the piece.")
    out.append("; Each template ends in a zero sprite.")
    out.append("")
    bg, bg_refs = templates(BG_TYPE_TBL, BG_TYPE_COUNT, 8, BG_NAMES, "bg")
    for addr, label, pieces in bg:
        line(label + ":", "", "", "%d piece%s" % (len(pieces), "" if len(pieces) == 1 else "s"))
        for p in pieces:
            line("", "DB", "%3d, %3d, %3d, %3d, %3d, %3d, %3d, $%02X" % p,
                 "mirrored" if p[7] & 0x40 else "")
        line("", "DB", "0")
        out.append("")
    line("background_type_tbl:", "", "")
    for i, ref in enumerate(bg_refs):
        line("", "DW", ref, "$%02X" % i)
    out.append("")
    for i, name in enumerate(BG_NAMES):
        line("BG_" + name.upper(), "EQU", "$%02X" % i)
    out.append("")
    out.append("")

    # --- objects -----------------------------------------------------------
    out.append("; --- objects ---------------------------------------------------------------")
    out.append(";")
    out.append("; An entry is: sprite, size U, size V, size Z, flags, offsets. There is no")
    out.append("; position -- that comes from the room, one packed byte per object -- so the")
    out.append("; same template serves every block in the castle. A template with more than")
    out.append("; one entry is an object drawn from several sprites, like a guard.")
    out.append("")
    fg, fg_refs = templates(BLOCK_TYPE_TBL, BLOCK_TYPE_COUNT, 6, FG_NAMES, "fg")
    for addr, label, entries in fg:
        line(label + ":", "", "", "%d sprite%s" % (len(entries), "" if len(entries) == 1 else "s"))
        for e in entries:
            line("", "DB", "%3d, %3d, %3d, %3d, $%02X, $%02X" % e)
        line("", "DB", "0")
        out.append("")
    line("block_type_tbl:", "", "")
    for i, ref in enumerate(fg_refs):
        line("", "DW", ref, "$%02X - %s" % (i, FG_NAMES[i]))
    out.append("")
    for i, name in enumerate(FG_NAMES):
        line("FG_" + name.upper(), "EQU", "$%02X" % i)
    out.append("")
    out.append("")

    # --- rooms -------------------------------------------------------------
    table = rooms()
    out.append("; --- the rooms -------------------------------------------------------------")
    out.append(";")
    out.append("; Each room is:")
    out.append(";")
    out.append(";     attribute and size    colour in bits 0-2, room shape in bits 3 up")
    out.append(";     scenery count")
    out.append(";     object byte count")
    out.append(";     scenery type indices")
    out.append(";     object groups         a type-and-count byte, then that many")
    out.append(";                           packed positions: U cell in bits 0-2,")
    out.append(";                           V cell in bits 3-5, Z level in bits 6-7")
    out.append(";")
    out.append("; The game bounds the record with a length and ends the scenery list with")
    out.append("; $FF; two counts say the same thing and are cheaper to walk.")
    out.append("")
    bg_sizes = pieces_by_index(BG_TYPE_TBL, BG_TYPE_COUNT, 8)
    fg_sizes = pieces_by_index(BLOCK_TYPE_TBL, BLOCK_TYPE_COUNT, 6)
    biggest = 0
    most_objects = 0
    for rid in sorted(table):
        attr, body = table[rid]
        scenery, objects = split_body(body)
        biggest = max(biggest, len(scenery) + len(objects))
        most_objects = max(most_objects,
                           count_objects(bg_sizes, fg_sizes, scenery, objects))
        line("room_%02X:" % rid, "DB", "$%02X, %d, %d"
             % (attr, len(scenery), len(objects)),
             "attr %d, shape %d" % (attr & 7, attr >> 3))
        if scenery:
            line("", "DB", ", ".join("BG_" + BG_NAMES[s].upper() for s in scenery))
        i = 0
        while i < len(objects):
            group = objects[i]
            typ, count = (group >> 3) & 0x1F, (group & 7) + 1
            spots = objects[i + 1:i + 1 + count]
            line("", "DB", "$%02X, %s" % (group, ", ".join("$%02X" % s for s in spots)),
                 "%d x %s" % (count, FG_NAMES[typ] if typ < len(FG_NAMES) else "?"))
            i += 1 + count
        out.append("")
    out.append("")

    out.append("; Indexed by room number; zero where there is no such room.")
    line("room_tbl:", "", "")
    for lo in range(0, 256, 8):
        row = ["room_%02X" % r if r in table else "0" for r in range(lo, lo + 8)]
        line("", "DW", ", ".join(row), "$%02X" % lo)
    out.append("")
    line("ROOM_COUNT", "EQU", "%d" % len(table))
    line("ROOM_MAX_BODY", "EQU", "%d" % biggest, "longest scenery+object list")
    line("ROOM_MAX_OBJECTS", "EQU", "%d" % most_objects,
         "the fullest room, so the object pool")
    out.append("")
    return table


def main():
    global data
    packed = HERE / "room_data.bin"
    if not packed.is_file():
        sys.exit("room_data.bin is missing -- run kl_extract.py against your "
                 "own copy of the game first")
    data = packed.read_bytes()
    out = []
    table = emit(out)
    (HERE / "room_data.s").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("room_data.s: %d rooms" % len(table))


if __name__ == "__main__":
    main()
