; Generated by adj.py from a running Knight Lore -- do not edit.
;
; The pixel nudge that lines a sprite's artwork up with its logical
; position. Knight Lore picks these inside 29 per-graphic update
; routines rather than reading a table, so these are the values its own
; code produced, read back out of live object records.
;
; Indexed by graphic number. Mirrored objects get a different pair, so
; there are two tables and object placement picks by the flip flag.

sprite_adj:         
                    DB         0,   0
                    DB         0,   0
                    DB        -7,  -3        ; graphic 2
                    DB        -9,  -3        ; graphic 3
                    DB         1,  -3        ; graphic 4
                    DB        -9,  -3        ; graphic 5
                    DB       -16,  -8        ; graphic 6
                    DB       -16,  -8        ; graphic 7
                    DB       -12,  -6        ; graphic 8
                    DB       -12,  -6        ; graphic 9
                    DB       -20,  -1        ; graphic 10
                    DB       -12,  -2        ; graphic 11
                    DB        -8,  -4        ; graphic 12
                    DB        -8,  -4        ; graphic 13
                    DB        -8,  -4        ; graphic 14
                    DB        -8,  -4        ; graphic 15
                    DB       -12,  -6        ; graphic 16
                    DB       -12,  -6        ; graphic 17
                    DB       -12,  -6        ; graphic 18
                    DB       -12,  -6        ; graphic 19
                    DB       -12,  -6        ; graphic 20
                    DB       -12,  -6        ; graphic 21
                    DB       -12,  -7        ; graphic 22
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,   3        ; graphic 30
                    DB         0,   0
                    DB       -12,  -8        ; graphic 32
                    DB       -12,  -8        ; graphic 33
                    DB       -12,  -8        ; graphic 34
                    DB       -12,  -8        ; graphic 35
                    DB       -12,  -8        ; graphic 36
                    DB       -12,  -8        ; graphic 37
                    DB       -12,  -8        ; graphic 38
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -16,  -8        ; graphic 54
                    DB       -16,  -8        ; graphic 55
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -16,  -8        ; graphic 62
                    DB       -16,  -8        ; graphic 63
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -6        ; graphic 81
                    DB         0,   0
                    DB       -12,  -6        ; graphic 83
                    DB       -16,  -8        ; graphic 84
                    DB       -16,  -8        ; graphic 85
                    DB         0,   0
                    DB        -8,  -4        ; graphic 87
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -16,  -8        ; graphic 91
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 97
                    DB       -12,  -4        ; graphic 98
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 102
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 120
                    DB       -12,  -4        ; graphic 121
                    DB       -12,  -4        ; graphic 122
                    DB       -12,  -4        ; graphic 123
                    DB       -12,  -4        ; graphic 124
                    DB       -12,  -4        ; graphic 125
                    DB       -12,  -4        ; graphic 126
                    DB       -12,  -4        ; graphic 127
                    DB        -8,  -2        ; graphic 128
                    DB        -8,  -2        ; graphic 129
                    DB        -8,  -2        ; graphic 130
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -16, -12        ; graphic 141
                    DB       -24,  12        ; graphic 142
                    DB       -16,  -8        ; graphic 143
                    DB         0,   0
                    DB       -12,  -6        ; graphic 145
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,   7        ; graphic 150
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,   3        ; graphic 158
                    DB         0,   0
                    DB       -12,  -4        ; graphic 160
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 165
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB        -8,  -4        ; graphic 179
                    DB        -8,  -4        ; graphic 180
                    DB         0,   0
                    DB         0,   0
                    DB        -8,  -4        ; graphic 183
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0

sprite_adj_flipped: 
                    DB         0,   0
                    DB         0,   0
                    DB       -17,  -2        ; graphic 2
                    DB        -7,  -2        ; graphic 3
                    DB       -17,  -2        ; graphic 4
                    DB        -7,  -2        ; graphic 5
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -6        ; graphic 8
                    DB       -12,  -6        ; graphic 9
                    DB       -20,  -1        ; graphic 10
                    DB       -12,  -2        ; graphic 11
                    DB        -8,  -4        ; graphic 12
                    DB         0,   0
                    DB         0,   0
                    DB        -8,  -4        ; graphic 15
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -16,  -8        ; graphic 23
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -6        ; graphic 81
                    DB         0,   0
                    DB       -12,  -6        ; graphic 83
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB        -8,  -2        ; graphic 128
                    DB        -8,  -2        ; graphic 129
                    DB        -8,  -2        ; graphic 130
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0

