; Generated by adj.py from a running Knight Lore -- do not edit.
;
; The pixel nudge that lines a sprite's artwork up with its logical
; position. Knight Lore picks these inside 29 per-graphic update
; routines rather than reading a table, so these are the values its own
; code produced, read back out of live object records.
;
; Indexed by graphic number. Mirrored objects get a different pair, so
; there are two tables and object placement picks by the flip flag.

sprite_adj:         
                    DB         0,   0
                    DB       -12,  -8        ; graphic 1
                    DB        -7,  -3        ; graphic 2
                    DB        -9,  -3        ; graphic 3
                    DB         1,  -3        ; graphic 4
                    DB        -9,  -3        ; graphic 5
                    DB       -16,  -8        ; graphic 6
                    DB       -16,  -8        ; graphic 7
                    DB       -12,  -6        ; graphic 8
                    DB       -12,  -6        ; graphic 9
                    DB       -20,  -1        ; graphic 10
                    DB       -12,  -2        ; graphic 11
                    DB        -8,  -4        ; graphic 12
                    DB        -8,  -4        ; graphic 13
                    DB        -8,  -4        ; graphic 14
                    DB        -8,  -4        ; graphic 15
                    DB       -12,  -6        ; graphic 16
                    DB       -12,  -6        ; graphic 17
                    DB       -12,  -6        ; graphic 18
                    DB       -12,  -6        ; graphic 19
                    DB       -12,  -6        ; graphic 20
                    DB       -12,  -6        ; graphic 21
                    DB       -12,  -7        ; graphic 22
                    DB       -16,  -8        ; graphic 23, from the other way round
                    DB       -12,  -6        ; graphic 24
                    DB       -12,  -6        ; graphic 25
                    DB       -12,  -6        ; graphic 26
                    DB       -12,  -6        ; graphic 27
                    DB       -12,  -6        ; graphic 28
                    DB       -12,  -6        ; graphic 29
                    DB       -12,   3        ; graphic 30
                    DB       -12,   3        ; graphic 31, assumed from 30
                    DB       -12,  -8        ; graphic 32
                    DB       -12,  -8        ; graphic 33
                    DB       -12,  -8        ; graphic 34
                    DB       -12,  -8        ; graphic 35
                    DB       -12,  -8        ; graphic 36
                    DB       -12,  -8        ; graphic 37
                    DB       -12,  -8        ; graphic 38
                    DB         0,   0
                    DB       -12,  -8        ; graphic 40
                    DB       -12,  -8        ; graphic 41
                    DB       -12,  -8        ; graphic 42
                    DB       -12,  -8        ; graphic 43
                    DB       -12,  -8        ; graphic 44
                    DB       -12,  -8        ; graphic 45
                    DB       -12,  -8        ; graphic 46
                    DB       -12,  -8        ; graphic 47
                    DB       -12,  -7        ; graphic 48
                    DB       -12,  -7        ; graphic 49
                    DB       -12,  -7        ; graphic 50
                    DB       -12,  -7        ; graphic 51
                    DB       -12,  -7        ; graphic 52
                    DB       -12,  -7        ; graphic 53
                    DB       -16,  -8        ; graphic 54
                    DB       -16,  -8        ; graphic 55
                    DB       -12,  -7        ; graphic 56
                    DB       -12,  -7        ; graphic 57
                    DB       -12,  -7        ; graphic 58, from the other way round
                    DB       -12,  -7        ; graphic 59
                    DB       -12,  -7        ; graphic 60
                    DB       -12,  -7        ; graphic 61, from the other way round
                    DB       -16,  -8        ; graphic 62
                    DB       -16,  -8        ; graphic 63
                    DB       -12, -12        ; graphic 64
                    DB       -12, -12        ; graphic 65
                    DB       -12, -12        ; graphic 66
                    DB       -12, -12        ; graphic 67
                    DB       -12, -12        ; graphic 68
                    DB       -12, -12        ; graphic 69
                    DB       -12, -12        ; graphic 70
                    DB         0,   0
                    DB       -12, -12        ; graphic 72
                    DB       -12, -12        ; graphic 73
                    DB       -12, -12        ; graphic 74, from the other way round
                    DB       -12, -12        ; graphic 75
                    DB       -12, -12        ; graphic 76
                    DB       -12, -12        ; graphic 77, from the other way round
                    DB       -12, -12        ; graphic 78, from the other way round
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -6        ; graphic 81
                    DB         0,   0
                    DB       -12,  -6        ; graphic 83
                    DB       -16,  -8        ; graphic 84
                    DB       -16,  -8        ; graphic 85
                    DB         0,   0
                    DB        -8,  -4        ; graphic 87
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -16,  -8        ; graphic 91
                    DB       -12,  -2        ; graphic 92, from the other way round
                    DB       -12,  -2        ; graphic 93
                    DB       -12,  -2        ; graphic 94
                    DB       -12,  -2        ; graphic 95
                    DB         0,   0
                    DB       -12,  -4        ; graphic 97
                    DB       -12,  -4        ; graphic 98
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 102
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 120
                    DB       -12,  -4        ; graphic 121
                    DB       -12,  -4        ; graphic 122
                    DB       -12,  -4        ; graphic 123
                    DB       -12,  -4        ; graphic 124
                    DB       -12,  -4        ; graphic 125
                    DB       -12,  -4        ; graphic 126
                    DB       -12,  -4        ; graphic 127
                    DB        -8,  -2        ; graphic 128
                    DB        -8,  -2        ; graphic 129
                    DB        -8,  -2        ; graphic 130
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -16, -12        ; graphic 141
                    DB       -24,  12        ; graphic 142
                    DB       -16,  -8        ; graphic 143
                    DB         0,   0
                    DB       -12,  -6        ; graphic 145
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,   7        ; graphic 150
                    DB       -12,   7        ; graphic 151, assumed from 150
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,   3        ; graphic 158
                    DB       -12,   3        ; graphic 159, assumed from 158
                    DB       -12,  -4        ; graphic 160
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 165
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB        -8,  -4        ; graphic 179
                    DB        -8,  -4        ; graphic 180
                    DB         0,   0
                    DB         0,   0
                    DB        -8,  -4        ; graphic 183
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0

sprite_adj_flipped: 
                    DB         0,   0
                    DB       -12,  -8        ; graphic 1, from the other way round
                    DB       -17,  -2        ; graphic 2
                    DB        -7,  -2        ; graphic 3
                    DB       -17,  -2        ; graphic 4
                    DB        -7,  -2        ; graphic 5
                    DB       -16,  -8        ; graphic 6, from the other way round
                    DB       -16,  -8        ; graphic 7, from the other way round
                    DB       -12,  -6        ; graphic 8
                    DB       -12,  -6        ; graphic 9
                    DB       -20,  -1        ; graphic 10
                    DB       -12,  -2        ; graphic 11
                    DB        -8,  -4        ; graphic 12
                    DB        -8,  -4        ; graphic 13, from the other way round
                    DB        -8,  -4        ; graphic 14, from the other way round
                    DB        -8,  -4        ; graphic 15
                    DB       -12,  -6        ; graphic 16
                    DB       -12,  -6        ; graphic 17
                    DB       -12,  -6        ; graphic 18
                    DB       -12,  -6        ; graphic 19
                    DB       -12,  -6        ; graphic 20
                    DB       -12,  -6        ; graphic 21
                    DB       -12,  -7        ; graphic 22, from the other way round
                    DB       -16,  -8        ; graphic 23
                    DB       -12,  -6        ; graphic 24
                    DB       -12,  -6        ; graphic 25
                    DB       -12,  -6        ; graphic 26
                    DB       -12,  -6        ; graphic 27
                    DB       -12,  -6        ; graphic 28
                    DB       -12,  -6        ; graphic 29
                    DB       -12,   3        ; graphic 30, from the other way round
                    DB       -12,   3        ; graphic 31, assumed from 30
                    DB       -12,  -8        ; graphic 32
                    DB       -12,  -8        ; graphic 33
                    DB       -12,  -8        ; graphic 34
                    DB       -12,  -8        ; graphic 35
                    DB       -12,  -8        ; graphic 36
                    DB       -12,  -8        ; graphic 37
                    DB       -12,  -8        ; graphic 38, from the other way round
                    DB         0,   0
                    DB       -12,  -8        ; graphic 40
                    DB       -12,  -8        ; graphic 41
                    DB       -12,  -8        ; graphic 42
                    DB       -12,  -8        ; graphic 43
                    DB       -12,  -8        ; graphic 44
                    DB       -12,  -8        ; graphic 45
                    DB       -12,  -8        ; graphic 46
                    DB       -12,  -8        ; graphic 47
                    DB       -12,  -7        ; graphic 48
                    DB       -12,  -7        ; graphic 49
                    DB       -12,  -7        ; graphic 50
                    DB       -12,  -7        ; graphic 51
                    DB       -12,  -7        ; graphic 52
                    DB       -12,  -7        ; graphic 53
                    DB       -16,  -8        ; graphic 54, from the other way round
                    DB       -16,  -8        ; graphic 55, from the other way round
                    DB       -12,  -7        ; graphic 56
                    DB       -12,  -7        ; graphic 57
                    DB       -12,  -7        ; graphic 58
                    DB       -12,  -7        ; graphic 59
                    DB       -12,  -7        ; graphic 60
                    DB       -12,  -7        ; graphic 61
                    DB       -16,  -8        ; graphic 62, from the other way round
                    DB       -16,  -8        ; graphic 63, from the other way round
                    DB       -12, -12        ; graphic 64, from the other way round
                    DB       -12, -12        ; graphic 65
                    DB       -12, -12        ; graphic 66, from the other way round
                    DB       -12, -12        ; graphic 67, from the other way round
                    DB       -12, -12        ; graphic 68, from the other way round
                    DB       -12, -12        ; graphic 69
                    DB       -12, -12        ; graphic 70
                    DB         0,   0
                    DB       -12, -12        ; graphic 72
                    DB       -12, -12        ; graphic 73
                    DB       -12, -12        ; graphic 74
                    DB       -12, -12        ; graphic 75
                    DB       -12, -12        ; graphic 76
                    DB       -12, -12        ; graphic 77
                    DB       -12, -12        ; graphic 78
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -6        ; graphic 81
                    DB         0,   0
                    DB       -12,  -6        ; graphic 83
                    DB       -16,  -8        ; graphic 84, from the other way round
                    DB       -16,  -8        ; graphic 85, from the other way round
                    DB         0,   0
                    DB        -8,  -4        ; graphic 87, from the other way round
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -16,  -8        ; graphic 91, from the other way round
                    DB       -12,  -2        ; graphic 92
                    DB       -12,  -2        ; graphic 93, from the other way round
                    DB       -12,  -2        ; graphic 94, from the other way round
                    DB       -12,  -2        ; graphic 95
                    DB         0,   0
                    DB       -12,  -4        ; graphic 97, from the other way round
                    DB       -12,  -4        ; graphic 98, from the other way round
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 102, from the other way round
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 120, from the other way round
                    DB       -12,  -4        ; graphic 121, from the other way round
                    DB       -12,  -4        ; graphic 122, from the other way round
                    DB       -12,  -4        ; graphic 123, from the other way round
                    DB       -12,  -4        ; graphic 124, from the other way round
                    DB       -12,  -4        ; graphic 125, from the other way round
                    DB       -12,  -4        ; graphic 126, from the other way round
                    DB       -12,  -4        ; graphic 127, from the other way round
                    DB        -8,  -2        ; graphic 128
                    DB        -8,  -2        ; graphic 129
                    DB        -8,  -2        ; graphic 130
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -16, -12        ; graphic 141, from the other way round
                    DB       -24,  12        ; graphic 142, from the other way round
                    DB       -16,  -8        ; graphic 143, from the other way round
                    DB         0,   0
                    DB       -12,  -6        ; graphic 145, from the other way round
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,   7        ; graphic 150, from the other way round
                    DB       -12,   7        ; graphic 151, assumed from 150
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,   3        ; graphic 158, from the other way round
                    DB       -12,   3        ; graphic 159, assumed from 158
                    DB       -12,  -4        ; graphic 160, from the other way round
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB       -12,  -4        ; graphic 165, from the other way round
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB        -8,  -4        ; graphic 179, from the other way round
                    DB        -8,  -4        ; graphic 180, from the other way round
                    DB         0,   0
                    DB         0,   0
                    DB        -8,  -4        ; graphic 183, from the other way round
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0
                    DB         0,   0

