; Generated by adj.py from a running Knight Lore -- do not edit.
;
; The pixel nudge that lines a sprite's artwork up with its logical
; position. Knight Lore picks these inside 29 per-graphic update
; routines rather than reading a table, so these are the values its
; own code produced, read back out of live object records.
;
; 20 distinct pairs cover all 256 graphics both ways round, and 4
; graphics want a different one mirrored. room_adjust does the lookup.

; The pairs, x then y. Entry 0 is no nudge at all, so a graphic
; nothing knows about indexes to it harmlessly.
sprite_adj_pairs:
					DB		   0,   0		; 0
					DB		 -12,  -8		; 2
					DB		  -7,  -3		; 4
					DB		 -17,  -2		; 6
					DB		  -9,  -3		; 8
					DB		  -7,  -2		; 10
					DB		   1,  -3		; 12
					DB		 -16,  -8		; 14
					DB		 -12,  -6		; 16
					DB		 -20,  -1		; 18
					DB		 -12,  -2		; 20
					DB		  -8,  -4		; 22
					DB		 -12,  -7		; 24
					DB		 -12,   3		; 26
					DB		 -12, -12		; 28
					DB		 -12,  -4		; 30
					DB		  -8,  -2		; 32
					DB		 -16, -12		; 34
					DB		 -24,  12		; 36
					DB		 -12,   7		; 38


; Graphics whose mirror image wants a different nudge from their
; plain one. Graphic, then its mirrored index; a zero graphic ends it.
sprite_adj_mirror:
					DB		  2,   6
					DB		  3,  10
					DB		  4,   6
					DB		  5,  10
					DB		0


; One byte a graphic: its pair, doubled, plus bit 7 if the mirror
; differs. Page-aligned, so the graphic number IS the low byte of
; the address and the lookup needs no arithmetic at all.
					ALIGN	256
sprite_adj_index:
					DB		$00, $02, $84, $88, $8C, $88, $0E, $0E		; 0
					DB		$10, $10, $12, $14, $16, $16, $16, $16		; 8
					DB		$10, $10, $10, $10, $10, $10, $18, $0E		; 16
					DB		$10, $10, $10, $10, $10, $10, $1A, $1A		; 24
					DB		$02, $02, $02, $02, $02, $02, $02, $00		; 32
					DB		$02, $02, $02, $02, $02, $02, $02, $02		; 40
					DB		$18, $18, $18, $18, $18, $18, $0E, $0E		; 48
					DB		$18, $18, $18, $18, $18, $18, $0E, $0E		; 56
					DB		$1C, $1C, $1C, $1C, $1C, $1C, $1C, $00		; 64
					DB		$1C, $1C, $1C, $1C, $1C, $1C, $1C, $00		; 72
					DB		$00, $10, $00, $10, $0E, $0E, $00, $16		; 80
					DB		$00, $00, $00, $0E, $14, $14, $14, $14		; 88
					DB		$00, $1E, $1E, $00, $00, $00, $1E, $00		; 96
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 104
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 112
					DB		$1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E		; 120
					DB		$20, $20, $20, $00, $00, $00, $00, $00		; 128
					DB		$00, $00, $00, $00, $00, $22, $24, $0E		; 136
					DB		$00, $10, $00, $00, $00, $00, $26, $26		; 144
					DB		$00, $00, $00, $00, $00, $00, $1A, $1A		; 152
					DB		$1E, $00, $00, $00, $00, $1E, $00, $00		; 160
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 168
					DB		$00, $00, $00, $16, $16, $00, $00, $16		; 176
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 184
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 192
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 200
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 208
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 216
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 224
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 232
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 240
					DB		$00, $00, $00, $00, $00, $00, $00, $00		; 248

