"""Builds the Exile-like: generates its data, then assembles it with sjasmplus.

    python examples/exile/build.py

Writes output/exile.sna, with output/exile.sld beside it for source-level
stepping, output/exile.lst, and the symbols in output/exile.sym. Everything
in output/ is regenerated: the data the game is built from is world.txt and
the Python here, never the .s it becomes.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
OUT = HERE / "output"

sys.path.insert(0, str(HERE))
import sprites  # noqa: E402
import tiles  # noqa: E402
import world  # noqa: E402

# The same search as examples/filmation's build: named, then the repo's copy,
# then PATH.
SJASMPLUS_CANDIDATES = [
    REPO / "tools" / "sjasmplus" / "sjasmplus.exe",
    REPO / ".venv-win" / "Scripts" / "sjasmplus.exe",
]

INSTALL_HELP = (
    "sjasmplus not found.\n"
    "Windows: download the prebuilt sjasmplus-<version>.win.zip from\n"
    "  https://github.com/z00m128/sjasmplus/releases and unzip it into\n"
    f"  {REPO / 'tools' / 'sjasmplus'} (or put sjasmplus.exe on PATH).\n"
    "Linux/macOS: build from source:\n"
    "  git clone https://github.com/z00m128/sjasmplus.git\n"
    "  cd sjasmplus && git submodule update --init --recursive && make"
)


def find_sjasmplus() -> str:
    named = os.environ.get("SJASMPLUS")
    if named and Path(named).is_file():
        return named
    for candidate in SJASMPLUS_CANDIDATES:
        if candidate.is_file():
            return str(candidate)
    on_path = shutil.which("sjasmplus")
    if on_path is not None:
        return on_path
    sys.exit(INSTALL_HELP)


def db_lines(data: bytes, per_line: int = 16) -> list[str]:
    return ["    db " + ", ".join(f"0x{b:02X}" for b in data[i:i + per_line])
            for i in range(0, len(data), per_line)]


def write_data() -> None:
    """output/data.s: every table the game reads, in the order and alignment
    exile.s's memory map expects."""
    sprite_data = sprites.sprite_bytes()
    lines = [
        "; Generated by build.py from world.txt, world.py, tiles.py and sprites.py.",
        "; Do not edit: edit those and rebuild.",
        "",
        "KIND_ROCK    equ %d" % world.ROCK,
        "KIND_MASONRY equ %d" % world.MASONRY,
        "KIND_CHAMBER equ %d" % world.CHAMBER,
        "",
        "    ALIGN 256",
        "perm:",
        *db_lines(bytes(world.PERM)),
        "wave:",
        *db_lines(bytes(v & 0xFF for v in world.WAVE)),
        "world_map:",
        *db_lines(bytes(world.load_map()), world.MAP_W),
        "    ALIGN 512",
        "tile_gfx:",
        *db_lines(tiles.graphics_bytes()),
        "tile_mask:",
        *db_lines(tiles.mask_bytes()),
        "sprite_gfx:",
        *db_lines(sprite_data),
        "",
        "; Image * 8 + shift -> that image's rows at that shift.",
        "sprite_table:",
    ]
    image_size = 8 * sprites.H * 6
    for image in range(len(sprites.image_order())):
        lines.append("    dw " + ", ".join(
            f"sprite_gfx + {image * image_size + shift * sprites.H * 6}" for shift in range(8)))
    (OUT / "data.s").write_text("\n".join(lines) + "\n")


def assemble(sjasmplus: str) -> None:
    cmd = [
        sjasmplus,
        "--nologo",
        "--fullpath",
        f"--sld={OUT / 'exile.sld'}",
        f"--lst={OUT / 'exile.lst'}",
        f"--sym={OUT / 'exile.sym'}",
        "exile.s",
    ]
    result = subprocess.run(cmd, cwd=HERE)
    if result.returncode != 0:
        sys.exit(result.returncode)


def main() -> None:
    OUT.mkdir(exist_ok=True)
    write_data()
    assemble(find_sjasmplus())
    print(f"wrote {OUT / 'exile.sna'}")


if __name__ == "__main__":
    main()
