"""Builds the Exile-like: generates its data, then assembles it with sjasmplus.

    python examples/exile/build.py

Writes output/exile.sna, with output/exile.sld beside it for source-level
stepping, output/exile.lst, and the symbols in output/exile.sym. Everything
in output/ is regenerated: what the game is built from is map.txt,
blocks.png and blocks.json, and the sprite in sprites.py -- never the .s and
.bin they become.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
OUT = HERE / "output"

sys.path.insert(0, str(HERE))
import blocks  # noqa: E402
import planet  # noqa: E402
import sprites  # noqa: E402

# The same search as examples/filmation's build: named, then the repo's copy,
# then PATH.
SJASMPLUS_CANDIDATES = [
    REPO / "tools" / "sjasmplus" / "sjasmplus.exe",
    REPO / ".venv-win" / "Scripts" / "sjasmplus.exe",
]

INSTALL_HELP = (
    "sjasmplus not found.\n"
    "Windows: download the prebuilt sjasmplus-<version>.win.zip from\n"
    "  https://github.com/z00m128/sjasmplus/releases and unzip it into\n"
    f"  {REPO / 'tools' / 'sjasmplus'} (or put sjasmplus.exe on PATH).\n"
    "Linux/macOS: build from source:\n"
    "  git clone https://github.com/z00m128/sjasmplus.git\n"
    "  cd sjasmplus && git submodule update --init --recursive && make"
)


def find_sjasmplus() -> str:
    named = os.environ.get("SJASMPLUS")
    if named and Path(named).is_file():
        return named
    for candidate in SJASMPLUS_CANDIDATES:
        if candidate.is_file():
            return str(candidate)
    on_path = shutil.which("sjasmplus")
    if on_path is not None:
        return on_path
    sys.exit(INSTALL_HELP)


def db_lines(data: bytes, per_line: int = 16) -> list[str]:
    return ["    db " + ", ".join(f"0x{b:02X}" for b in data[i:i + per_line])
            for i in range(0, len(data), per_line)]


def write_data() -> None:
    """output/data.s and output/map.bin: every table the game reads, in the
    order and alignment exile.s's memory map expects."""
    blockset = blocks.BlockSet()
    world = planet.read(blockset)
    (OUT / "map.bin").write_bytes(bytes(world))

    sprite_data = sprites.sprite_bytes()
    lines = [
        "; Generated by build.py from blocks.png, blocks.json and sprites.py.",
        "; Do not edit: edit those and rebuild.",
        "",
        f"; {len(blockset.legend)} blocks of {blocks.MAX_BLOCKS}.",
        "    ALIGN 2048",
        "block_gfx:",
        *db_lines(blockset.graphics_bytes()),
        "    ALIGN 2048",
        "block_mask:",
        *db_lines(blockset.mask_bytes()),
        "sprite_gfx:",
        *db_lines(sprite_data),
        "",
        "; Image * 8 + shift -> that image's rows at that shift.",
        "sprite_table:",
    ]
    image_size = 8 * sprites.H * 6
    for image in range(len(sprites.image_order())):
        lines.append("    dw " + ", ".join(
            f"sprite_gfx + {image * image_size + shift * sprites.H * 6}" for shift in range(8)))
    (OUT / "data.s").write_text("\n".join(lines) + "\n")


def assemble(sjasmplus: str) -> None:
    cmd = [
        sjasmplus,
        "--nologo",
        "--fullpath",
        f"--sld={OUT / 'exile.sld'}",
        f"--lst={OUT / 'exile.lst'}",
        f"--sym={OUT / 'exile.sym'}",
        "exile.s",
    ]
    result = subprocess.run(cmd, cwd=HERE)
    if result.returncode != 0:
        sys.exit(result.returncode)


def main() -> None:
    OUT.mkdir(exist_ok=True)
    try:
        write_data()
    except ValueError as e:
        sys.exit(f"error: {e}")
    assemble(find_sjasmplus())
    print(f"wrote {OUT / 'exile.sna'}")


if __name__ == "__main__":
    main()
