"""Generates cpp-core/src/generated/dispatch.inc from
vendor/chips/z80_desc.yml, porting codegen/z80_gen.py's own algorithm
(the script that generates the real z80.h from that same YAML -- fetched
for reference to .chips-codegen-src/z80_gen.py, not vendored/committed)
to target C++ instead of C.

Output is at HALF-T-STATE resolution: every T-state becomes two switch
cases, H then L (address valid on H, control lines assert on L). See
cpp-core/src/z80.h's header comment for why -- briefly, the gap between
"address valid" and "MREQ asserted" within T1 is the window a 48K ULA
contends on, and a whole-T-state core cannot represent it.

rust-core/zx-core/src/generated/dispatch.rs is NO LONGER generated by this
script. It stays committed as-is: rust-core is frozen as the reference
implementation to diff the C++ core against until that reaches parity.

Scope: unprefixed (0x00-0xFF) and ED-prefixed opcodes only. CB/DD/FD
prefixes and interrupt acknowledge sequences are deliberately skipped --
those are hand-written in z80.cpp. I/O (ioread/iowrite mcycles, including
the block forms INI/IND/INIR/INDR/OUTI/OUTD/OTIR/OTDR) IS handled -- the
machine's bus decode is address-based, so no per-opcode device model is
needed.

Mechanical parts (opcode enumeration via the YAML's `cond` bitfield
expressions, T-state/step bookkeeping per mcycle type) are fully
data-driven, porting z80_gen.py's own algorithm directly. The free-form
`action`/`post_action` C snippets are NOT auto-transpiled -- they're
translated via a hand-verified per-instruction-name lookup below (built by
reading every entry in z80_desc.yml directly), since the set of distinct
patterns is small and enumerable, and hand-translating with a human
understanding of Z80 semantics is far more reliable than a fragile general
C-expression parser would be for this one-time job.

Usage:
    python scripts/generate_z80_dispatch.py
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DESC_PATH = PROJECT_ROOT / "vendor" / "chips" / "z80_desc.yml"
OUT_PATH = PROJECT_ROOT / "cpp-core" / "src" / "generated" / "dispatch.inc"

ED_STEP_BASE = 256
EXTRA_STEP_BASE = 512

MEM_TCYCLES = 3
IO_TCYCLES = 4

# Names of YAML entries this generator does not attempt: HALT is
# hand-written in cpu.rs (its PC-rewind trick doesn't fit the generic
# pattern). `OUT (n),A`/`IN A,(n)`/`IN $RY,(C)`/`IN (C)`/`OUT (C),$RY`/
# `OUT (C),0`/INI/IND/INIR/INDR/OUTI/OUTD/OTIR/OTDR ARE handled -- see the
# ioread/iowrite T-state kinds below -- since `Spectrum48K::tick()`'s bus
# decode is already address-based (any port with A0=0 hits the ULA
# keyboard/border regardless of which opcode issued the IORQ, matching
# real hardware), so these need no new device model, just the CPU-side
# dispatch (a real port beyond the ULA, e.g. a 128K AY chip, would just
# read/write as unmapped floating-bus/no-op, same as any other opcode's
# access to one). Everything else here is a `special` payload (CB/DD/FD/
# interrupt handling, out of scope for this pass).
SKIP_NAMES = {
    "HALT",
    "ddfdcb", "int_im0", "int_im1", "int_im2", "nmi",
    # The BYTE-DISPATCH entries for the CB/DD/FD prefixes themselves (not
    # to be confused with the lowercase 'cb'/'ddfdcb' *payload* entries
    # above, which are separately marked `special` and already excluded
    # that way). These MUST be skipped explicitly: `emit_overlapped()`
    # only special-cases `prefix: ed`, so leaving these in silently
    # treated 0xCB/0xDD/0xFD as a bare no-op-then-refetch instead of
    # properly failing -- found via a real, nasty bug this caused (see
    # rust-core plan): ZEXALL's own shared per-iteration test harness does
    # `POP IY; POP IX` on every single iteration of every single test
    # group, so `POP IX` (0xDD 0xE1) silently became "NOP; POP HL",
    # corrupting HL every iteration without ever panicking -- no crash to
    # notice, just wrong results forever. Skipping these here instead
    # makes hitting 0xCB/0xDD/0xFD panic loudly (the stated design
    # principle for anything genuinely unimplemented), which is what
    # should have happened from the start.
    "CB prefix", "DD prefix", "FD prefix",
}

# ---- register field tables, indexed by the y/z/p 3-bit (or 2-bit) field ----
# B C D E H L (HL) A -- index 6 ((HL)) is never used by any op this
# generator handles (those go through $DLATCH/$ADDR instead), so it's
# left as None and will loudly KeyError/TypeError if something tries.
R = ["regs.b", "regs.c", "regs.d", "regs.e",
     "regs.h", "regs.l", None, "regs.a"]

# 16-bit pair reads. dd-style (index 3 = SP) and qq/rp2-style (index 3 = AF)
# differ only at index 3.
RP_DD_READ = ["regs.bc()", "regs.de()", "regs.hl()", "regs.sp"]
RP_QQ_READ = ["regs.bc()", "regs.de()", "regs.hl()", "regs.af()"]
RP_DD_SET = ["set_bc", "set_de", "set_hl", None]  # SP has no setter, direct field
RP_QQ_SET = ["set_bc", "set_de", "set_hl", "set_af"]

# High/low BYTE of a pair -- for BC/DE/HL these are just the existing
# individual register fields (same insight z80_gen.py's own rpl_map/rph_map
# tables encode); only SP/AF need something else, and AF's halves are just
# A and F, also plain fields.
RP_LOW = ["regs.c", "regs.e", "regs.l", "regs.spl()"]
RP_HIGH = ["regs.b", "regs.d", "regs.h", "regs.sph()"]
RP2_LOW = ["regs.c", "regs.e", "regs.l", "regs.f"]
RP2_HIGH = ["regs.b", "regs.d", "regs.h", "regs.a"]
RP_LOW_SET = ["regs.c", "regs.e", "regs.l", None]  # SP low set via set_spl()
RP_HIGH_SET = ["regs.b", "regs.d", "regs.h", None]

# Parenthesised deliberately: in C++ `&` binds LOOSER than `==`, so
# `regs.f & FLAG_Z == 0` would parse as `regs.f & (FLAG_Z == 0)` and quietly
# invert every conditional jump. (Rust's precedence is the other way round,
# which is why the Rust version of this table could omit the parens.)
CC_EXPR = [
    "(regs.f & FLAG_Z) == 0", "(regs.f & FLAG_Z) != 0",
    "(regs.f & FLAG_C) == 0", "(regs.f & FLAG_C) != 0",
    "(regs.f & FLAG_PV) == 0", "(regs.f & FLAG_PV) != 0",
    "(regs.f & FLAG_S) == 0", "(regs.f & FLAG_S) != 0",
]
CC_NAME = ["NZ", "Z", "NC", "C", "PO", "PE", "P", "M"]

IM_TABLE = [0, 0, 1, 2, 0, 0, 1, 2]


def r_read(idx: int) -> str:
    return R[idx]


def r_read_expr(idx: int) -> str:
    """$RY/$RZ-style SUBSTITUTABLE 8-bit register read: index 4/5 (H/L)
    route through hlx_h()/hlx_l() (become IXH/IXL/IYH/IYL under a DD/FD
    prefix); everything else is a plain field, unaffected by any prefix."""
    if idx == 4:
        return "hlx_h()"
    if idx == 5:
        return "hlx_l()"
    return R[idx]


def r_write_stmt(idx: int, value_expr: str) -> str:
    """Same substitution as `r_read_expr`, but as a full assignment
    statement (H/L need a setter *call*, not an lvalue, since hlx routing
    is a runtime choice of field)."""
    if idx == 4:
        return f"set_hlx_h({value_expr});"
    if idx == 5:
        return f"set_hlx_l({value_expr});"
    return f"{R[idx]} = {value_expr};"


def rp_read(p: int, dd: bool) -> str:
    return (RP_DD_READ if dd else RP_QQ_READ)[p]


def rp_read_expr(p: int, dd: bool) -> str:
    """$RP/$RP2-style SUBSTITUTABLE 16-bit pair read: p==2 (HL slot) routes
    through hlx() (becomes IX/IY under a DD/FD prefix); BC/DE/SP/AF are
    never shadowed, so they stay literal."""
    if p == 2:
        return "hlx()"
    return (RP_DD_READ if dd else RP_QQ_READ)[p]


def rp_set_stmt_hlx(p: int, dd: bool, value_expr: str) -> str:
    if p == 2:
        return f"set_hlx({value_expr});"
    return rp_set_stmt(p, dd, value_expr)


def rp_set_stmt(p: int, dd: bool, value_expr: str) -> str:
    setter = (RP_DD_SET if dd else RP_QQ_SET)[p]
    if setter is None:
        return f"regs.sp = {value_expr};"
    return f"regs.{setter}({value_expr});"


class Op:
    def __init__(self, name: str, cond: str, prefix: str, flags: dict, mcycles: list):
        self.name = name
        self.cond = cond
        self.cond_compiled = compile(cond, "<string>", "eval")
        self.prefix = prefix
        self.flags = flags
        self.mcycles = mcycles


# These two ARE handled this pass, despite being `flags: {special: true}`
# in the YAML (meaning "not enumerated via cond/x/y/z/p/q the normal
# way") -- they're the CB-prefix payload steps (register-direct and
# "(HL)" forms), generated at fixed extra-step numbers below and
# dispatched into by the hand-written CB fetch machine cycle in cpu.rs.
# `ddfdcb` (the DD+CB/FD+CB double-prefix payload) stays skipped -- it
# needs IX/IY substitution machinery that doesn't exist yet.
SPECIAL_BUT_HANDLED = {"cb", "cbhl"}


def parse_opdescs() -> list[Op]:
    with open(DESC_PATH, "r") as fp:
        desc = yaml.safe_load(fp)
    ops = []
    for name, d in desc.items():
        if name in SKIP_NAMES:
            continue
        if d.get("flags", {}).get("special") and name not in SPECIAL_BUT_HANDLED:
            continue
        mcycles = d.get("mcycles")
        if mcycles is None:
            raise ValueError(f"op '{name}' has no mcycles")
        ops.append(Op(name, d.get("cond", "True"), d.get("prefix", ""), d.get("flags", {}), mcycles))
    return ops


def find_op(ops: list[Op], name: str) -> Op:
    for op in ops:
        if op.name == name:
            return op
    raise ValueError(f"op '{name}' not found (check SPECIAL_BUT_HANDLED/SKIP_NAMES)")


def enumerate_opcodes(ops: list[Op]) -> dict[int, tuple[Op, int, int, int, int]]:
    """Returns {opcode_index: (op, y, z, p, q)}, opcode_index in 0..256 for
    unprefixed, ED_STEP_BASE..ED_STEP_BASE+256 for ED-prefixed. Mirrors
    z80_gen.py's expand_optable(): eval `cond` against every opcode byte,
    asserting no two descriptors ever claim the same byte.
    """
    table: dict[int, tuple[Op, int, int, int, int]] = {}
    for prefix_offset, prefix in ((0, ""), (ED_STEP_BASE, "ed")):
        for opcode in range(256):
            x = opcode >> 6
            y = (opcode >> 3) & 7
            z = opcode & 7
            p = y >> 1
            q = y & 1
            for op in ops:
                if op.prefix != prefix or op.flags.get("special"):
                    # `special` ops (currently: cb/cbhl, let through by
                    # parse_opdescs() specifically so find_op() can locate
                    # them) aren't enumerated via cond/x/y/z/p/q -- they're
                    # dispatched into a different way, see generate()'s own
                    # explicit gen_op() calls for them.
                    continue
                if eval(op.cond_compiled, {}, {"x": x, "y": y, "z": z, "p": p, "q": q}):
                    idx = prefix_offset + opcode
                    if idx in table:
                        raise ValueError(
                            f"condition collision at opcode {opcode:#04x} prefix={prefix!r}: "
                            f"'{table[idx][0].name}' and '{op.name}'"
                        )
                    table[idx] = (op, y, z, p, q)
    return table


# ============================================================================
# Per-instruction-name action translation. Each entry is a function
# (y, z, p, q, mcycle_index) -> C++ statement(s) (a string, possibly multiple
# `;`-separated statements, NO trailing step_ assignment -- that's added
# generically by render()). `mcycle_index` is which of the op's mcycles this
# action belongs to (0-based), since a few instructions have actions on more
# than one mcycle.
#
# Entries that need to branch forward (the conditional and repeating
# instructions) take an extra `skip` argument: a callable, `skip(k)`, giving
# the step number k T-states past this action's own next T-state. It is a
# callable rather than a precomputed number because the offsets differ per
# instruction (5 for the block/relative-jump forms, 6 for RET cc, 7 for
# CALL cc, 3 for the CB (HL) form), and because at half-T-state resolution
# those offsets can no longer be applied to a step number directly -- see
# Generator.skip_target().
#
# Emitting C++ rather than Rust: `self.` disappears (these are member
# functions), Rust's wrapping_add/sub become explicit-width casts, and
# tuple-returning alu functions become small named structs (r.new_a,
# r.repeat, ...). Everything is hand-translated rather than mechanically
# transformed -- a regex over generated code would fail silently and wrongly.
# ============================================================================

def alu_call(op_index_expr: str, val_expr: str) -> str:
    return f"alu_op({op_index_expr}, {val_expr});"


# Rewinds PC by two for a repeating block instruction's next pass, and parks
# WZ between them. Identical in every one of LDIR/LDDR/CPIR/CPDR/INIR/INDR/
# OTIR/OTDR, so it is spelled once.
BLOCK_REPEAT_REWIND = (
    "regs.pc = uint16_t(regs.pc - 1); regs.wz = regs.pc; "
    "regs.pc = uint16_t(regs.pc - 1);"
)


def _ldi_ldd_body() -> str:
    return (
        "uint16_t bc_after = uint16_t(regs.bc() - 1); regs.set_bc(bc_after); "
        "regs.f = alu::ldi_ldd_flags(regs.a, dlatch_, bc_after, regs.f);"
    )


def _cpi_cpd_body(step: str) -> str:
    return (
        f"regs.wz = uint16_t(regs.wz {step} 1); "
        "uint16_t bc_after = uint16_t(regs.bc() - 1); regs.set_bc(bc_after); "
        "auto r = alu::cpi_cpd(regs.a, dlatch_, bc_after, regs.f); regs.f = r.flags;"
    )


ACTIONS: dict[str, "callable"] = {
    "LD $RY,$RZ": lambda y, z, p, q, i: r_write_stmt(y, r_read_expr(z)),
    "$ALU (HL)": lambda y, z, p, q, i: alu_call(str(y), "dlatch_"),
    "$ALU $RZ": lambda y, z, p, q, i: alu_call(str(y), r_read_expr(z)),
    "$ALU n": lambda y, z, p, q, i: alu_call(str(y), "dlatch_"),
    "EX AF,AF'": lambda y, z, p, q, i: (
        "uint16_t af = regs.af(); "
        "uint16_t af2 = uint16_t((regs.a_ << 8) | regs.f_); "
        "regs.set_af(af2); regs.a_ = uint8_t(af >> 8); regs.f_ = uint8_t(af);"
    ),
    "DJNZ d": {
        1: lambda y, z, p, q, i, skip: (
            "regs.b = uint8_t(regs.b - 1); "
            f"if (regs.b == 0) {{ step_ = {skip(5)}; return true; }}"
        ),
        2: lambda y, z, p, q, i: (
            "regs.pc = uint16_t(regs.pc + int8_t(dlatch_)); regs.wz = regs.pc;"
        ),
    },
    "JR d": {
        1: lambda y, z, p, q, i: (
            "regs.pc = uint16_t(regs.pc + int8_t(dlatch_)); regs.wz = regs.pc;"
        ),
    },
    "JR $CC-4,d": {
        0: lambda y, z, p, q, i, skip: (
            f"if (!({CC_EXPR[y - 4]})) {{ step_ = {skip(5)}; return true; }}"
        ),
        1: lambda y, z, p, q, i: (
            "regs.pc = uint16_t(regs.pc + int8_t(dlatch_)); regs.wz = regs.pc;"
        ),
    },
    # z80.h's _z80_add16/_z80_adc16/_z80_sbc16 all set cpu->wz = (old) HL+1
    # as a side effect (ported here explicitly since alu::add16/adc16/sbc16
    # only compute the arithmetic result+flags, not this register side
    # effect -- found missing via a real differential-test failure, not
    # anticipated in advance).
    "ADD HL,$RP": lambda y, z, p, q, i: (
        "regs.wz = uint16_t(hlx() + 1); "
        f"auto r = alu::add16(hlx(), {rp_read_expr(p, True)}, regs.f); "
        "set_hlx(r.value); regs.f = r.flags;"
    ),
    "LD (BC),A": lambda y, z, p, q, i: (
        "regs.set_wzl(uint8_t(regs.c + 1)); regs.set_wzh(regs.a);"
    ),
    "LD (DE),A": lambda y, z, p, q, i: (
        "regs.set_wzl(uint8_t(regs.e + 1)); regs.set_wzh(regs.a);"
    ),
    "LD (nn),A": {2: lambda y, z, p, q, i: "regs.set_wzh(regs.a);"},
    # WZ high byte = A on the mread of the immediate port byte (matching
    # "$WZH=$A" in the YAML), so the port number ends up on the low half of
    # WZ and A duplicated onto the high half -- exactly what real hardware
    # puts on the upper address bus lines (A8-A15) during the actual io
    # cycle. OUT's iowrite mcycle also increments WZL afterward ("$WZL++"),
    # a real, if obscure, undocumented side effect.
    "OUT (n),A": {
        0: lambda y, z, p, q, i: "regs.set_wzh(regs.a);",
        1: lambda y, z, p, q, i: "regs.set_wzl(uint8_t(regs.wzl() + 1));",
    },
    "IN A,(n)": {0: lambda y, z, p, q, i: "regs.set_wzh(regs.a);"},
    # ED-prefixed port I/O ($BC as the full 16-bit port address). WZ=BC+1
    # on the ioread/iowrite mcycle (mirrors "$WZ=$BC+1" in the YAML, same
    # real-hardware upper-address-bus side effect as OUT (n),A / IN A,(n)
    # above). The overlapped mcycle's `_z80_in(cpu,$DLATCH)` sets S/Z/5/3/P
    # from the byte read, H=0, N=0, C preserved -- ported as alu::in_flags
    # rather than reusing and8/xor8/or8's private szp_flags helper, since
    # those also force flags this doesn't touch.
    "IN $RY,(C)": {
        0: lambda y, z, p, q, i: "regs.wz = uint16_t(regs.bc() + 1);",
        1: lambda y, z, p, q, i: (
            f"{R[y]} = dlatch_; regs.f = alu::in_flags(dlatch_, regs.f);"
        ),
    },
    "IN (C)": {
        0: lambda y, z, p, q, i: "regs.wz = uint16_t(regs.bc() + 1);",
        1: lambda y, z, p, q, i: "regs.f = alu::in_flags(dlatch_, regs.f);",
    },
    "OUT (C),$RY": {0: lambda y, z, p, q, i: "regs.wz = uint16_t(regs.bc() + 1);"},
    "OUT (C),0": {0: lambda y, z, p, q, i: "regs.wz = uint16_t(regs.bc() + 1);"},
    "LD A,(BC)": lambda y, z, p, q, i: "regs.wz = uint16_t(regs.bc() + 1);",
    "LD A,(DE)": lambda y, z, p, q, i: "regs.wz = uint16_t(regs.de() + 1);",
    "INC (HL)": lambda y, z, p, q, i: (
        "auto r = alu::inc8(dlatch_, regs.f); dlatch_ = r.value; regs.f = r.flags;"
    ),
    "DEC (HL)": lambda y, z, p, q, i: (
        "auto r = alu::dec8(dlatch_, regs.f); dlatch_ = r.value; regs.f = r.flags;"
    ),
    "INC $RY": lambda y, z, p, q, i: (
        f"auto r = alu::inc8({r_read_expr(y)}, regs.f); "
        f"{r_write_stmt(y, 'r.value')} regs.f = r.flags;"
    ),
    "DEC $RY": lambda y, z, p, q, i: (
        f"auto r = alu::dec8({r_read_expr(y)}, regs.f); "
        f"{r_write_stmt(y, 'r.value')} regs.f = r.flags;"
    ),
    "RLCA": lambda y, z, p, q, i: "auto r = alu::rlca(regs.a, regs.f); regs.a = r.value; regs.f = r.flags;",
    "RRCA": lambda y, z, p, q, i: "auto r = alu::rrca(regs.a, regs.f); regs.a = r.value; regs.f = r.flags;",
    "RLA": lambda y, z, p, q, i: "auto r = alu::rla(regs.a, regs.f); regs.a = r.value; regs.f = r.flags;",
    "RRA": lambda y, z, p, q, i: "auto r = alu::rra(regs.a, regs.f); regs.a = r.value; regs.f = r.flags;",
    "DAA": lambda y, z, p, q, i: "auto r = alu::daa(regs.a, regs.f); regs.a = r.value; regs.f = r.flags;",
    "CPL": lambda y, z, p, q, i: "auto r = alu::cpl(regs.a, regs.f); regs.a = r.value; regs.f = r.flags;",
    "SCF": lambda y, z, p, q, i: "regs.f = alu::scf(regs.a, regs.f);",
    "CCF": lambda y, z, p, q, i: "regs.f = alu::ccf(regs.a, regs.f);",
    "RET $CC": {
        0: lambda y, z, p, q, i, skip: (
            f"if (!({CC_EXPR[y]})) {{ step_ = {skip(6)}; return true; }}"
        ),
        2: lambda y, z, p, q, i: "regs.pc = regs.wz;",
    },
    "RET": {1: lambda y, z, p, q, i: "regs.pc = regs.wz;"},
    "EXX": lambda y, z, p, q, i: (
        "std::swap(regs.b, regs.b_); "
        "std::swap(regs.c, regs.c_); "
        "std::swap(regs.d, regs.d_); "
        "std::swap(regs.e, regs.e_); "
        "std::swap(regs.h, regs.h_); "
        "std::swap(regs.l, regs.l_);"
    ),
    "JP HL": lambda y, z, p, q, i: "regs.pc = hlx();",
    "LD SP,HL": lambda y, z, p, q, i: "regs.sp = hlx();",
    "JP $CC,nn": {1: lambda y, z, p, q, i: f"if ({CC_EXPR[y]}) {{ regs.pc = regs.wz; }}"},
    "JP nn": {1: lambda y, z, p, q, i: "regs.pc = regs.wz;"},
    "EX (SP),HL": {3: lambda y, z, p, q, i: "set_hlx(regs.wz);"},
    "EX DE,HL": lambda y, z, p, q, i: (
        "uint16_t de = regs.de(); regs.set_de(regs.hl()); regs.set_hl(de);"
    ),
    "DI": lambda y, z, p, q, i: "regs.iff1 = false; regs.iff2 = false;",
    "EI": {
        0: lambda y, z, p, q, i: "regs.iff1 = false; regs.iff2 = false;",
        "post": lambda y, z, p, q, i: "regs.iff1 = true; regs.iff2 = true;",
    },
    "CALL $CC,nn": {
        1: lambda y, z, p, q, i, skip: (
            f"if (!({CC_EXPR[y]})) {{ step_ = {skip(7)}; return true; }}"
        ),
        4: lambda y, z, p, q, i: "regs.pc = regs.wz;",
    },
    "CALL nn": {3: lambda y, z, p, q, i: "regs.pc = regs.wz;"},
    "RST $Y*8": {2: lambda y, z, p, q, i: f"regs.wz = {y * 8}; regs.pc = regs.wz;"},
    # ---- ED prefix block ---------------------------------------------------
    "SBC HL,$RP": lambda y, z, p, q, i: (
        "regs.wz = uint16_t(regs.hl() + 1); "
        f"auto r = alu::sbc16(regs.hl(), {rp_read(p, True)}, uint8_t(regs.f & FLAG_C)); "
        "regs.set_hl(r.value); regs.f = r.flags;"
    ),
    "ADC HL,$RP": lambda y, z, p, q, i: (
        "regs.wz = uint16_t(regs.hl() + 1); "
        f"auto r = alu::adc16(regs.hl(), {rp_read(p, True)}, uint8_t(regs.f & FLAG_C)); "
        "regs.set_hl(r.value); regs.f = r.flags;"
    ),
    "NEG": lambda y, z, p, q, i: "auto r = alu::sub8(0, regs.a); regs.a = r.value; regs.f = r.flags;",
    "RETI": {1: lambda y, z, p, q, i: "regs.pc = regs.wz;",
             "post": lambda y, z, p, q, i: "regs.iff1 = regs.iff2;"},
    "RETN": {1: lambda y, z, p, q, i: "regs.pc = regs.wz;",
             "post": lambda y, z, p, q, i: "regs.iff1 = regs.iff2;"},
    "IM $IMY": lambda y, z, p, q, i: f"regs.im = {IM_TABLE[y]};",
    "LD I,A": lambda y, z, p, q, i: "regs.i = regs.a;",
    "LD R,A": lambda y, z, p, q, i: "regs.r = regs.a;",
    "LD A,I": lambda y, z, p, q, i: (
        "regs.a = regs.i; regs.f = alu::sziff2_flags(regs.i, regs.f, regs.iff2);"
    ),
    "LD A,R": lambda y, z, p, q, i: (
        "regs.a = regs.r; regs.f = alu::sziff2_flags(regs.r, regs.f, regs.iff2);"
    ),
    "RRD": {
        1: lambda y, z, p, q, i: (
            "auto r = alu::rrd(regs.a, dlatch_, regs.f); "
            "regs.a = r.new_a; dlatch_ = r.new_mem; regs.f = r.flags;"
        ),
        2: lambda y, z, p, q, i: "regs.wz = uint16_t(regs.hl() + 1);",
    },
    "RLD": {
        1: lambda y, z, p, q, i: (
            "auto r = alu::rld(regs.a, dlatch_, regs.f); "
            "regs.a = r.new_a; dlatch_ = r.new_mem; regs.f = r.flags;"
        ),
        2: lambda y, z, p, q, i: "regs.wz = uint16_t(regs.hl() + 1);",
    },
    "LDI": {2: lambda y, z, p, q, i: _ldi_ldd_body()},
    "LDD": {2: lambda y, z, p, q, i: _ldi_ldd_body()},
    "LDIR": {
        2: lambda y, z, p, q, i, skip: (
            _ldi_ldd_body()
            + f" if (bc_after == 0) {{ step_ = {skip(5)}; return true; }}"
        ),
        3: lambda y, z, p, q, i: BLOCK_REPEAT_REWIND,
    },
    "LDDR": {
        2: lambda y, z, p, q, i, skip: (
            _ldi_ldd_body()
            + f" if (bc_after == 0) {{ step_ = {skip(5)}; return true; }}"
        ),
        3: lambda y, z, p, q, i: BLOCK_REPEAT_REWIND,
    },
    "CPI": {1: lambda y, z, p, q, i: _cpi_cpd_body("+")},
    "CPD": {1: lambda y, z, p, q, i: _cpi_cpd_body("-")},
    "CPIR": {
        1: lambda y, z, p, q, i, skip: (
            _cpi_cpd_body("+")
            + f" if (!r.repeat) {{ step_ = {skip(5)}; return true; }}"
        ),
        2: lambda y, z, p, q, i: BLOCK_REPEAT_REWIND,
    },
    "CPDR": {
        1: lambda y, z, p, q, i, skip: (
            _cpi_cpd_body("-")
            + f" if (!r.repeat) {{ step_ = {skip(5)}; return true; }}"
        ),
        2: lambda y, z, p, q, i: BLOCK_REPEAT_REWIND,
    },
    # INI/IND/OUTI/OUTD and their repeating forms -- mcycle shape mirrors
    # LDI/LDIR (an ioread/mread step that sets WZ and decrements B, then an
    # mwrite/iowrite step that computes the block_io_flags()-based flags and,
    # for the repeating forms, either loops via a trailing 5-tcycle generic
    # mcycle or falls straight through when B has reached 0). `regs.b` is
    # already the POST-decrement value by the time the flags get computed,
    # matching _z80_ini_ind / _z80_outi_outd's own "const uint8_t b = cpu->b"
    # read (which happens after the same decrement in z80.h too).
    "INI": {
        1: lambda y, z, p, q, i: (
            "regs.wz = uint16_t(regs.bc() + 1); regs.b = uint8_t(regs.b - 1);"
        ),
        2: lambda y, z, p, q, i: (
            "regs.f = alu::ini_ind_flags(regs.b, dlatch_, uint8_t(regs.c + 1));"
        ),
    },
    "IND": {
        1: lambda y, z, p, q, i: (
            "regs.wz = uint16_t(regs.bc() - 1); regs.b = uint8_t(regs.b - 1);"
        ),
        2: lambda y, z, p, q, i: (
            "regs.f = alu::ini_ind_flags(regs.b, dlatch_, uint8_t(regs.c - 1));"
        ),
    },
    "INIR": {
        1: lambda y, z, p, q, i: (
            "regs.wz = uint16_t(regs.bc() + 1); regs.b = uint8_t(regs.b - 1);"
        ),
        2: lambda y, z, p, q, i, skip: (
            "regs.f = alu::ini_ind_flags(regs.b, dlatch_, uint8_t(regs.c + 1)); "
            f"if (regs.b == 0) {{ step_ = {skip(5)}; return true; }}"
        ),
        3: lambda y, z, p, q, i: BLOCK_REPEAT_REWIND,
    },
    "INDR": {
        1: lambda y, z, p, q, i: (
            "regs.wz = uint16_t(regs.bc() - 1); regs.b = uint8_t(regs.b - 1);"
        ),
        2: lambda y, z, p, q, i, skip: (
            "regs.f = alu::ini_ind_flags(regs.b, dlatch_, uint8_t(regs.c - 1)); "
            f"if (regs.b == 0) {{ step_ = {skip(5)}; return true; }}"
        ),
        3: lambda y, z, p, q, i: BLOCK_REPEAT_REWIND,
    },
    "OUTI": {
        1: lambda y, z, p, q, i: "regs.b = uint8_t(regs.b - 1);",
        2: lambda y, z, p, q, i: (
            "regs.wz = uint16_t(regs.bc() + 1); "
            "regs.f = alu::outi_outd_flags(regs.b, dlatch_, regs.l);"
        ),
    },
    "OUTD": {
        1: lambda y, z, p, q, i: "regs.b = uint8_t(regs.b - 1);",
        2: lambda y, z, p, q, i: (
            "regs.wz = uint16_t(regs.bc() - 1); "
            "regs.f = alu::outi_outd_flags(regs.b, dlatch_, regs.l);"
        ),
    },
    "OTIR": {
        1: lambda y, z, p, q, i: "regs.b = uint8_t(regs.b - 1);",
        2: lambda y, z, p, q, i, skip: (
            "regs.wz = uint16_t(regs.bc() + 1); "
            "regs.f = alu::outi_outd_flags(regs.b, dlatch_, regs.l); "
            f"if (regs.b == 0) {{ step_ = {skip(5)}; return true; }}"
        ),
        3: lambda y, z, p, q, i: BLOCK_REPEAT_REWIND,
    },
    "OTDR": {
        1: lambda y, z, p, q, i: "regs.b = uint8_t(regs.b - 1);",
        2: lambda y, z, p, q, i, skip: (
            "regs.wz = uint16_t(regs.bc() - 1); "
            "regs.f = alu::outi_outd_flags(regs.b, dlatch_, regs.l); "
            f"if (regs.b == 0) {{ step_ = {skip(5)}; return true; }}"
        ),
        3: lambda y, z, p, q, i: BLOCK_REPEAT_REWIND,
    },
    # LD r,n / LD (HL),n / LD $RP,nn / LD (nn),HL / LD HL,(nn) / LD (nn),$RP /
    # LD $RP,(nn) / PUSH / POP -- no `action` text at all, pure data movement
    # fully handled by the generic dst/ab/db substitution.
    "LD $RY,n": None,
    "LD (HL),n": None,
    "LD $RP,nn": None,
    "LD (nn),HL": None,
    "LD HL,(nn)": None,
    "LD (nn),$RP": None,
    "LD $RP,(nn)": None,
    "POP $RP2": None,
    "PUSH $RP2": None,
    "INC $RP": lambda y, z, p, q, i: rp_set_stmt_hlx(
        p, True, f"uint16_t({rp_read_expr(p, True)} + 1)"
    ),
    "DEC $RP": lambda y, z, p, q, i: rp_set_stmt_hlx(
        p, True, f"uint16_t({rp_read_expr(p, True)} - 1)"
    ),
    "JP nn (target)": None,  # placeholder, unused (JP nn handled above)
    # CB-prefix payload steps (see SPECIAL_BUT_HANDLED) -- `z`/`x`/`y` here
    # come from the CB-suffix opcode itself (opcode_, latched by the
    # hand-written CB fetch machine cycle in z80.cpp), NOT from this op's own
    # generation-time y/z/p/q (which are meaningless here: these two entries
    # aren't enumerated per-opcode the normal way).
    #
    # cb_action returns false for BIT, which writes nothing back -- hence the
    # out-parameter rather than a plain return value.
    "cb": lambda y, z, p, q, i: (
        "uint8_t cb_z = uint8_t(opcode_ & 7); "
        "uint8_t cb_val = get_reg8_plain(cb_z); "
        "uint8_t cb_out; "
        "if (cb_action(cb_val, false, &cb_out)) { set_reg8_plain(cb_z, cb_out); }"
    ),
    "cbhl": {
        0: lambda y, z, p, q, i, skip: (
            "uint8_t cb_out; "
            "if (cb_action(dlatch_, true, &cb_out)) { dlatch_ = cb_out; } "
            f"else {{ step_ = {skip(3)}; return true; }}"
        ),
    },
}


def get_action(name: str, mcycle_index: int, y: int, z: int, p: int, q: int,
               skip, is_post: bool = False) -> str | None:
    entry = ACTIONS.get(name)
    if entry is None:
        return None
    if callable(entry):
        # A plain-callable ACTIONS entry means "the action for this op's one
        # real (non-auto-appended-overlapped) mcycle" -- mci 0. Anything else
        # (the auto-appended trailing overlapped, or a `post_action` query)
        # genuinely has no action here.
        if mcycle_index != 0 or is_post:
            return None
        return entry(y, z, p, q, mcycle_index)
    key = "post" if is_post else mcycle_index
    fn = entry.get(key)
    if fn is None:
        return None
    try:
        return fn(y, z, p, q, mcycle_index, skip)
    except TypeError:
        return fn(y, z, p, q, mcycle_index)


# ============================================================================
# ab / db / dst simple-token substitution (mirrors z80_gen.py's map_cpu, but
# only the small set of tokens actually used unprefixed/ED in this file --
# and unlike map_cpu, increment/decrement forms need dedicated Cpu helper
# methods since Rust has no lvalue-expression `x++`).
# ============================================================================

def addr_expr(tok: str, y: int, z: int, p: int, q: int) -> str:
    table = {
        "$ADDR": "addr_",
        "$PC++": "pc_post_inc()",
        "$BC": "regs.bc()",
        "$DE": "regs.de()",
        "$SP": "regs.sp",
        "$SP++": "sp_post_inc()",
        "$SP+1": "uint16_t(regs.sp + 1)",
        "--$SP": "sp_pre_dec()",
        "$WZ": "regs.wz",
        "$WZ++": "wz_post_inc()",
        "cpu->hl": "regs.hl()",
        "cpu->hl++": "hl_post_inc()",
        "cpu->hl--": "hl_post_dec()",
        "cpu->de++": "de_post_inc()",
        "cpu->de--": "de_post_dec()",
    }
    if tok in table:
        return table[tok]
    raise ValueError(f"unhandled address expression: {tok!r}")


def data_read_expr(tok: str, y: int, z: int, p: int, q: int) -> str:
    if tok == "$DLATCH":
        return "dlatch_"
    # $H/$L (bare, unlike $RRY/$RRZ) ARE substitutable in the YAML -- used
    # only by "LD (nn),HL"/"LD HL,(nn)"/"EX (SP),HL" (all p==2-fixed,
    # unprefixed), and real DD/FD-prefixed forms of those (LD (nn),IX,
    # EX (SP),IX, ...) really do read/write IXH/IXL. Verified directly
    # against z80.h (case 607/610 use cpu->hlx[cpu->hlx_idx].l/.h).
    if tok == "$H":
        return "hlx_h()"
    if tok == "$L":
        return "hlx_l()"
    plain_regs = {"$A": "a", "$B": "b", "$C": "c", "$D": "d", "$E": "e"}
    if tok in plain_regs:
        return f"regs.{plain_regs[tok]}"
    if tok == "$RRZ":
        return R[z]
    if tok == "$RRY":
        return R[y]
    if tok == "$PCH":
        return "uint8_t(regs.pc >> 8)"
    if tok == "$PCL":
        return "uint8_t(regs.pc)"
    if tok == "$RP2H":
        return "hlx_h()" if p == 2 else RP2_HIGH[p]
    if tok == "$RP2L":
        return "hlx_l()" if p == 2 else RP2_LOW[p]
    if tok == "$RRPH":
        return RP_HIGH[p]
    if tok == "$RRPL":
        return RP_LOW[p]
    if tok == '"0"' or tok == 0:
        return "0"
    raise ValueError(f"unhandled data-read expression: {tok!r}")


def dest_write_expr(tok: str, y: int, z: int, p: int, q: int) -> str:
    """Returns either a C++ lvalue expression (assignable with `= value;`)
    or one of the `__XXX__` sentinels `emit_dest_assign` special-cases (for
    targets that need a setter *call*, not a plain field), for an `mread`'s
    `dst` field. `$RY == 6` ((HL)) never occurs among the ops this
    generator handles (they route through $DLATCH instead)."""
    if tok == "$DLATCH":
        return "dlatch_"
    if tok == "$RY":
        # Substitutable (LD $RY,n, e.g. -- DD-prefixed LD H,n really means
        # LD IXH,n).
        if y == 4:
            return "__HLXH__"
        if y == 5:
            return "__HLXL__"
        return R[y]
    if tok == "$RRY":
        return R[y]  # never substituted -- see z80_desc.yml's own note
    if tok == "$H":
        return "__HLXH__"
    if tok == "$L":
        return "__HLXL__"
    plain_regs = {"$A": "a", "$B": "b", "$C": "c", "$D": "d", "$E": "e"}
    if tok in plain_regs:
        return f"regs.{plain_regs[tok]}"
    if tok == "$WZL":
        return "__WZL__"  # handled specially, see emit_mread
    if tok == "$WZH":
        return "__WZH__"
    if tok == "$RPL":
        # Substitutable (LD $RP,nn -- DD-prefixed LD HL,nn really means
        # LD IX,nn).
        if p == 2:
            return "__HLXL__"
        return RP_LOW[p] if p != 3 else "__SPL__"
    if tok == "$RPH":
        if p == 2:
            return "__HLXH__"
        return RP_HIGH[p] if p != 3 else "__SPH__"
    if tok == "$RP2L":
        # Substitutable (POP $RP2 -- DD-prefixed POP HL really means POP IX).
        if p == 2:
            return "__HLXL__"
        return RP2_LOW[p]
    if tok == "$RP2H":
        if p == 2:
            return "__HLXH__"
        return RP2_HIGH[p]
    if tok == "$RRPL":
        return RP_LOW[p] if p != 3 else "__SPL__"
    if tok == "$RRPH":
        return RP_HIGH[p] if p != 3 else "__SPH__"
    raise ValueError(f"unhandled dest-write token: {tok!r}")


def emit_dest_assign(tok: str, y: int, z: int, p: int, q: int) -> str:
    target = dest_write_expr(tok, y, z, p, q)
    if target == "__WZL__":
        return "regs.set_wzl(get_data(pins));"
    if target == "__WZH__":
        return "regs.set_wzh(get_data(pins));"
    if target == "__SPL__":
        return "regs.set_spl(get_data(pins));"
    if target == "__SPH__":
        return "regs.set_sph(get_data(pins));"
    if target == "__HLXH__":
        return "set_hlx_h(get_data(pins));"
    if target == "__HLXL__":
        return "set_hlx_l(get_data(pins));"
    return f"{target} = get_data(pins);"


# ============================================================================
# Step/code generation, mirroring z80_gen.py's gen_decoder(): each mcycle
# type expands into a fixed sequence of T-states. Unlike the first draft of
# this generator, step NUMBERS for an entire op are assigned in one flat
# pass over every T-state up front (dispatch_index for the first, then
# Generator.alloc() for every other one, including the trailing
# `overlapped` T-state) -- this is the fix for a real bug caught before
# ever running it: allocating the "next step after this mcycle" lazily,
# without reserving it via alloc(), let a later op's alloc() call hand out
# the SAME number again, silently colliding two different opcodes' code
# onto one match arm.
# ============================================================================

class TState:
    """One HALF-T-state (one generated switch case) within a single
    instruction. `kind` selects which template `render()` uses; `number` is
    assigned by Generator.gen_op(), not at construction time.

    `tindex` is the ordinal of the whole T-state this half belongs to, within
    the op. It exists only so a repeating block instruction's "skip the
    rewind mcycle" jump can be resolved structurally (see gen_op) rather than
    by a hardcoded step offset, which no longer survives the half-T split."""

    def __init__(self, kind: str, tindex: int, **kw):
        self.kind = kind
        self.tindex = tindex
        self.kw = kw
        self.number: int | None = None


def build_tstates(op: Op) -> list[TState]:
    """Flattens one op's `mcycles` into its exact per-HALF-T-state sequence.
    An `overlapped` mcycle is auto-appended if the op doesn't already end
    with one, mirroring parse_opdescs()'s own `num_overlapped == 0` check.

    Every T-state becomes two half-states, H then L, following real Z80 bus
    timing: the address bus goes valid on H, control lines assert on L, and
    WAIT is sampled on L. See z80.h's header comment for why that split is
    the entire point of this rewrite -- it is what makes the "address valid,
    MREQ not yet asserted" window the ULA contends on actually exist.

    The one exception is `overlapped`, which is a single half-state: it IS
    T1H of the next instruction's M1 fetch (that is what the overlapped
    fetch means), and T1L of that fetch is hand-written as STEP_M1_T1L."""
    mcycles = list(op.mcycles)
    if not any(mc["type"] == "overlapped" for mc in mcycles):
        mcycles = mcycles + [{"type": "overlapped"}]

    tstates: list[TState] = []
    # Counts whole T-states as they're emitted, so each half can record which
    # T-state it belongs to.
    t_ord = 0

    def emit(kind: str, **kw) -> None:
        tstates.append(TState(kind, t_ord, **kw))

    def emit_idle_tstate() -> None:
        nonlocal t_ord
        emit("idle")
        emit("idle")
        t_ord += 1

    for mci, mc in enumerate(mcycles):
        t = mc["type"]
        if t == "mread":
            # T1H places the real target address on the bus with NO control
            # bits -- this is the contention window. It is also the ONE place
            # "ab" is evaluated: several "ab" tokens ($PC++, cpu->hl++, ...)
            # are side-effecting post-increments, so every later half-state
            # reuses get_addr(pins) instead of re-running the expression.
            tcycles = mc.get("tcycles", MEM_TCYCLES)
            emit("mread_t1h", ab=mc["ab"])
            emit("mread_t1l")
            t_ord += 1
            emit("idle")
            emit("mread_t2l_wait")
            t_ord += 1
            emit("idle")
            emit("mread_t3l_latch", dst=mc["dst"], mci=mci)
            t_ord += 1
            for _ in range(3, tcycles):
                emit_idle_tstate()
        elif t == "mwrite":
            # Same T1H address-first reasoning as mread. MREQ asserts at T1L,
            # the data goes on the bus at T2H, and WR only asserts at T2L --
            # matching the real chip, where WR deliberately trails MREQ so the
            # data bus has settled before the write strobe.
            tcycles = mc.get("tcycles", MEM_TCYCLES)
            emit("mwrite_t1h", ab=mc["ab"])
            emit("mwrite_t1l")
            t_ord += 1
            emit("mwrite_t2h_data", db=mc["db"])
            emit("mwrite_t2l_wait", mci=mci)
            t_ord += 1
            emit("idle")
            emit("mwrite_t3l_end")
            t_ord += 1
            for _ in range(3, tcycles):
                emit_idle_tstate()
        elif t == "ioread":
            # An I/O cycle is 4 T-states because the Z80 always inserts one
            # wait state (TW) between T2 and T3. IORQ asserts at T2H (not T1L
            # like MREQ) -- the extra half-cycle of address setup is a real
            # difference between the memory and I/O cycles on this chip.
            tcycles = mc.get("tcycles", IO_TCYCLES)
            emit("ioread_t1h", ab=mc["ab"])
            emit("idle")
            t_ord += 1
            emit("ioread_t2h_assert")
            emit("idle")
            t_ord += 1
            emit("idle")
            emit("ioread_tw_l_wait")
            t_ord += 1
            emit("idle")
            emit("ioread_t3l_latch", dst=mc["dst"], mci=mci)
            t_ord += 1
            for _ in range(4, tcycles):
                emit_idle_tstate()
        elif t == "iowrite":
            tcycles = mc.get("tcycles", IO_TCYCLES)
            emit("iowrite_t1h", ab=mc["ab"])
            emit("idle")
            t_ord += 1
            emit("iowrite_t2h_assert", db=mc["db"])
            emit("idle")
            t_ord += 1
            emit("idle")
            emit("iowrite_tw_l_wait")
            t_ord += 1
            emit("idle")
            emit("iowrite_t3l_end", mci=mci)
            t_ord += 1
            for _ in range(4, tcycles):
                emit_idle_tstate()
        elif t == "generic":
            # An internal cycle: no bus activity at all. The action fires on
            # the L half, not the H half, so that EVERY action site in this
            # generator sits on an L half (mread latch, mwrite write, io
            # latch/end are all L too).
            #
            # That uniformity is load-bearing, not cosmetic. A forward branch
            # taken by an action jumps to the target T-state's H half; if the
            # action itself sat on an H half, the jump would skip its own
            # T-state's L half and the instruction would come out half a
            # T-state short. Caught by the differential test's timing check
            # on LDIR's non-repeating exit (15.5 T against the reference's
            # 16), which is exactly the kind of thing register comparison
            # alone would never have noticed.
            emit("idle")
            emit("generic", mci=mci)
            t_ord += 1
            for _ in range(1, mc["tcycles"]):
                emit_idle_tstate()
        elif t == "overlapped":
            # One half-state only -- see this function's own doc comment.
            emit("overlapped", mci=mci, prefix=mc.get("prefix"))
            t_ord += 1
        else:
            raise ValueError(f"{op.name}: unhandled mcycle type {t!r}")
    if tstates[-1].kind != "overlapped":
        raise ValueError(f"{op.name}: internal error, didn't end on 'overlapped'")
    return tstates


class Generator:
    def __init__(self):
        self.cur_extra_step = EXTRA_STEP_BASE
        self.arms: list[str] = []

    def alloc(self) -> int:
        s = self.cur_extra_step
        self.cur_extra_step += 1
        return s

    def gen_op(self, dispatch_index: int | None, op: Op, y: int, z: int, p: int, q: int) -> int:
        """Returns the step number assigned to this op's first half-T-state --
        `dispatch_index` when given explicitly (the main 0..512 opcode
        table), otherwise a freshly `alloc()`'d one (used for standalone
        entries like `cb`/`cbhl` that aren't part of that table but still
        need a real, collision-free step number for hand-written code
        elsewhere to jump to)."""
        tstates = build_tstates(op)
        tstates[0].number = dispatch_index if dispatch_index is not None else self.alloc()
        for ts in tstates[1:]:
            ts.number = self.alloc()

        for i, ts in enumerate(tstates):
            # $NEXTSTEP == this half-state's own natural successor (its
            # `_goto()` target if nothing branches early) -- well-defined
            # for every kind except the last (always 'overlapped', which
            # dispatches via begin_fetch()/begin_fetch_ed() instead of a
            # plain `step_ = next`).
            nxt = tstates[i + 1].number if i + 1 < len(tstates) else None
            # A callable, not a number: the forward-branch distance differs
            # per instruction (5 for the block/relative-jump forms, 6 for
            # RET cc, 7 for CALL cc, 3 for the CB (HL) form), and the action
            # is what knows which applies.
            skip = (lambda idx: lambda k: self.skip_target(tstates, idx, k))(i)
            body = self.render(ts, nxt, skip, op, y, z, p, q)
            self.arms.append(f"        case {ts.number}: {{\n{body}\n        }}")

        return tstates[0].number

    @staticmethod
    def skip_target(tstates: list[TState], i: int, k: int) -> int:
        """Where a forward-branching instruction jumps when it takes the
        "don't do the rest of this" path -- a conditional RET/CALL/JR that
        wasn't taken, or a repeating block instruction that has finished and
        must skip its PC-rewind mcycle.

        The whole-T-state generator wrote this as a raw step offset,
        `nextstep + k`, which worked only because step numbers were assigned
        one per T-state in order. That stopped being true once each T-state
        became two half-states (with `overlapped` the lone one-half
        exception), so the same arithmetic would now land mid-mcycle.

        Resolved structurally instead: `k` still means what it always meant,
        "k T-states past this action's own next T-state", and this looks up
        the half-state that actually starts there. A layout change that
        breaks the assumption raises here rather than silently generating a
        jump into the middle of the wrong machine cycle."""
        target_tindex = tstates[i].tindex + 1 + k
        for ts in tstates:
            if ts.tindex == target_tindex:
                return ts.number
        raise ValueError(
            f"skip target T-state {target_tindex} (this T-state + 1 + {k}) does not "
            f"exist -- the op has only {tstates[-1].tindex + 1} T-states"
        )

    def render(self, ts: TState, nxt: int | None, skip: int | None,
               op: Op, y: int, z: int, p: int, q: int) -> str:
        """Emits the C++ body of one half-T-state's switch case.

        Every case ends by setting `step_` and returning true, except the
        WAIT-check halves (which return WITHOUT advancing `step_`, so the
        same half re-runs until WAIT clears) and `overlapped` (where
        begin_fetch* sets `step_` itself)."""
        goto = f"            step_ = {nxt};\n            return true;"

        if ts.kind == "idle":
            return goto

        # ---- memory read -------------------------------------------------
        if ts.kind == "mread_t1h":
            # The contention window: address valid, no control lines yet.
            # Also the ONE place "ab" is evaluated, so a side-effecting token
            # ($PC++, cpu->hl++) fires exactly once -- every later half reuses
            # get_addr(pins) rather than re-running the expression.
            addr = addr_expr(ts.kw["ab"], y, z, p, q)
            return f"            pins = set_addr(pins, {addr});\n{goto}"
        if ts.kind == "mread_t1l":
            return f"            pins = set_addr_assert(pins, get_addr(pins), MREQ | RD);\n{goto}"
        if ts.kind == "mread_t2l_wait":
            return f"            if (asserted(pins, WAIT)) {{ return true; }}\n{goto}"
        if ts.kind == "mread_t3l_latch":
            dest = emit_dest_assign(ts.kw["dst"], y, z, p, q)
            action = get_action(op.name, ts.kw["mci"], y, z, p, q, skip)
            body = f"            {dest}\n"
            if action:
                body += f"            {action}\n"
            body += "            pins = release_pins(pins, MREQ | RD);\n"
            return body + goto

        # ---- memory write --------------------------------------------------
        if ts.kind == "mwrite_t1h":
            addr = addr_expr(ts.kw["ab"], y, z, p, q)
            return f"            pins = set_addr(pins, {addr});\n{goto}"
        if ts.kind == "mwrite_t1l":
            return f"            pins = set_addr_assert(pins, get_addr(pins), MREQ);\n{goto}"
        if ts.kind == "mwrite_t2h_data":
            # Data is evaluated here, its first and only evaluation (T1H
            # placed the address only). Confirmed that no "db" token used by
            # any real mwrite entry is side-effecting.
            db_tok = ts.kw["db"]
            data = "0" if db_tok in ("0", 0) else data_read_expr(db_tok, y, z, p, q)
            return f"            pins = set_data(pins, {data});\n{goto}"
        if ts.kind == "mwrite_t2l_wait":
            # WR trails MREQ by a half-cycle, as on the real chip: the data
            # bus has to settle before the write strobe.
            action = get_action(op.name, ts.kw["mci"], y, z, p, q, skip)
            body = "            if (asserted(pins, WAIT)) { return true; }\n"
            body += "            pins = assert_pins(pins, WR);\n"
            if action:
                body += f"            {action}\n"
            return body + goto
        if ts.kind == "mwrite_t3l_end":
            return f"            pins = release_pins(pins, MREQ | WR);\n{goto}"

        # ---- I/O read ------------------------------------------------------
        if ts.kind == "ioread_t1h":
            addr = addr_expr(ts.kw["ab"], y, z, p, q)
            return f"            pins = set_addr(pins, {addr});\n{goto}"
        if ts.kind == "ioread_t2h_assert":
            # IORQ asserts a half-cycle later than MREQ would -- a real
            # difference between this chip's memory and I/O cycles, not a
            # transcription slip.
            return f"            pins = set_addr_assert(pins, get_addr(pins), IORQ | RD);\n{goto}"
        if ts.kind == "ioread_tw_l_wait":
            return f"            if (asserted(pins, WAIT)) {{ return true; }}\n{goto}"
        if ts.kind == "ioread_t3l_latch":
            dest = emit_dest_assign(ts.kw["dst"], y, z, p, q)
            action = get_action(op.name, ts.kw["mci"], y, z, p, q, skip)
            body = f"            {dest}\n"
            if action:
                body += f"            {action}\n"
            body += "            pins = release_pins(pins, IORQ | RD);\n"
            return body + goto

        # ---- I/O write -----------------------------------------------------
        if ts.kind == "iowrite_t1h":
            addr = addr_expr(ts.kw["ab"], y, z, p, q)
            return f"            pins = set_addr(pins, {addr});\n{goto}"
        if ts.kind == "iowrite_t2h_assert":
            db_tok = ts.kw["db"]
            data = "0" if db_tok in ("0", 0) else data_read_expr(db_tok, y, z, p, q)
            return (f"            pins = set_addr_data_assert(pins, get_addr(pins), {data}, IORQ | WR);\n"
                    f"{goto}")
        if ts.kind == "iowrite_tw_l_wait":
            return f"            if (asserted(pins, WAIT)) {{ return true; }}\n{goto}"
        if ts.kind == "iowrite_t3l_end":
            action = get_action(op.name, ts.kw["mci"], y, z, p, q, skip)
            body = ""
            if action:
                body += f"            {action}\n"
            body += "            pins = release_pins(pins, IORQ | WR);\n"
            return body + goto

        # ---- internal cycle -------------------------------------------------
        if ts.kind == "generic":
            action = get_action(op.name, ts.kw["mci"], y, z, p, q, skip)
            body = f"            {action}\n" if action else ""
            return body + goto

        # ---- overlapped fetch of the next instruction -----------------------
        if ts.kind == "overlapped":
            mci = ts.kw["mci"]
            action = get_action(op.name, mci, y, z, p, q, None)
            post_action = get_action(op.name, mci, y, z, p, q, None, is_post=True)
            body = f"            {action}\n" if action else ""
            prefix = ts.kw.get("prefix")
            if prefix == "ed":
                body += "            pins = begin_fetch_ed(pins);\n            return true;"
            elif prefix is not None:
                # Any other prefix value (cb/dd/fd) means this op should have
                # been excluded via SKIP_NAMES instead. Falling through to a
                # plain begin_fetch() here previously caused a real, silent
                # bug (see SKIP_NAMES' own comment) -- the prefix byte got
                # treated as a harmless no-op rather than failing loudly.
                raise ValueError(
                    f"{op.name}: unhandled prefix {prefix!r} -- add it to SKIP_NAMES "
                    f"until real dispatch for it exists, don't let it fall through silently"
                )
            else:
                body += "            pins = begin_fetch(pins);\n"
                if post_action:
                    body += f"            {post_action}\n"
                body += "            return true;"
            return body
        raise ValueError(f"unhandled T-state kind {ts.kind!r}")


def generate() -> str:
    ops = parse_opdescs()
    table = enumerate_opcodes(ops)

    gen = Generator()
    for idx in sorted(table):
        op, y, z, p, q = table[idx]
        gen.gen_op(idx, op, y, z, p, q)

    # CB-prefix payload steps: not part of the 0..512 opcode table (they're
    # dispatched into by z80.cpp's hand-written CB fetch machine cycle, which
    # decides between them based on the CB-suffix opcode's own z field), so
    # they get fresh alloc()'d step numbers instead of a fixed dispatch_index
    # -- exported below as named constants so hand-written code can reference
    # them without hardcoding magic numbers.
    cb_step = gen.gen_op(None, find_op(ops, "cb"), 0, 0, 0, 0)
    cbhl_step = gen.gen_op(None, find_op(ops, "cbhl"), 0, 0, 0, 0)

    body = "\n".join(gen.arms)
    return f"""\
// GENERATED FILE -- do not edit by hand.
// Produced by scripts/generate_z80_dispatch.py from vendor/chips/z80_desc.yml.
// Regenerate with: python scripts/generate_z80_dispatch.py
//
// Included directly into the body of Z80::dispatch_generated() in z80.cpp,
// which supplies the enclosing switch and the `pins` reference. Not a
// standalone translation unit -- it needs that function's scope.
//
// One switch case per HALF-T-state: every T-state is two cases, H then L
// (address valid on H, control lines assert on L). See z80.h's header
// comment for why that split exists.

/// Step number for the CB-prefix register-direct payload ("cb" in
/// z80_desc.yml) -- the hand-written CB fetch machine cycle jumps straight
/// here, not through the 0..512 opcode table.
#define ZX_CB_STEP {cb_step}
/// Same, for the "(HL)" form ("cbhl" in z80_desc.yml).
#define ZX_CBHL_STEP {cbhl_step}

{body}
"""


def main():
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(generate(), encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
