; Knight Lore 128K. Where everything goes, bank by bank:
;
;   bank 5, $4000   the screen; the room builder at $5B00; the room templates,
;                   the tables and the cold code (the menu, the end screens)
;                   from $6000; the view buffer, the object pool and the
;                   aligned tables from $7400
;   bank 2, $8000   the code that runs every turn, the rotation arena, and the
;                   stack at the top, below $C000
;   bank 0, $C000   the room page, paged in for the whole of play: the
;                   resident sprites, then the room being played's own
;   bank 4, $C000   the rooms, and what each loads into the room page; paged
;                   in only while a room is looked up and loaded
;   bank 1, $C000   the library: the sprites loaded room by room (3 and 7
;                   follow when it outgrows one bank)
;
; Banks 3, 6 and 7 are empty so far. ../engine/memory-128k.md is the plan for
; them, and README.md says how far it has got. The device's default mapping is
; the 128K's own at power-on -- banks 5, 2 and 0 -- and everything is
; assembled into it except the rooms and the library, which MMU puts in their
; own banks.
					DEVICE ZXSPECTRUM128


					ORG	0x8000

; The view buffer is a window, not a screen: everything that intersects the
; area a moved object disturbed is composited here, then copied out in one
; go. Its shape is therefore the hard limit on how big a single object can
; be, and both dimensions have to clear the whole sprite set:
;
;   widest sprite   5 bytes, and a sprite that is not byte-aligned spans one
;                   column more than its own width -- so 6 columns
;   tallest sprite  64 rows (the castle door arch; the forest one is 52)
;
; 8 x 64 = 512 bytes covers both with the stride a power of two, which is
; what makes the row address a shift rather than a multiply. Six would be
; tight enough to work and no cheaper: 6 x 64 is 384, still over a page, so
; the second page has to be handled either way, and the multiply-by-6 costs
; more than the multiply-by-8 saves. The padding from the sprite's width out
; to the stride is what the extra two columns actually cost -- see the row
; advance in sprite_blit.
VIEW_BUF_WIDTH		EQU		8

; The buffer spans two pages, so the blit cannot address it with `ld d,high
; view_buffer` plus `inc e` throughout. Rows are 8 bytes on an 8-byte
; boundary, so no row straddles the page break and only the increments that
; can land on a row boundary have to carry into D -- which is the last one
; of each row, plus the row advance itself. Everything inside a row stays
; `inc e`. Knight Lore has no limit of this kind at all, because its buffer
; IS the screen; ours is a small window, and this is what that costs.
VIEW_BUF_ROWS		EQU		512 / VIEW_BUF_WIDTH

; The stack, in UNCONTENDED memory. Whatever loaded the game leaves SP where
; its own stack was -- 0x5D56, in the .sna this used to be built as -- which is
; inside the ULA-contended 0x4000-0x7FFF window, so on real hardware
; every call and return there pays a contention delay -- a few hundred
; T-states a frame for nothing. Everything that runs every turn lives above
; 0x8000 -- the code, the sprite data and the rotate table -- and what sits
; below it is read rarely or is cheap to reach: see the regions further down.
;
; It starts at the top of bank 2 -- SP = $C000, so the first push lands at
; $BFFE -- and STACK_RESERVE is kept clear below it. On the 48K it was at the
; very top of memory. On the 128K that is the bank that pages, and a RET with
; another bank in would read its address from that bank.
;
; The reserve is measured, not guessed: the bytes below the stack are filled
; with a pattern, the game is played through the rooms with everything in them
; moving -- the pot, a portcullis, collapsing blocks, pickups, a death, a
; change of light and a new game -- and the untouched bytes counted afterwards.
; That says 34, where it said 26 before the sounds and the panel, which nest
; deeper. Anything that adds to the deepest call chain wants re-measuring.
STACK_TOP			EQU		0xC000
STACK_RESERVE		EQU		48		; 34 used, 14 spare

; ---------------------------------------------------------------------------
; The castle's tables, in contended memory.
;
; The pixel adjustments Knight Lore's own code would have computed, and the
; tables that go with the panel, the font and the charms. The rooms themselves
; are in bank 4, and the templates they are built from in bank 0 -- see the
; foot of this file. Little of it is touched except when a room is built, so
; it costs nothing to leave it where the ULA fights the CPU for it -- which is
; also where the game itself kept it.
;
; room_data.s is generated by rooms_source.py from rooms.json, specials_gen.s
; by specials_source.py from specials.json, and sprite_adj_gen.s by
; sprite_source.py from graphic_map.json, whose nudges adj.py harvests from a
; running game. None of them is hand-written; all three read the JSON the
; repository carries, not the packed files kl_extract.py first pulled them
; out of.
                    ORG     $6000
                    INCLUDE "panel_data.s"
                    INCLUDE "sprite_adj_gen.s"
                    INCLUDE "graphics_gen.s"   ; GFX_* -- generated from graphics.json

; The game's own font: forty 8x8 characters, which is all the text Knight Lore
; has. Digits first and then letters, no lower case and no punctuation beyond
; what a word needs -- so a hex digit is its own character index and needs no
; translating, which is the whole of why printing a room number is six
; instructions. kl_extract.py pulls it from $6108, immediately in front of the
; room tables; the game's own object walk uses it as the end of its object
; table for the same reason.
;
; font.s is generated from the font sheet, font.png and font.json, which is
; where the artwork lives -- see font_sheet.py and font_source.py. It opens
; the label `font` that print_char reaches for.
                    INCLUDE "font.s"

; The collectables: where each of the thirty-two starts, the order the wizard
; wants them in, and which graphic each row has been dealt -- see special.s.
; kl_extract.py pulls the first two out of the game, as it does the font, and
; specials_source.py turns specials.json back into assembler. All four labels
; come out of that one file: the two that hold data and the two that only
; reserve room, because special_init copies the first over the second in one
; LDIR and nothing may come between them.
                    INCLUDE "specials_gen.s"

; The one buffer every deferred rotation goes through, moved down here for the
; same reason -- see shift.s for what it is and how it is sized.
shift_shared:       DS      SHIFT_SHARED_SIZE

; The sound effects, which only choose what to play -- see sound.s.
                    INCLUDE "sound_fx.s"
                    INCLUDE "monster_gate.s"    ; where the trimmed index left room

; Looking a room up in bank 4, and the paging it needs.
                    INCLUDE "room_find.s"
                    INCLUDE "room_page.s"
                    INCLUDE "page.s"

; The busy rule, which sits monsters out in a crowded room. It was in the space
; the trimmed sprite table left at $7F00 on the 48K; with Pentagram's graphics
; the table runs to 242 entries and fills that, and this is the same bank.
                    INCLUDE "busy.s"            ; its numbers, then the engine's own
                    INCLUDE "../engine/busy.s"

; The sun and the moon in their window. They move when the clock ticks, one turn
; in eight, and are redrawn when a redraw reaches the window -- not every turn,
; so this is where they went when Pentagram's movers filled bank 2.
                    INCLUDE "sun.s"

room_data_end:
                    ; The menu and the end screens follow on from here -- see
                    ; cold_start, below the code.

                    ORG     $8000

					INCLUDE "../engine/sprite.s"
					INCLUDE "../engine/object.s"
					INCLUDE "../engine/depth.s"
					INCLUDE "../engine/shift.s"
					INCLUDE "../engine/walker.s"
					INCLUDE "knight.s"
					INCLUDE "movers.s"
					INCLUDE "../engine/mover.s"
					INCLUDE "shared_movers.s"		; what it gives the next
					INCLUDE "../engine/movers.s"		; the behaviours shared with Pentagram
					INCLUDE "special.s"
					INCLUDE "../engine/sound.s"
					INCLUDE "panel.s"
					INCLUDE "input.s"		; its keys and its bits, then
					INCLUDE "../engine/input.s"		; the sticks, which are nobody's

; The view buffer and the object pool used to sit here, at the top of the
; image. They are reserved at the foot of this file instead, in the gap between
; the room data and the code -- see there for why.

					INCLUDE "main.s"
					INCLUDE "../engine/turn.s"
					INCLUDE "player.s"
					INCLUDE "../engine/redraw.s"
					INCLUDE "overlay.s"	; redraw_view falls into it
					INCLUDE "../engine/vid_buff.s"



; The stack grows down from the top of bank 2, so the code has to stop short of
; what it reserves there. This is the check that was missing when the player
; pushed the top of the image into the stack.
image_end:
                    ASSERT  $ <= STACK_TOP - STACK_RESERVE
                    DISPLAY "code            $8000..", /H, image_end, "   free below the stack: ", /D, STACK_TOP - STACK_RESERVE - image_end

; ---------------------------------------------------------------------------
; Code that runs between games rather than during one: the end screens and
; their tunes, what plays the tunes, and the menu. It was up with the rest of
; the code on the 48K. On the 128K that space went to the stack, and this is
; cold enough not to mind contended memory, so it goes on the end of the data
; in the $6000 region. It is assembled down here, after the engine, because
; menu.s uses sprite_width_class, a macro engine/sprite.s brings in.
                    ORG     room_data_end
cold_start:
                    INCLUDE "end.s"             ; its tunes and their notes, then
                    INCLUDE "../engine/tune.s"  ; what plays them
                    INCLUDE "menu.s"
                    INCLUDE "end_at.s"          ; where both of them put a character
cold_end:
                    ASSERT  cold_end <= $7400   ; clear of the view buffer
                    DISPLAY "data, cold code $6000..", /H, cold_end, "   free: ", /D, $7400 - cold_end

; ---------------------------------------------------------------------------
; The room page, in bank 0 at $C000: the bank that stays paged in for the whole
; of play, since every turn draws from it. Bank 0 is uncontended on every 128K
; model, the +2A and +3 included. The resident sprites are assembled into it
; for good; room_page, after them, is where each room's own are loaded -- see
; room_page.s.
                    ORG     $C000
sprite_start:
					INCLUDE "sprite_data.s"
sprite_end:

; The templates every room is built from, and the tables that go with them. They
; were in the $6000 region; Pentagram's doubled them, and that region is full.
; Bank 0 is paged in all the time a room is being built and played, and nothing
; reads a template while room_find or room_page_fill has another bank in, so
; they can sit here, ahead of the room page. If the page runs short, the plan's
; next step is to copy only the templates a room names out of bank 4, as
; room_find copies its record -- see ../engine/memory-128k.md.
                    INCLUDE "room_data.s"
room_templates_end:
                    ALIGN   4
room_page:
                    ASSERT  room_page + ROOM_PAGE_MOST <= $10000
                    DISPLAY "room page, bank 0: resident to ", /H, room_page, ", the fullest room to ", /H, room_page + ROOM_PAGE_MOST, "   free: ", /D, $10000 - room_page - ROOM_PAGE_MOST

; ---------------------------------------------------------------------------
; The rooms, in bank 4 at $C000. Only room_find reads them, with bank 4 paged
; in for as long as it takes to copy one record out -- see room_find.s.
                    MMU     3, ROOM_BANK, $C000
                    INCLUDE "room_list.s"
                    INCLUDE "room_sprites.s"    ; what each room loads -- see room_page.s
room_list_end:
                    DISPLAY "rooms, bank 4   $C000..", /H, room_list_end, "   free: ", /D, $10000 - room_list_end

; The library, from bank 1 on: the sprites rooms load. sprite_library.s pages
; each bank in for itself, and leaves bank 0 in.
                    INCLUDE "sprite_library.s"
                    MMU     3, PAGE_PLAY

; ---------------------------------------------------------------------------
; Building a room, down where the ROM keeps its system variables.
;
; $5B00 to $5FFF is the printer buffer and the system variables, and none of it
; is wanted: interrupts are off for good, nothing here calls the ROM, and the
; stack is up at STACK_TOP. room_wipe stops at $57FF and room_paper at $5AFF,
; so nothing the engine does reaches it either. Knight Lore makes the same
; judgement and parks its object table at $5C08.
;
; It is contended memory, so what goes here has to be code that does not run
; every turn -- and building a room is the definition of that. It happens once,
; when the room changes, and everything else in the file is untouched by it.
; The few bytes of it that ARE read every turn are room_half_u, room_floor_z
; and the door table, which is a handful of loads.
                    ORG     $5B00
                    INCLUDE "room_build.s"
                    INCLUDE "../engine/room.s"
                    INCLUDE "glance.s"
room_code_end:
                    ASSERT  room_code_end <= $6000
                    DISPLAY "room builder     $5B00..", /H, room_code_end, "   free: ", /D, $6000 - room_code_end


; ---------------------------------------------------------------------------
; Two reservations, put where there is room for them.
;
; The room data ends well short of $8000 and nothing uses what is left, so the
; view buffer and the object pool go there rather than on the end of the image.
; They were on the end until the player arrived and pushed it past $FF00, where
; the stack would have pushed straight into the code -- and nothing would have
; said so, because an image that overruns the stack still assembles.
;
; The view buffer is aligned to its own size, so a row start is a multiple of
; the stride in both pages and `high view_buffer` is even -- the row address
; folds its top bit into D with a single `rl d`, which needs an even base.
                    ORG     $7400
                    ALIGN   512
view_buffer:        DS      VIEW_BUF_ROWS * VIEW_BUF_WIDTH

; The object pool. A room owns all of it: room_build refills it from the start,
; so nothing survives a room change. ROOM_MAX_OBJECTS is the fullest room in
; the castle, which rooms_source.py works out while generating room_data.s.
ROOM_SLOTS          EQU     ROOM_MAX_OBJECTS    ; what room_add may fill
POOL_SLOTS          EQU     ROOM_SLOTS + SPECIAL_SLOTS
                    ALIGN   32
room_objects:
                REPT    POOL_SLOTS
                    ALIGN   32
                    object_record   0,      0,              0, 0, 0
                ENDR
                    ; object_record lays down only the first twenty bytes of a
                    ; record, and the ALIGN in front of the next one is what gives
                    ; it the rest. The last one has no next one: without this its
                    ; last twelve bytes were whatever came after the pool -- which
                    ; is day_step -- and the fullest room's second collectable slot
                    ; is that record. Blanking it zeroed two of day_step's operands,
                    ; and the sun never moved again.
                    ALIGN   32
                    ASSERT  $ == room_objects + POOL_SLOTS * ROOM_STRIDE

; Two tables that were up in the code region until it ran out of room. Neither
; is touched by anything that cares about contention -- bit_reverse_table only
; while a graphic is being mirrored, which happens when a room is built, and
; sprite_table once per object placed -- and both want an alignment that there
; is room to honour here and was not up there.
;
; sprite_table is read as `ld h,(high sprite_table)/2 / ld l,a / add hl,hl`, so
; its page has to be even: a 512 boundary, not merely a 256 one.
                    INCLUDE "clock.s"

                    ALIGN   256
; Every byte with its bits the other way round, for mirroring a sprite. Knight
; Lore keeps the same table at $F100 and reaches it exactly this way, with the
; page in B and the byte in C.
bit_reverse_table:
                    bit_reverse_bytes

                    ALIGN   512
                    INCLUDE "sprite_table.s"

; And code that only runs when a key is pressed, in what is left.
                    INCLUDE "pickup.s"
                    INCLUDE "../engine/screen.s"         ; pickup.s falls into it
pool_end:
                    ASSERT  $ <= $8000      ; still inside the gap
                    DISPLAY "buffer and pool $7400..", /H, pool_end, "   free: ", /D, $8000 - pool_end

; All eight RAM banks, bank 0 first, for build.py to wrap as
; output/knightlore128.z80 with PC at start. Not SAVESNA: a .sna keeps PC on
; the stack, where sjasmplus has to push it into whatever is below SP.
                    SAVEDEV "output/knightlore128.banks", 0, 0, $20000
; ...and the view from $4000 to $FFFF with bank 0 paged in, as the game runs.
                    SAVEBIN "output/knightlore128.bin", $4000, $C000
