"""Builds the isoblocks ray renderer: sjasmplus, from rays/demo.s ->
rays/output/rays.z80.

Generated first, into output/, from files that are edited by hand:

- ray_tables.s, from shared/raycast.py: the view's offsets from the focus, the
  focus's limits, each view row's screen address.
- ray_layout.s and ray_data.s: the memory layout above the code, the compiled
  tiles packed into it, their jump tables, and the sprites' tables (the
  pictures from shared/art/sprites.png, the triangles' pixels from raycast.py).
- colours.bin and heights.bin, from shared/maps/test.json: Tom Harte's
  map of each diamond's colours, and the heights for the sprites.

    python rays/build.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "output"
sys.path.insert(0, str(HERE.parent / "shared"))
from common import assemble, find_label, read_map, read_sprites   # noqa: E402,F401

import isogeom                                                    # noqa: E402
import raycast                                                    # noqa: E402


def ray_tiles() -> list[list[int]]:
    """The 128 tiles: [way round][top][middle][bottom], 8 bytes each.

    Drawn from the model's own triangles and patterns (raycast.band_at and
    PATTERNS), so they cannot disagree with it. A cell's way round is its
    strip's parity; its bands are 2j - 1, 2j and 2j + 1, any j."""
    tiles = []
    for way in range(2):
        for top in range(4):
            for middle in range(4):
                for bottom in range(4):
                    colour = {1: top, 2: middle, 3: bottom}
                    tile = []
                    for y in range(8):
                        byte = 0
                        for x in range(8):
                            band = raycast.band_at(way, x, 8 + y)
                            if raycast.PATTERNS[colour[band]](x, 8 + y):
                                byte |= 0x80 >> x
                        tile.append(byte)
                    tiles.append(tile)
    return tiles


def cast_diamonds() -> set:
    """The diamonds Tom Harte's cast_map casts, as (c, r): 2 x 16 + 1 rows of
    triangles from band 1, even rows 16 whole diamonds from strip 1, odd rows
    15 and a half either side."""
    diamonds = set()
    for row in range(2 * raycast.CHAR_ROWS + 1):
        r = row + 1
        for c in range(r % 2, 33, 2):
            diamonds.add((c, r))
    return diamonds


def cast_reads() -> set:
    """Every (U', V') his casts read, from (U0, V0): each diamond's own line
    of sight, the one beside it on each side and the one above."""
    reads = set()
    for c, r in cast_diamonds():
        u, v = (c - r) // 2, (c + r) // 2
        reads |= {(u, v), (u + 1, v), (u + 1, v - 1), (u, v - 1)}
    return reads


def write_ray_tables(path: Path) -> None:
    u0, v0 = raycast.origin((0, 0))          # the focus's offsets
    reads = cast_reads()
    low_u, high_u = min(u for u, _ in reads), max(u for u, _ in reads)
    low_v, high_v = min(v for _, v in reads), max(v for _, v in reads)
    size = isogeom.MAP_SIZE
    tab = "\t\t\t\t\t"
    lines = ["; Generated by rays/build.py from shared/raycast.py. Do not edit.", "",
             f"RAY_U_OFFSET\t\tEQU\t\t{u0}\t\t\t; U0 = focus x + this",
             f"RAY_V_OFFSET\t\tEQU\t\t{v0}\t\t\t; V0 = focus y + this",
             "; The focus's limits: the cells read stay on the map.",
             f"RAY_MIN_X\t\t\tEQU\t\t{-low_u - u0}",
             f"RAY_MAX_X\t\t\tEQU\t\t{size - 1 - high_u - u0}",
             f"RAY_MIN_Y\t\t\tEQU\t\t{-low_v - v0}",
             f"RAY_MAX_Y\t\t\tEQU\t\t{size - 1 - high_v - v0}",
             f"RAY_FIRST_ROW\t\tEQU\t\t{raycast.FIRST_CHAR_ROW}",
             f"RAY_CHAR_ROWS\t\tEQU\t\t{raycast.CHAR_ROWS}",
             f"RAY_FIRST_STRIP\t\tEQU\t\t{raycast.FIRST_STRIP}",
             f"RAY_STRIPS\t\t\tEQU\t\t{raycast.STRIPS}"]
    lines += ["", "; The screen address of each character row's column 0.", "ray_screen_rows:"]
    for j in range(raycast.FIRST_CHAR_ROW, raycast.FIRST_CHAR_ROW + raycast.CHAR_ROWS):
        line = 8 * j
        address = 0x4000 | ((line & 0xC0) << 5) | ((line & 0x38) << 2)
        lines.append(f"{tab}DW\t\t${address:04X}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# The ray demo's bank 2, above the code. build.py places the generated code
# and tables, so it owns the layout; demo.s includes output/ray_layout.s.
#
# Triangle row r (0-32) is page RAY_TRIANGLE_PAGE + r, strips at 0-31, so
# the rows of a tile are INC H apart. A tile row's bottom triangles' page
# also holds the tiles it shows (output_map, at TRI_OUTPUT) and their sprite
# slots (TRI_SLOTS). The rest of each page, from TRI_FREE, holds the sprite
# buffers (a cell's 8 rows a page apart, like the screen's), the tables, the
# interrupt routine, the stack, and the compiled tiles packed into the gaps.
RAY_TRIANGLE_PAGE = 0x9F
RAY_TRIANGLE_ROWS = 2 * raycast.CHAR_ROWS + 1
TRI_OUTPUT, TRI_SLOTS, TRI_FREE = 32, 64, 96
RAY_CELLS_MAX = 24
RAY_BUFFER_PAGE, RAY_BUFFER_LOW = 0xA8, TRI_FREE
TILE_JUMPS = (0x9A00, 0x9B00)           # by way round: JP to each tile's code
IM2_TABLE = 0x9C00                      # 257 bytes
RAY_VISIBLE_AT = 0x9F80
RAY_PICTURES_AT = 0xA080                # a picture a page
VIDEO_POINTERS_AT = 0xA280
RAY_CELL_SCREENS_AT = 0xA2A0            # 2 bytes a sprite buffer: its screen address...
RAY_CELL_ENTRIES_AT = 0xA3A0            # ...and its cell's output_map entry
ISR_PAGE, ISR_FROM = 0xBB, 0xB0         # $BBB9 frames, $BBBB the routine
STACK_PAGE = 0xBF
RAY_COLOUR_BANK, RAY_HEIGHT_BANK = 0, 4       # banks at $C000: uncontended
RAY_PICTURE_PAD = 8     # empty rows either side of a picture, for ray_sprites.s


def ray_gaps() -> list[tuple[int, int]]:
    """The free ranges of the triangle pages, (first, end), for code."""
    reserved = [(RAY_VISIBLE_AT, RAY_VISIBLE_AT + 128),
                (VIDEO_POINTERS_AT, RAY_CELL_SCREENS_AT + 2 * RAY_CELLS_MAX),
                (RAY_CELL_ENTRIES_AT, RAY_CELL_ENTRIES_AT + 2 * RAY_CELLS_MAX),
                (ISR_PAGE * 256 + ISR_FROM, ISR_PAGE * 256 + 256)]
    reserved += [(RAY_PICTURES_AT + 256 * n, RAY_PICTURES_AT + 256 * n + 128)
                 for n in range(len(read_sprites()))]
    gaps = []
    for page in range(RAY_TRIANGLE_PAGE, STACK_PAGE):
        first = page * 256 + TRI_FREE
        if RAY_BUFFER_PAGE <= page < RAY_BUFFER_PAGE + 8:
            first += RAY_CELLS_MAX
        edges = [first]
        for low, high in sorted(reserved):
            if low // 256 == page:
                edges += [low, high]
        edges.append(page * 256 + 256)
        for start, end in zip(edges[::2], edges[1::2]):
            if end > start:
                gaps.append((start, end))
    return gaps


def his_tile_colours(number: int) -> tuple[int, int, int]:
    """(top, middle, bottom) of one of Tom Harte's tile numbers: the top's
    colour in bits 5 and 2, the middle's in 6 and 3, the bottom's in 7 and 4
    -- each his cast's colour masked with $90, bits 7 and 4 of it, which are
    our colour numbers: floor 0, top 1 ($10), left face 2 ($80), right 3 ($90)."""
    def colour(high: int, low: int) -> int:
        return 2 * (number >> high & 1) + (number >> low & 1)
    return colour(5, 2), colour(6, 3), colour(7, 4)


def write_ray_layout(path: Path) -> None:
    """The layout, as EQUs, and the three bytes the compiled tiles hold in
    B', C' and E' -- the commonest in the tiles."""
    counts = {}
    for tile in ray_tiles():
        for byte in tile:
            counts[byte] = counts.get(byte, 0) + 1
    common = sorted(counts, key=lambda b: -counts[b])[:3]
    lines = ["; Generated by rays/build.py: the ray demo's layout. Do not edit.", "",
             f"triangle_map\t\tEQU\t\t${RAY_TRIANGLE_PAGE * 256:04X}\t; row r a page on",
             f"TRI_OUTPUT\t\t\tEQU\t\t{TRI_OUTPUT}",
             f"TRI_SLOTS\t\t\tEQU\t\t{TRI_SLOTS}",
             f"RAY_CELLS_MAX\t\tEQU\t\t{RAY_CELLS_MAX}",
             f"RAY_BUFFERS\t\t\tEQU\t\t${RAY_BUFFER_PAGE * 256 + RAY_BUFFER_LOW:04X}\t; cell i at +i, rows a page apart",
             f"TILE_JUMPS_0\t\tEQU\t\t${TILE_JUMPS[0]:04X}",
             f"TILE_JUMPS_1\t\tEQU\t\t${TILE_JUMPS[1]:04X}",
             f"IM2_TABLE\t\t\tEQU\t\t${IM2_TABLE:04X}",
             f"RAY_VISIBLE\t\t\tEQU\t\t${RAY_VISIBLE_AT:04X}",
             f"RAY_PICTURES\t\tEQU\t\t${RAY_PICTURES_AT:04X}\t; a picture a page",
             f"video_pointers\t\tEQU\t\t${VIDEO_POINTERS_AT:04X}",
             f"RAY_CELL_SCREENS\tEQU\t\t${RAY_CELL_SCREENS_AT:04X}",
             f"RAY_CELL_ENTRIES\tEQU\t\t${RAY_CELL_ENTRIES_AT:04X}",
             f"RAY_PICTURE_PAD\t\tEQU\t\t{RAY_PICTURE_PAD}",
             f"RAY_COLOUR_BANK\t\tEQU\t\t{RAY_COLOUR_BANK}\t\t; his map, the colours",
             f"RAY_HEIGHT_BANK\t\tEQU\t\t{RAY_HEIGHT_BANK}\t\t; the heights, for the sprites",
             "RAY_COLOUR_PAGE\t\tEQU\t\tRAY_COLOUR_BANK\t; $7FFD for each at $C000",
             "RAY_HEIGHT_PAGE\t\tEQU\t\tRAY_HEIGHT_BANK",
             f"TILE_B\t\t\t\tEQU\t\t${common[0]:02X}\t\t; the compiled tiles' B', C' and E'",
             f"TILE_C\t\t\t\tEQU\t\t${common[1]:02X}",
             f"TILE_E\t\t\t\tEQU\t\t${common[2]:02X}"]
    for number, name in enumerate(read_sprites()):
        lines.append(f"PICTURE_{name.upper()}\tEQU\t\t{number}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_ray_data(path: Path) -> None:
    """Everything the ray demo keeps in the triangle pages' gaps, and the
    jump tables.

    - A compiled tile per different tile: EXX, then each of its 8 bytes
      stored at (HL), INC H between -- LD (HL),B / C / E for the three
      commonest bytes, LD (HL),n for the rest -- then EXX and RET. HL' is
      where it goes: the screen, or a sprite buffer.
    - TILE_JUMPS_0 and _1, by way round: at + his tile number, JP to its
      code. The tiles are drawn from ray_tiles(), so from the model's own
      patterns.
    - video_pointers: each view row's screen address, bottom row first.
    - RAY_VISIBLE and RAY_PICTURES, for the sprites (write_ray_sprite_tables).
    """
    tab = "\t\t\t\t\t"
    ours = ray_tiles()
    counts = {}
    for tile in ours:
        for byte in tile:
            counts[byte] = counts.get(byte, 0) + 1
    common = sorted(counts, key=lambda b: -counts[b])[:3]
    registers = dict(zip(common, "bce"))
    # Each different tile's code, and which each (way, number) uses.
    bodies, names, uses = {}, {}, {}
    for way in range(2):
        for number in range(0, 256, 4):
            top, middle, bottom = his_tile_colours(number)
            tile = tuple(ours[64 * way + 16 * top + 4 * middle + bottom])
            if tile not in names:
                names[tile] = f"tile_code_{len(names)}"
                code = ["exx"]
                for row, byte in enumerate(tile):
                    code.append(f"ld\t\t(hl),{registers[byte]}" if byte in registers
                                else f"ld\t\t(hl),${byte:02X}")
                    if row < 7:
                        code.append("inc\t\th")
                code += ["exx", "ret"]
                size = sum(1 if c.startswith(("exx", "ret", "inc")) or
                           (c.startswith("ld") and not c.endswith(tuple("0123456789ABCDEF")))
                           else 2 for c in code)
                bodies[names[tile]] = (code, size)
            uses[(way, number)] = names[tile]
    # Pack the code into the gaps, biggest first.
    gaps = [list(gap) for gap in ray_gaps()]
    placed = {}
    for name, (code, size) in sorted(bodies.items(), key=lambda item: -item[1][1]):
        for gap in gaps:
            if gap[1] - gap[0] >= size:
                placed[name] = gap[0]
                gap[0] += size
                break
        else:
            sys.exit(f"no room in the triangle pages for {name}")
    lines = ["; Generated by rays/build.py: the ray demo's compiled tiles and tables.",
             "; Do not edit.", ""]
    for name, at in sorted(placed.items(), key=lambda item: item[1]):
        code, _ = bodies[name]
        lines += [f"{tab}ORG\t\t${at:04X}", f"{name}:"] + [f"{tab}{c}" for c in code]
    for way in range(2):
        lines += ["", f"; Way round {way}: JP to each tile's code, at + its number."]
        for number in range(0, 256, 4):
            lines += [f"{tab}ORG\t\t${TILE_JUMPS[way] + number:04X}",
                      f"{tab}jp\t\t{uses[(way, number)]}"]
    lines += ["", f"{tab}ORG\t\tvideo_pointers"]
    for j in reversed(range(raycast.FIRST_CHAR_ROW, raycast.FIRST_CHAR_ROW + raycast.CHAR_ROWS)):
        line = 8 * j
        lines.append(f"{tab}DW\t\t${0x4000 | ((line & 0xC0) << 5) | ((line & 0x38) << 2):04X}")
    lines += ray_sprite_tables()
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    free = sum(end - start for start, end in gaps)
    print(f"Compiled {len(bodies)} tiles into the triangle pages; {free} bytes of gaps left")


def his_colours(front: int, left: int, right: int, back: int) -> tuple[int, int]:
    """Tom Harte's rule for a diamond's left and right halves, from the
    heights (plus one, 0 for none) of its front line of sight and the ones to
    its left, right and back -- as his cast_diamond decided it. Our colour
    numbers: floor 0, top 1, left wall 2, right wall 3."""
    floor, top, left_wall, right_wall = 0, 1, 2, 3
    if not (front | back | left):
        left_half = floor
    elif front < left:
        left_half = right_wall if left >= back else left_wall
    else:
        left_half = top if front >= back else left_wall
    if not (front | back | right):
        right_half = floor
    elif front < right:
        right_half = left_wall if right >= back else right_wall
    else:
        right_half = top if front >= back else right_wall
    return left_half, right_half


def write_maps(cells: bytes, colour_path: Path, height_path: Path) -> None:
    """Tom Harte's map, and its heights. Both are our shifted map with U
    mirrored -- his x is our V and his y is 127 - U.

    The heights (for the sprites): each line of sight's nearest height plus
    one, 0 for none -- what his map held a bit per height of, reduced.

    The colours (for his cast): each byte the colours of the diamond whose
    front line of sight it is, by his rule, the left half's in bits 7 and 4
    and the right half's in bits 6 and 3 -- so AND $90, or ADD A,A and AND
    $90, is the triangle his cast made. His left is our (U, V - 1), his right
    (U + 1, V), his back (U + 1, V - 1); off the map is nothing, and the view
    never reads a diamond there.

    A cube is on exactly one line of sight, so changing the map changes one
    height, and the colours of the four diamonds that line is front, left,
    right or back of."""
    shifted = raycast.shift_map(cells)
    size = isogeom.MAP_SIZE

    def height(u: int, v: int) -> int:
        if 0 <= u < size and 0 <= v < size:
            return shifted[v * size + u].bit_length()
        return 0

    heights, colours = bytearray(size * size), bytearray(size * size)
    for v in range(size):
        for u in range(size):
            at = v * size + (size - 1 - u)
            front = height(u, v)
            left, right = his_colours(front, height(u, v - 1), height(u + 1, v), height(u + 1, v - 1))
            heights[at] = front
            colours[at] = ((left >> 1) << 7 | (left & 1) << 4 |
                           (right >> 1) << 6 | (right & 1) << 3)
    height_path.write_bytes(bytes(heights))
    colour_path.write_bytes(bytes(colours))


def ray_sprite_tables() -> list[str]:
    """RAY_VISIBLE: for each way round of a cell and each set of its triangles
    (4 top, 2 middle, 1 bottom), the pixels of each of its 8 rows those
    triangles cover. RAY_PICTURES, a page apart: each picture's left byte,
    then its right, as 32 rows of (the sprite's pixels, which of them are
    ink) -- the 16 rows of the picture with 8 empty ones either side, so that
    the 8 rows of any character cell the sprite touches are all there to
    read."""
    tab = "\t\t\t\t\t"
    lines = ["", f"{tab}ORG\t\tRAY_VISIBLE"]
    for way in range(2):
        for bits in range(8):
            masks = []
            for y in range(8):
                mask = 0
                for x in range(8):
                    band = raycast.band_at(way, x, 8 + y)       # 1, 2 or 3
                    if bits >> (3 - band) & 1:
                        mask |= 0x80 >> x
                masks.append(f"${mask:02X}")
            lines.append(f"{tab}DB\t\t" + ", ".join(masks))
    blank = [(0, 0)] * RAY_PICTURE_PAD
    for number, (name, rows) in enumerate(read_sprites().items()):
        lines += ["", f"{tab}ORG\t\tRAY_PICTURES + {256 * number}\t; {name}"]
        for shift in (8, 0):
            side = blank + [((opaque >> shift) & 0xFF, (ink >> shift) & 0xFF)
                            for opaque, ink in rows] + blank
            for first in range(0, len(side), 8):
                lines.append(f"{tab}DB\t\t" + ", ".join(f"${o:02X}, ${i:02X}"
                                                      for o, i in side[first:first + 8]))
    return lines


def main() -> None:
    OUT.mkdir(exist_ok=True)
    write_ray_tables(OUT / "ray_tables.s")
    write_ray_layout(OUT / "ray_layout.s")
    write_ray_data(OUT / "ray_data.s")
    write_maps(read_map(), OUT / "colours.bin", OUT / "heights.bin")
    assemble(HERE, "rays")


if __name__ == "__main__":
    main()
