"""Builds the isoblocks demo: sjasmplus, from demo/demo.s -> output/demo.z80.

Three things are generated first, into output/, from files that are edited by
hand:

- view_tables.s, from isogeom.py: each view's three map steps, where its
  first cell is from the focus, and the limits that keep the view on the map.
  The same module is the model check_render.py draws with, so the engine and
  the model cannot disagree about the geometry.
- blocks_gen.s, from art/blocks.png and art/blocks.json: a drawer per block
  picture, unrolled -- a store for every byte of the block that is solid, an
  AND and an OR for every byte that is part clear, nothing at all for a byte
  that is wholly clear.
- map.bin, from maps/test.json: the boxes rasterised to 16K of cells.

sjasmplus writes all eight RAM banks (SAVEDEV), the view from $4000 as the
engine runs (SAVEBIN, for check_render.py) and the SLD; ../filmation/z80file.py
wraps the banks as a 128K .z80 that starts at `start`.

    python build.py
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
OUT = HERE / "output"
sys.path.insert(0, str(HERE.parent / "filmation"))
import z80file                                                   # noqa: E402

import isogeom                                                    # noqa: E402
import raycast                                                    # noqa: E402

SJASMPLUS = [REPO / "tools" / "sjasmplus" / "sjasmplus.exe",
             REPO / ".venv-win" / "Scripts" / "sjasmplus.exe"]


def find_sjasmplus() -> str:
    for candidate in SJASMPLUS:
        if candidate.is_file():
            return str(candidate)
    found = shutil.which("sjasmplus")
    if found:
        return found
    sys.exit("sjasmplus not found -- see examples/filmation/knightlore/build.py")


def word(value: int) -> str:
    return f"${value & 0xFFFF:04X}"


def write_view_tables(path: Path) -> None:
    """VIEW_TABLE: 16 bytes a view -- steps, start offset, focus limits, drawers."""
    lines = ["; Generated by build.py from isogeom.py. Do not edit.", "",
             "; Per view, 16 bytes: the map steps along a half-row, to the second",
             "; half-row and to the next row; the first cell read, from the focus",
             "; (x, y, signed); the focus's lowest and highest x and y; the",
             "; drawers for the view's block picture in a first half-row and in a",
             "; second.", "",
             "\t\t\t\t\tALIGN\t64", "view_table:"]
    for view in range(4):
        along, second, next_row = isogeom.view_steps(view)
        sx, sy = isogeom.start_from_focus(view)
        min_x, max_x, min_y, max_y = isogeom.focus_limits(view)
        drawer = "draw_block_even" if view % 2 == 0 else "draw_block_odd"
        lines += [f"; view {view}",
                  f"\t\t\t\t\tDW\t\t{word(along)}, {word(second)}, {word(next_row)}",
                  f"\t\t\t\t\tDB\t\t{sx & 0xFF}, {sy & 0xFF}, {min_x}, {max_x}, {min_y}, {max_y}",
                  f"\t\t\t\t\tDW\t\t{drawer}_first, {drawer}_second"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def read_blocks() -> list:
    """Each block picture as 16 rows of two (mask, bits) bytes, views 0/2 first."""
    spec = json.loads((HERE / "art" / "blocks.json").read_text(encoding="utf-8"))
    sheet = Image.open(HERE / "art" / spec["sheet"]).convert("RGB")
    colour = {name: tuple(int(value[i:i + 2], 16) for i in (1, 3, 5))
              for name, value in spec["colours"].items()}
    blocks = []
    for name in ("views 0 and 2", "views 1 and 3"):
        left, top = spec["blocks"][name]["at"]
        rows = []
        for y in range(16):
            row = []
            for byte in range(2):
                mask = bits = 0
                for bit in range(8):
                    pixel = sheet.getpixel((left + 8 * byte + bit, top + y))
                    weight = 0x80 >> bit
                    if pixel == colour["clear"]:
                        mask |= weight
                    elif pixel == colour["ink"]:
                        bits |= weight
                    elif pixel != colour["paper"]:
                        sys.exit(f"art/{spec['sheet']}: {name} has a pixel that is not "
                                 f"ink, paper or clear at ({8 * byte + bit}, {y})")
                row.append((mask, bits))
            rows.append(row)
        blocks.append(rows)
    return blocks


def pixels(rows: list) -> tuple[set, set]:
    """A block picture's (opaque pixels, ink pixels), as (x, y)."""
    opaque, ink = set(), set()
    for y, row in enumerate(rows):
        for byte, (mask, bits) in enumerate(row):
            for bit in range(8):
                weight = 0x80 >> bit
                if not mask & weight:
                    opaque.add((8 * byte + bit, y))
                    if bits & weight:
                        ink.add((8 * byte + bit, y))
    return opaque, ink


# Down a pixel line from a character row's last to the next row's first: L on
# a row, and H back to line 0 of the third -- or, when L carries out of the
# third's last row, on to the next third, whose line 0 is one page on.
NEXT_CHARACTER_ROW = ["\t\t\t\t\tld\t\ta,l", "\t\t\t\t\tadd\t\ta,32", "\t\t\t\t\tld\t\tl,a",
                      "\t\t\t\t\tld\t\ta,h", "\t\t\t\t\tjr\t\tc,$+4", "\t\t\t\t\tsub\t\t8",
                      "\t\t\t\t\tinc\t\ta", "\t\t\t\t\tld\t\th,a"]


def drawer_code(draw: set, opaque: set, ink: set, first_line: int) -> list[str]:
    """Unrolled code painting every byte that has a pixel in `draw`, straight
    into the screen: the block's top row is line `first_line` (0 or 4) of a
    character row.

    A byte is painted whole -- all of the block's own pixels in it, not only
    those in `draw` -- because painting more of the block is always safe
    (whatever covers it is painted later) and a byte that is solid is one
    store, where picking pixels out of it would take a mask and a merge.

    In: HL the block's top left on the screen. HL moves through the block a
    byte at a time: INC L to its right byte and DEC L back, INC H down a pixel
    line, and NEXT_CHARACTER_ROW where a line is a character row's last. It
    goes down only from the left byte: the rightmost place of a row has its
    right byte in column 32, which INC L makes column 0 a character row on --
    in the margin, never shown, and DEC L undoes it.
    """
    code, line, at = [], 0, 0
    for y in range(16):
        for byte in range(2):
            if not any((8 * byte + bit, y) in draw for bit in range(8)):
                continue
            want = sum(0x80 >> bit for bit in range(8) if (8 * byte + bit, y) in opaque)
            bits = sum(0x80 >> bit for bit in range(8) if (8 * byte + bit, y) in ink) & want
            if line != y and at == 1:
                code.append("\t\t\t\t\tdec\t\tl")
                at = 0
            while line < y:
                if (first_line + line) % 8 == 7:
                    code += NEXT_CHARACTER_ROW
                else:
                    code.append("\t\t\t\t\tinc\t\th")
                line += 1
            if byte != at:
                code.append("\t\t\t\t\tinc\t\tl")
                at = byte
            if want == 0xFF:
                code.append(f"\t\t\t\t\tld\t\t(hl),${bits:02X}")
            else:
                code += ["\t\t\t\t\tld\t\ta,(hl)", f"\t\t\t\t\tand\t\t${0xFF ^ want:02X}"]
                if bits:
                    code.append(f"\t\t\t\t\tor\t\t${bits:02X}")
                code.append("\t\t\t\t\tld\t\t(hl),a")
    return code


def write_block_drawers(blocks: list, path: Path) -> None:
    """A drawer per block picture, unrolled.

    (Drawers that leave out what the covering places paint over were tried:
    a drawer per set of covers, the set worked out for every block. They
    drew less, but finding the whole set cost more than they saved -- see
    plan.md. Whole blocks are drawn, and whole blocks that are covered are
    left out, in paint.s.)
    """
    lines = ["; Generated by build.py from art/blocks.png. Do not edit.", "",
             "; Two drawers a picture: a first half-row's block starts 4 lines into",
             "; a character row, a second half-row's at the top of one.",
             "; In:  HL the block's top left on the screen. Uses A. HL is left",
             "; somewhere in the block."]
    for name, rows in zip(("draw_block_even", "draw_block_odd"), blocks):
        opaque, ink = pixels(rows)
        for half, first_line in (("first", 4), ("second", 0)):
            lines += ["", f"{name}_{half}:"] + drawer_code(opaque, opaque, ink, first_line) \
                + ["\t\t\t\t\tret"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_map(path: Path) -> bytes:
    spec = json.loads((HERE / "maps" / "test.json").read_text(encoding="utf-8"))
    cells = isogeom.rasterise(spec["boxes"])
    path.write_bytes(cells)
    return cells


# ---------------------------------------------------------------------------
# The ray renderer (engine/harte_*.s and ray_view.s, raycast.py).
# ---------------------------------------------------------------------------

def ray_tiles() -> list[list[int]]:
    """The 128 tiles: [way round][top][middle][bottom], 8 bytes each.

    Drawn from the model's own triangles and patterns (raycast.band_at and
    PATTERNS), so they cannot disagree with it. A cell's way round is its
    strip's parity; its bands are 2j - 1, 2j and 2j + 1, any j."""
    tiles = []
    for way in range(2):
        for top in range(4):
            for middle in range(4):
                for bottom in range(4):
                    colour = {1: top, 2: middle, 3: bottom}
                    tile = []
                    for y in range(8):
                        byte = 0
                        for x in range(8):
                            band = raycast.band_at(way, x, 8 + y)
                            if raycast.PATTERNS[colour[band]](x, 8 + y):
                                byte |= 0x80 >> x
                        tile.append(byte)
                    tiles.append(tile)
    return tiles


def harte_diamonds() -> set:
    """The diamonds Tom Harte's cast_map casts, as (c, r): 2 x 16 + 1 rows of
    triangles from band 1, even rows 16 whole diamonds from strip 1, odd rows
    15 and a half either side."""
    diamonds = set()
    for row in range(2 * raycast.CHAR_ROWS + 1):
        r = row + 1
        for c in range(r % 2, 33, 2):
            diamonds.add((c, r))
    return diamonds


def harte_reads() -> set:
    """Every (U', V') his casts read, from (U0, V0): each diamond's own line
    of sight, the one beside it on each side and the one above."""
    reads = set()
    for c, r in harte_diamonds():
        u, v = (c - r) // 2, (c + r) // 2
        reads |= {(u, v), (u + 1, v), (u + 1, v - 1), (u, v - 1)}
    return reads


def write_ray_tables(path: Path) -> None:
    u0, v0 = raycast.origin((0, 0))          # the focus's offsets
    reads = harte_reads()
    low_u, high_u = min(u for u, _ in reads), max(u for u, _ in reads)
    low_v, high_v = min(v for _, v in reads), max(v for _, v in reads)
    size = isogeom.MAP_SIZE
    tab = "\t\t\t\t\t"
    lines = ["; Generated by build.py from raycast.py. Do not edit.", "",
             f"RAY_U_OFFSET\t\tEQU\t\t{u0}\t\t\t; U0 = focus x + this",
             f"RAY_V_OFFSET\t\tEQU\t\t{v0}\t\t\t; V0 = focus y + this",
             "; The focus's limits: the cells read stay on the map.",
             f"RAY_MIN_X\t\t\tEQU\t\t{-low_u - u0}",
             f"RAY_MAX_X\t\t\tEQU\t\t{size - 1 - high_u - u0}",
             f"RAY_MIN_Y\t\t\tEQU\t\t{-low_v - v0}",
             f"RAY_MAX_Y\t\t\tEQU\t\t{size - 1 - high_v - v0}",
             f"RAY_FIRST_ROW\t\tEQU\t\t{raycast.FIRST_CHAR_ROW}",
             f"RAY_CHAR_ROWS\t\tEQU\t\t{raycast.CHAR_ROWS}",
             f"RAY_FIRST_STRIP\t\tEQU\t\t{raycast.FIRST_STRIP}",
             f"RAY_STRIPS\t\t\tEQU\t\t{raycast.STRIPS}"]
    lines += ["", "; The screen address of each character row's column 0.", "ray_screen_rows:"]
    for j in range(raycast.FIRST_CHAR_ROW, raycast.FIRST_CHAR_ROW + raycast.CHAR_ROWS):
        line = 8 * j
        address = 0x4000 | ((line & 0xC0) << 5) | ((line & 0x38) << 2)
        lines.append(f"{tab}DW\t\t${address:04X}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# The ray demo's bank 2, above the code. build.py places the generated code
# and tables, so it owns the layout; demo/ray_demo.s includes ray_layout.s.
#
# Triangle row r (0-32) is page RAY_TRIANGLE_PAGE + r, strips at 0-31, so
# the rows of a tile are INC H apart. A tile row's bottom triangles' page
# also holds the tiles it shows (output_map, at TRI_OUTPUT) and their sprite
# slots (TRI_SLOTS). The rest of each page, from TRI_FREE, holds the sprite
# buffers (a cell's 8 rows a page apart, like the screen's), the tables, the
# interrupt routine, the stack, and the compiled tiles packed into the gaps.
RAY_TRIANGLE_PAGE = 0x9F
RAY_TRIANGLE_ROWS = 2 * raycast.CHAR_ROWS + 1
TRI_OUTPUT, TRI_SLOTS, TRI_FREE = 32, 64, 96
RAY_CELLS_MAX = 24
RAY_BUFFER_PAGE, RAY_BUFFER_LOW = 0xA8, TRI_FREE
TILE_JUMPS = (0x9A00, 0x9B00)           # by way round: JP to each tile's code
IM2_TABLE = 0x9C00                      # 257 bytes
RAY_VISIBLE_AT = 0x9F80
RAY_PICTURES_AT = 0xA080                # a picture a page
VIDEO_POINTERS_AT = 0xA280
RAY_CELL_SCREENS_AT = 0xA2A0            # 2 bytes a sprite buffer
ISR_PAGE, ISR_FROM = 0xBB, 0xB0         # $BBB9 frames, $BBBB the routine
STACK_PAGE = 0xBF
RAY_COLOUR_BANK, RAY_HEIGHT_BANK = 0, 4       # banks at $C000: uncontended
RAY_PICTURE_PAD = 8     # empty rows either side of a picture, for ray_sprites.s


def ray_gaps() -> list[tuple[int, int]]:
    """The free ranges of the triangle pages, (first, end), for code."""
    reserved = [(RAY_VISIBLE_AT, RAY_VISIBLE_AT + 128),
                (VIDEO_POINTERS_AT, RAY_CELL_SCREENS_AT + 2 * RAY_CELLS_MAX),
                (ISR_PAGE * 256 + ISR_FROM, ISR_PAGE * 256 + 256)]
    reserved += [(RAY_PICTURES_AT + 256 * n, RAY_PICTURES_AT + 256 * n + 128)
                 for n in range(len(read_sprites()))]
    gaps = []
    for page in range(RAY_TRIANGLE_PAGE, STACK_PAGE):
        first = page * 256 + TRI_FREE
        if RAY_BUFFER_PAGE <= page < RAY_BUFFER_PAGE + 8:
            first += RAY_CELLS_MAX
        edges = [first]
        for low, high in sorted(reserved):
            if low // 256 == page:
                edges += [low, high]
        edges.append(page * 256 + 256)
        for start, end in zip(edges[::2], edges[1::2]):
            if end > start:
                gaps.append((start, end))
    return gaps


def his_tile_colours(number: int) -> tuple[int, int, int]:
    """(top, middle, bottom) of one of Tom Harte's tile numbers: the top's
    colour in bits 5 and 2, the middle's in 6 and 3, the bottom's in 7 and 4
    -- each his cast's colour masked with $90, bits 7 and 4 of it, which are
    our colour numbers: floor 0, top 1 ($10), left face 2 ($80), right 3 ($90)."""
    def colour(high: int, low: int) -> int:
        return 2 * (number >> high & 1) + (number >> low & 1)
    return colour(5, 2), colour(6, 3), colour(7, 4)


def write_ray_layout(path: Path) -> None:
    """The layout, as EQUs, and the three bytes the compiled tiles hold in
    B', C' and E' -- the commonest in the tiles."""
    counts = {}
    for tile in ray_tiles():
        for byte in tile:
            counts[byte] = counts.get(byte, 0) + 1
    common = sorted(counts, key=lambda b: -counts[b])[:3]
    lines = ["; Generated by build.py: the ray demo's layout. Do not edit.", "",
             f"triangle_map\t\tEQU\t\t${RAY_TRIANGLE_PAGE * 256:04X}\t; row r a page on",
             f"TRI_OUTPUT\t\t\tEQU\t\t{TRI_OUTPUT}",
             f"TRI_SLOTS\t\t\tEQU\t\t{TRI_SLOTS}",
             f"RAY_CELLS_MAX\t\tEQU\t\t{RAY_CELLS_MAX}",
             f"RAY_BUFFERS\t\t\tEQU\t\t${RAY_BUFFER_PAGE * 256 + RAY_BUFFER_LOW:04X}\t; cell i at +i, rows a page apart",
             f"TILE_JUMPS_0\t\tEQU\t\t${TILE_JUMPS[0]:04X}",
             f"TILE_JUMPS_1\t\tEQU\t\t${TILE_JUMPS[1]:04X}",
             f"IM2_TABLE\t\t\tEQU\t\t${IM2_TABLE:04X}",
             f"RAY_VISIBLE\t\t\tEQU\t\t${RAY_VISIBLE_AT:04X}",
             f"RAY_PICTURES\t\tEQU\t\t${RAY_PICTURES_AT:04X}\t; a picture a page",
             f"video_pointers\t\tEQU\t\t${VIDEO_POINTERS_AT:04X}",
             f"RAY_CELL_SCREENS\tEQU\t\t${RAY_CELL_SCREENS_AT:04X}",
             f"RAY_PICTURE_PAD\t\tEQU\t\t{RAY_PICTURE_PAD}",
             f"RAY_COLOUR_BANK\t\tEQU\t\t{RAY_COLOUR_BANK}\t\t; his map, the colours",
             f"RAY_HEIGHT_BANK\t\tEQU\t\t{RAY_HEIGHT_BANK}\t\t; the heights, for the sprites",
             "RAY_COLOUR_PAGE\t\tEQU\t\tRAY_COLOUR_BANK\t; $7FFD for each at $C000",
             "RAY_HEIGHT_PAGE\t\tEQU\t\tRAY_HEIGHT_BANK",
             f"TILE_B\t\t\t\tEQU\t\t${common[0]:02X}\t\t; the compiled tiles' B', C' and E'",
             f"TILE_C\t\t\t\tEQU\t\t${common[1]:02X}",
             f"TILE_E\t\t\t\tEQU\t\t${common[2]:02X}"]
    for number, name in enumerate(read_sprites()):
        lines.append(f"RAY_PICTURE_{name.upper()}\tEQU\t\t{number}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_ray_data(path: Path) -> None:
    """Everything the ray demo keeps in the triangle pages' gaps, and the
    jump tables.

    - A compiled tile per different tile: EXX, then each of its 8 bytes
      stored at (HL), INC H between -- LD (HL),B / C / E for the three
      commonest bytes, LD (HL),n for the rest -- then EXX and RET. HL' is
      where it goes: the screen, or a sprite buffer.
    - TILE_JUMPS_0 and _1, by way round: at + his tile number, JP to its
      code. The tiles are drawn from ray_tiles(), so from the model's own
      patterns.
    - video_pointers: each view row's screen address, bottom row first.
    - RAY_VISIBLE and RAY_PICTURES, for the sprites (write_ray_sprite_tables).
    """
    tab = "\t\t\t\t\t"
    ours = ray_tiles()
    counts = {}
    for tile in ours:
        for byte in tile:
            counts[byte] = counts.get(byte, 0) + 1
    common = sorted(counts, key=lambda b: -counts[b])[:3]
    registers = dict(zip(common, "bce"))
    # Each different tile's code, and which each (way, number) uses.
    bodies, names, uses = {}, {}, {}
    for way in range(2):
        for number in range(0, 256, 4):
            top, middle, bottom = his_tile_colours(number)
            tile = tuple(ours[64 * way + 16 * top + 4 * middle + bottom])
            if tile not in names:
                names[tile] = f"tile_code_{len(names)}"
                code = ["exx"]
                for row, byte in enumerate(tile):
                    code.append(f"ld\t\t(hl),{registers[byte]}" if byte in registers
                                else f"ld\t\t(hl),${byte:02X}")
                    if row < 7:
                        code.append("inc\t\th")
                code += ["exx", "ret"]
                size = sum(1 if c.startswith(("exx", "ret", "inc")) or
                           (c.startswith("ld") and not c.endswith(tuple("0123456789ABCDEF")))
                           else 2 for c in code)
                bodies[names[tile]] = (code, size)
            uses[(way, number)] = names[tile]
    # Pack the code into the gaps, biggest first.
    gaps = [list(gap) for gap in ray_gaps()]
    placed = {}
    for name, (code, size) in sorted(bodies.items(), key=lambda item: -item[1][1]):
        for gap in gaps:
            if gap[1] - gap[0] >= size:
                placed[name] = gap[0]
                gap[0] += size
                break
        else:
            sys.exit(f"no room in the triangle pages for {name}")
    lines = ["; Generated by build.py: the ray demo's compiled tiles and tables.",
             "; Do not edit.", ""]
    for name, at in sorted(placed.items(), key=lambda item: item[1]):
        code, _ = bodies[name]
        lines += [f"{tab}ORG\t\t${at:04X}", f"{name}:"] + [f"{tab}{c}" for c in code]
    for way in range(2):
        lines += ["", f"; Way round {way}: JP to each tile's code, at + its number."]
        for number in range(0, 256, 4):
            lines += [f"{tab}ORG\t\t${TILE_JUMPS[way] + number:04X}",
                      f"{tab}jp\t\t{uses[(way, number)]}"]
    lines += ["", f"{tab}ORG\t\tvideo_pointers"]
    for j in reversed(range(raycast.FIRST_CHAR_ROW, raycast.FIRST_CHAR_ROW + raycast.CHAR_ROWS)):
        line = 8 * j
        lines.append(f"{tab}DW\t\t${0x4000 | ((line & 0xC0) << 5) | ((line & 0x38) << 2):04X}")
    lines += ray_sprite_tables()
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    free = sum(end - start for start, end in gaps)
    print(f"Compiled {len(bodies)} tiles into the triangle pages; {free} bytes of gaps left")


def his_colours(front: int, left: int, right: int, back: int) -> tuple[int, int]:
    """Tom Harte's rule for a diamond's left and right halves, from the
    heights (plus one, 0 for none) of its front line of sight and the ones to
    its left, right and back -- as his cast_diamond decided it. Our colour
    numbers: floor 0, top 1, left wall 2, right wall 3."""
    floor, top, left_wall, right_wall = 0, 1, 2, 3
    if not (front | back | left):
        left_half = floor
    elif front < left:
        left_half = right_wall if left >= back else left_wall
    else:
        left_half = top if front >= back else left_wall
    if not (front | back | right):
        right_half = floor
    elif front < right:
        right_half = left_wall if right >= back else right_wall
    else:
        right_half = top if front >= back else right_wall
    return left_half, right_half


def write_harte_maps(cells: bytes, colour_path: Path, height_path: Path) -> None:
    """Tom Harte's map, and its heights. Both are our shifted map with U
    mirrored -- his x is our V and his y is 127 - U.

    The heights (for the sprites): each line of sight's nearest height plus
    one, 0 for none -- what his map held a bit per height of, reduced.

    The colours (for his cast): each byte the colours of the diamond whose
    front line of sight it is, by his rule, the left half's in bits 7 and 4
    and the right half's in bits 6 and 3 -- so AND $90, or ADD A,A and AND
    $90, is the triangle his cast made. His left is our (U, V - 1), his right
    (U + 1, V), his back (U + 1, V - 1); off the map is nothing, and the view
    never reads a diamond there.

    A cube is on exactly one line of sight, so changing the map changes one
    height, and the colours of the four diamonds that line is front, left,
    right or back of."""
    shifted = raycast.shift_map(cells)
    size = isogeom.MAP_SIZE

    def height(u: int, v: int) -> int:
        if 0 <= u < size and 0 <= v < size:
            return shifted[v * size + u].bit_length()
        return 0

    heights, colours = bytearray(size * size), bytearray(size * size)
    for v in range(size):
        for u in range(size):
            at = v * size + (size - 1 - u)
            front = height(u, v)
            left, right = his_colours(front, height(u, v - 1), height(u + 1, v), height(u + 1, v - 1))
            heights[at] = front
            colours[at] = ((left >> 1) << 7 | (left & 1) << 4 |
                           (right >> 1) << 6 | (right & 1) << 3)
    height_path.write_bytes(bytes(heights))
    colour_path.write_bytes(bytes(colours))


def read_sprites() -> dict:
    """{name: picture}, a picture 16 rows of (opaque, ink) 16-bit pairs, bit 15
    the leftmost pixel -- the form raycast.render_with_sprites takes."""
    spec = json.loads((HERE / "art" / "sprites.json").read_text(encoding="utf-8"))
    sheet = Image.open(HERE / "art" / spec["sheet"]).convert("RGB")
    colour = {name: tuple(int(value[i:i + 2], 16) for i in (1, 3, 5))
              for name, value in spec["colours"].items()}
    pictures = {}
    for name, where in spec["sprites"].items():
        left, top = where["at"]
        rows = []
        for y in range(16):
            opaque = ink = 0
            for x in range(16):
                pixel = sheet.getpixel((left + x, top + y))
                if pixel == colour["clear"]:
                    continue
                opaque |= 0x8000 >> x
                if pixel == colour["ink"]:
                    ink |= 0x8000 >> x
                elif pixel != colour["paper"]:
                    sys.exit(f"art/{spec['sheet']}: {name} has a pixel that is not "
                             f"ink, paper or clear at ({x}, {y})")
            rows.append((opaque, ink))
        pictures[name] = rows
    return pictures


def ray_sprite_tables() -> list[str]:
    """RAY_VISIBLE: for each way round of a cell and each set of its triangles
    (4 top, 2 middle, 1 bottom), the pixels of each of its 8 rows those
    triangles cover. RAY_PICTURES, a page apart: each picture's left byte,
    then its right, as 32 rows of (the sprite's pixels, which of them are
    ink) -- the 16 rows of the picture with 8 empty ones either side, so that
    the 8 rows of any character cell the sprite touches are all there to
    read."""
    tab = "\t\t\t\t\t"
    lines = ["", f"{tab}ORG\t\tRAY_VISIBLE"]
    for way in range(2):
        for bits in range(8):
            masks = []
            for y in range(8):
                mask = 0
                for x in range(8):
                    band = raycast.band_at(way, x, 8 + y)       # 1, 2 or 3
                    if bits >> (3 - band) & 1:
                        mask |= 0x80 >> x
                masks.append(f"${mask:02X}")
            lines.append(f"{tab}DB\t\t" + ", ".join(masks))
    blank = [(0, 0)] * RAY_PICTURE_PAD
    for number, (name, rows) in enumerate(read_sprites().items()):
        lines += ["", f"{tab}ORG\t\tRAY_PICTURES + {256 * number}\t; {name}"]
        for shift in (8, 0):
            side = blank + [((opaque >> shift) & 0xFF, (ink >> shift) & 0xFF)
                            for opaque, ink in rows] + blank
            for first in range(0, len(side), 8):
                lines.append(f"{tab}DB\t\t" + ", ".join(f"${o:02X}, ${i:02X}"
                                                      for o, i in side[first:first + 8]))
    return lines


def write_ray_tiles(path: Path) -> None:
    """The tiles a byte per page: row n of tile t at TILES + 256n + t."""
    tiles = ray_tiles()
    tab = "\t\t\t\t\t"
    lines = ["; Generated by build.py from raycast.py. Do not edit."]
    for row in range(8):
        lines += ["", f"{tab}ORG\t\tTILES + {256 * row}"]
        for first in range(0, len(tiles), 16):
            lines.append(f"{tab}DB\t\t" + ", ".join(f"${tiles[t][row]:02X}"
                                                  for t in range(first, first + 16)))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_ray_map(cells: bytes, path: Path) -> None:
    """The ray map: each shifted cell's nearest height plus one, or 0."""
    shifted = raycast.shift_map(cells)
    path.write_bytes(bytes(b.bit_length() for b in shifted))


def find_label(sld: Path, name: str) -> int:
    """A label's address, from the SLD's label records."""
    for line in sld.read_text(encoding="utf-8").splitlines():
        fields = line.split("|")
        if len(fields) >= 8 and fields[6] == "L":
            parts = fields[7].split(",")
            if len(parts) > 2 and parts[1] == name and parts[2] == "":
                return int(fields[5])
    sys.exit(f"no label {name} in {sld}")


def main() -> None:
    OUT.mkdir(exist_ok=True)
    write_view_tables(OUT / "view_tables.s")
    write_block_drawers(read_blocks(), OUT / "blocks_gen.s")
    cells = write_map(OUT / "map.bin")
    write_ray_tables(OUT / "ray_tables.s")
    write_ray_tiles(OUT / "ray_tiles.s")
    write_ray_map(cells, OUT / "ray_map.bin")
    write_ray_layout(OUT / "ray_layout.s")
    write_ray_data(OUT / "ray_data.s")
    write_harte_maps(cells, OUT / "harte_map.bin", OUT / "harte_heights.bin")
    for name in ("demo", "ray_demo"):
        subprocess.run([find_sjasmplus(), f"--sld=../output/{name}.sld", "--fullpath",
                        f"--lst=../output/{name}.lst", f"{name}.s"], cwd=HERE / "demo", check=True)
        banks = (OUT / f"{name}.banks").read_bytes()
        start = find_label(OUT / f"{name}.sld", "start")
        # $7FFD 0: bank 0 at $C000, which holds the map; the normal screen.
        (OUT / f"{name}.z80").write_bytes(z80file.snapshot_128k(banks, start, 0))
        print(f"Wrote {OUT / (name + '.z80')} (128K, PC {start:04X}) and {OUT / (name + '.sld')}")


if __name__ == "__main__":
    main()
