"""Builds the isoblocks painter: sjasmplus, from painter/demo.s ->
painter/output/painter.z80.

Generated first, into output/, from files that are edited by hand:

- view_tables.s, from shared/isogeom.py: each view's three map steps, where
  its first cell is from the focus, and the limits that keep the view on the
  map. The same module is the model check.py draws with, so the engine and
  the model cannot disagree about the geometry.
- blocks_gen.s, from shared/art/blocks.png and blocks.json: a drawer per block
  picture, unrolled -- a store for every byte of the block that is solid, an
  AND and an OR for every byte that is part clear, nothing at all for a byte
  that is wholly clear.
- sprite_pictures.s, from shared/art/sprites.png: each sprite picture for the
  painter's sprites.
- map.bin, from shared/maps/test.json: the boxes rasterised to 16K of cells.

    python painter/build.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
OUT = HERE / "output"
sys.path.insert(0, str(HERE.parent / "shared"))
from common import SHARED, assemble, find_label, read_map, read_sprites, word   # noqa: E402,F401

import isogeom                                                    # noqa: E402


def write_view_tables(path: Path) -> None:
    """VIEW_TABLE: 16 bytes a view -- steps, start offset, focus limits, drawers."""
    lines = ["; Generated by painter/build.py from shared/isogeom.py. Do not edit.", "",
             "; Per view, 16 bytes: the map steps along a half-row, to the second",
             "; half-row and to the next row; the first cell read, from the focus",
             "; (x, y, signed); the focus's lowest and highest x and y; the",
             "; drawers for the view's block picture in a first half-row and in a",
             "; second.", "",
             f"SPRITE_START_X\t\tEQU\t\t{isogeom.start_from_focus(0)[0]}\t\t; view 0's first cell, from",
             f"SPRITE_START_Y\t\tEQU\t\t{isogeom.start_from_focus(0)[1]}\t\t; the focus: for sprites", "",
             "\t\t\t\t\tALIGN\t64", "view_table:"]
    for view in range(4):
        along, second, next_row = isogeom.view_steps(view)
        sx, sy = isogeom.start_from_focus(view)
        min_x, max_x, min_y, max_y = isogeom.focus_limits(view)
        drawer = "draw_block_even" if view % 2 == 0 else "draw_block_odd"
        lines += [f"; view {view}",
                  f"\t\t\t\t\tDW\t\t{word(along)}, {word(second)}, {word(next_row)}",
                  f"\t\t\t\t\tDB\t\t{sx & 0xFF}, {sy & 0xFF}, {min_x}, {max_x}, {min_y}, {max_y}",
                  f"\t\t\t\t\tDW\t\t{drawer}_first, {drawer}_second"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def read_blocks() -> list:
    """Each block picture as 16 rows of two (mask, bits) bytes, views 0/2 first."""
    spec = json.loads((SHARED / "art" / "blocks.json").read_text(encoding="utf-8"))
    sheet = Image.open(SHARED / "art" / spec["sheet"]).convert("RGB")
    colour = {name: tuple(int(value[i:i + 2], 16) for i in (1, 3, 5))
              for name, value in spec["colours"].items()}
    blocks = []
    for name in ("views 0 and 2", "views 1 and 3"):
        left, top = spec["blocks"][name]["at"]
        rows = []
        for y in range(16):
            row = []
            for byte in range(2):
                mask = bits = 0
                for bit in range(8):
                    pixel = sheet.getpixel((left + 8 * byte + bit, top + y))
                    weight = 0x80 >> bit
                    if pixel == colour["clear"]:
                        mask |= weight
                    elif pixel == colour["ink"]:
                        bits |= weight
                    elif pixel != colour["paper"]:
                        sys.exit(f"art/{spec['sheet']}: {name} has a pixel that is not "
                                 f"ink, paper or clear at ({8 * byte + bit}, {y})")
                row.append((mask, bits))
            rows.append(row)
        blocks.append(rows)
    return blocks


def pixels(rows: list) -> tuple[set, set]:
    """A block picture's (opaque pixels, ink pixels), as (x, y)."""
    opaque, ink = set(), set()
    for y, row in enumerate(rows):
        for byte, (mask, bits) in enumerate(row):
            for bit in range(8):
                weight = 0x80 >> bit
                if not mask & weight:
                    opaque.add((8 * byte + bit, y))
                    if bits & weight:
                        ink.add((8 * byte + bit, y))
    return opaque, ink


# Down a pixel line from a character row's last to the next row's first: L on
# a row, and H back to line 0 of the third -- or, when L carries out of the
# third's last row, on to the next third, whose line 0 is one page on.
NEXT_CHARACTER_ROW = ["\t\t\t\t\tld\t\ta,l", "\t\t\t\t\tadd\t\ta,32", "\t\t\t\t\tld\t\tl,a",
                      "\t\t\t\t\tld\t\ta,h", "\t\t\t\t\tjr\t\tc,$+4", "\t\t\t\t\tsub\t\t8",
                      "\t\t\t\t\tinc\t\ta", "\t\t\t\t\tld\t\th,a"]


def drawer_code(draw: set, opaque: set, ink: set, first_line: int) -> list[str]:
    """Unrolled code painting every byte that has a pixel in `draw`, straight
    into the screen: the block's top row is line `first_line` (0 or 4) of a
    character row.

    A byte is painted whole -- all of the block's own pixels in it, not only
    those in `draw` -- because painting more of the block is always safe
    (whatever covers it is painted later) and a byte that is solid is one
    store, where picking pixels out of it would take a mask and a merge.

    In: HL the block's top left on the screen. HL moves through the block a
    byte at a time: INC L to its right byte and DEC L back, INC H down a pixel
    line, and NEXT_CHARACTER_ROW where a line is a character row's last. It
    goes down only from the left byte: the rightmost place of a row has its
    right byte in column 32, which INC L makes column 0 a character row on --
    in the margin, never shown, and DEC L undoes it.
    """
    code, line, at = [], 0, 0
    for y in range(16):
        for byte in range(2):
            if not any((8 * byte + bit, y) in draw for bit in range(8)):
                continue
            want = sum(0x80 >> bit for bit in range(8) if (8 * byte + bit, y) in opaque)
            bits = sum(0x80 >> bit for bit in range(8) if (8 * byte + bit, y) in ink) & want
            if line != y and at == 1:
                code.append("\t\t\t\t\tdec\t\tl")
                at = 0
            while line < y:
                if (first_line + line) % 8 == 7:
                    code += NEXT_CHARACTER_ROW
                else:
                    code.append("\t\t\t\t\tinc\t\th")
                line += 1
            if byte != at:
                code.append("\t\t\t\t\tinc\t\tl")
                at = byte
            if want == 0xFF:
                code.append(f"\t\t\t\t\tld\t\t(hl),${bits:02X}")
            else:
                code += ["\t\t\t\t\tld\t\ta,(hl)", f"\t\t\t\t\tand\t\t${0xFF ^ want:02X}"]
                if bits:
                    code.append(f"\t\t\t\t\tor\t\t${bits:02X}")
                code.append("\t\t\t\t\tld\t\t(hl),a")
    return code


def write_block_drawers(blocks: list, path: Path) -> None:
    """A drawer per block picture, unrolled.

    (Drawers that leave out what the covering places paint over were tried:
    a drawer per set of covers, the set worked out for every block. They
    drew less, but finding the whole set cost more than they saved -- see
    plan.md. Whole blocks are drawn, and whole blocks that are covered are
    left out, in paint.s.)
    """
    lines = ["; Generated by painter/build.py from shared/art/blocks.png. Do not edit.", "",
             "; Two drawers a picture: a first half-row's block starts 4 lines into",
             "; a character row, a second half-row's at the top of one.",
             "; In:  HL the block's top left on the screen. Uses A. HL is left",
             "; somewhere in the block."]
    for name, rows in zip(("draw_block_even", "draw_block_odd"), blocks):
        opaque, ink = pixels(rows)
        for half, first_line in (("first", 4), ("second", 0)):
            lines += ["", f"{name}_{half}:"] + drawer_code(opaque, opaque, ink, first_line) \
                + ["\t\t\t\t\tret"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_sprite_pictures(path: Path) -> None:
    """Each sprite picture for paint_sprite: 16 rows of (the left byte's mask,
    its ink, the right byte's mask, its ink), a mask's bits set where the
    picture is clear -- as the block drawers' art is read."""
    tab = "\t\t\t\t\t"
    lines = ["; Generated by painter/build.py from shared/art/sprites.png. Do not edit.", "",
             "sprite_pictures:"]
    for number, (name, rows) in enumerate(read_sprites().items()):
        lines.append(f"PICTURE_{name.upper()}\tEQU\t\t{number}")
        for opaque, ink in rows:
            values = [~opaque >> 8 & 0xFF, ink >> 8 & 0xFF, ~opaque & 0xFF, ink & 0xFF]
            lines.append(f"{tab}DB\t\t" + ", ".join(f"${v:02X}" for v in values))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    OUT.mkdir(exist_ok=True)
    write_view_tables(OUT / "view_tables.s")
    write_block_drawers(read_blocks(), OUT / "blocks_gen.s")
    write_sprite_pictures(OUT / "sprite_pictures.s")
    (OUT / "map.bin").write_bytes(read_map())
    assemble(HERE, "painter")


if __name__ == "__main__":
    main()
